Repository Saumy1905/PYQFort, pull requests merged in 2025-06, with the labels that each got.

#95 PR for Issue #12
  ABV-IIITM Gwalior, MP/01. CSE/CSE syllabus.pdf
  ABV-IIITM Gwalior, MP/02. MSC/MSC syllabus.pdf
  ABV-IIITM Gwalior, MP/03. EEE/EEE syllabus.pdf
  ABV-IIITM Gwalior, MP/04. Integrated Btech+Mtech IT/IMT syllabus.pdf
  ABV-IIITM Gwalior, MP/05. Integrate Btech in IT + MBA/IMG syllabus.pdf
Labels: good first issue, Advanced, SSOC S4

#85 Added PYQs for CSE 1st Sem Chemistry CHEM 1001, Mathematics MTH1101, …
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/1st Sem/Chemistry - I (CHEM1001)/CHEM1001 - 1st Sem 2017.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/1st Sem/Chemistry - I (CHEM1001)/CHEM1001 - 1st Sem 2020.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/1st Sem/Chemistry - I (CHEM1001)/CHEM1001 - 1st Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/1st Sem/Chemistry - I (CHEM1001)/CHEM1001(Backlog) - 1st Sem 2019.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/1st Sem/Chemistry - I (CHEM1001)/CHEM1001(Backlog) - 1st Sem 2020.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/1st Sem/Mathematics- I (MTH1101)/MATH 1101 - 1st Sem 2019.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/1st Sem/Mathematics- I (MTH1101)/MATH 1101 - 1st Sem 2020.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/1st Sem/Mathematics- I (MTH1101)/MATH 1101 - 1st Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/1st Sem/Mathematics- I (MTH1101)/MATH 1101(Backlog) - 1st Sem 2019.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/1st Sem/Mathematics- I (MTH1101)/MATH 1101(Backlog) - 1st Sem 2020.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/1st Sem/Mathematics- I (MTH1101)/MATH 1101(Backlog) - 1st Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/1st Sem/Mathematics- I (MTH1101)/MTH 1101- 1st Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/1st Sem/Mathematics- I (MTH1101)/MTH 1101- 1st Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/1st Sem/Physics - I (PHY1001)/PHY1001-1st Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/1st Sem/Physics - I (PHY1001)/PHYS1001-1st Sem 2021.pdf
  README.md
Labels: enhancement, Beginner, SSOC S4

#89 uploaded kiit 3sem and 4sem pyq
  README(1).md
  kiit/3sem/3EndsemDSA(1).pdf
  kiit/3sem/3EndsemDsa(10).pdf
  kiit/3sem/3EndsemDsa(2).pdf
  kiit/3sem/3EndsemDsa(3).pdf
  kiit/3sem/3EndsemDsa(4).pdf
  kiit/3sem/3EndsemDsa(5).pdf
  kiit/3sem/3EndsemDsa(6).pdf
  kiit/3sem/3EndsemDsa(7).pdf
  kiit/3sem/3EndsemDsa(8).pdf
  kiit/3sem/3EndsemDsa(9).pdf
  kiit/3sem/3EndsemDsa.pdf
  kiit/3sem/3EndsemOOPJ(1).pdf
  kiit/3sem/3EndsemOOPJ(2).pdf
  kiit/3sem/3EndsemOOPJ(3).pdf
  kiit/3sem/3EndsemOOPJ(4).pdf
  kiit/3sem/3EndsemOOPJ(5).pdf
  kiit/3sem/3EndsemOOPJ.pdf
  kiit/4sem/4EndCoa.pdf
  kiit/4sem/4EndsemCoa(1).pdf
  kiit/4sem/4EndsemCoa(2).pdf
  kiit/4sem/4EndsemEco.pdf
  kiit/4sem/4OOPJEndsem.pdf
  kiit/4sem/DBMS 2024.pdf
  kiit/4sem/DBMS_2023_Sol.pdf
  kiit/4sem/Operating System End Sem 2024.pdf
  kiit/4sem/Operating Systems End-2024.pdf
  kiit/4sem/Operating Systems(CS 2002) End.pdf
Labels: enhancement, Intermediate, SSOC S4

#103 Added VRSEC-AP Computer Engineering syllabus
  VRSEC-AP/Computer Engineering/CSE_Syllabus.pdf
Labels: good first issue, Beginner, SSOC S4

#115 Added syllabus for CE, IT, and ME branches from VRSEC
  VRSEC-AP/Information Technology/IT_Syllabus.pdf
  VRSEC-AP/Mechanical Engineering/ME_Syllabus.pdf
Labels: good first issue, Advanced, SSOC S4

#109 Added PYQs of CSE 2nd, 3rd and 4th Sem of HITK
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/2nd Sem/Basic Electrical Engineering (ELE1001)/ELE 1001- 2nd Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/2nd Sem/Basic Electrical Engineering (ELE1001)/ELEC 1001-2022.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/2nd Sem/Basic Electrical Engineering (ELE1001)/ELEC1001 - 2021.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/2nd Sem/Basic Electrical Engineering (ELE1001)/ELEC1001- 2020.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/2nd Sem/Programming for Problem Solving (CSE1001)/CSE1001- 2nd Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/2nd Sem/Programming for Problem Solving (CSE1001)/CSEN 1001- 2nd Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/2nd Sem/Programming for Problem Solving (CSE1001)/CSEN 1001-2nd Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/2nd Sem/Programming for Problem Solving (CSE1001)/CSEN1001- 2nd Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/3rd Sem/Analog Circuits (ECEN2101)/ECEN 2101- 3rd Sem 2020.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/3rd Sem/Analog Circuits (ECEN2101)/ECEN 2101- 3rd Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/3rd Sem/Analog Circuits (ECEN2101)/ECEN 2101- 3rd Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/3rd Sem/Analog Circuits (ECEN2101)/ECEN 2101- 3rd Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/3rd Sem/Data Structures and Algorithms (CSE2101)/CSEN 2101- 3rd Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/3rd Sem/Data Structures and Algorithms (CSE2101)/CSEN 2101- 3rd Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/3rd Sem/Data Structures and Algorithms (CSE2101)/CSEN 2101- 3rd Sem(Backlog) 2020.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/3rd Sem/Data Structures and Algorithms (CSE2101)/CSEN2101- 3rd Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/4th Sem/Design & Analysis of Algorithms (CSEN2201)/CSEN 2201- 4th Sem 2019.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/4th Sem/Design & Analysis of Algorithms (CSEN2201)/CSEN 2201- 4th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/4th Sem/Design & Analysis of Algorithms (CSEN2201)/CSEN 2201- 4th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/4th Sem/Design & Analysis of Algorithms (CSEN2201)/CSEN 2201- 4th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/4th Sem/Operating Systems (CSEN2203)/CSEN 2203- 4th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/4th Sem/Operating Systems (CSEN2203)/CSEN 2203- 4th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/4th Sem/Operating Systems (CSEN2203)/CSEN 2203- 4th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/4th Sem/Operating Systems (CSEN2203)/CSEN 2203- 4th Sem 2024.pdf
Labels: enhancement, Advanced, SSOC S4

#119 Added 24 CSE PYQs for Sem 1, 2, 3 from Velammal College
  Velammal College of Engineering and Technology/CSE/1st Sem/Engineering Chemistry (Nov 2023) (21CH101).pdf
  Velammal College of Engineering and Technology/CSE/1st Sem/Engineering Physics (Apr 2022) (PH3151).pdf
  Velammal College of Engineering and Technology/CSE/1st Sem/Engineering Physics (Nov 2023) (21PH101).pdf
  Velammal College of Engineering and Technology/CSE/1st Sem/Heritage of Tamils (Nov 2023) (21TA101).pdf
  Velammal College of Engineering and Technology/CSE/1st Sem/Matrices and Calculus (Apr 2022) (MA3151).pdf
  Velammal College of Engineering and Technology/CSE/1st Sem/Matrices and Calculus (Nov 2023) (21MA101).pdf
  Velammal College of Engineering and Technology/CSE/1st Sem/Problem Solving and Python Programming (Nov 2023) (21CS101).pdf
  Velammal College of Engineering and Technology/CSE/1st Sem/Professional English-I (Nov 2023) (21EN101).pdf
  Velammal College of Engineering and Technology/CSE/2nd Sem/Basic Electrical and Electronics Engineering (Apr 2022) (BE3251).pdf
  Velammal College of Engineering and Technology/CSE/2nd Sem/Basic Electrical and Electronics for Information Science (April 2024) (21EE104).pdf
  Velammal College of Engineering and Technology/CSE/2nd Sem/Engineering Graphics (April 2024) (21ME101).pdf
  Velammal College of Engineering and Technology/CSE/2nd Sem/English-II (April 2024) (21EN102).pdf
  Velammal College of Engineering and Technology/CSE/2nd Sem/Environmental Science (April 2023) (21CH103).pdf
  Velammal College of Engineering and Technology/CSE/2nd Sem/Environmental Science (April 2024) (21CH103).pdf
  Velammal College of Engineering and Technology/CSE/2nd Sem/Environmental Science (Nov 2023) (21CH103).pdf
  Velammal College of Engineering and Technology/CSE/2nd Sem/Physics for Information Science (April 2024) (21PH103).pdf
  Velammal College of Engineering and Technology/CSE/2nd Sem/Programming in C (April 2024) (21CS103).pdf
  Velammal College of Engineering and Technology/CSE/2nd Sem/Sampling Techniques and Numerical Methods (April 2024) (21MA103).pdf
  Velammal College of Engineering and Technology/CSE/2nd Sem/Tamils and Technology (April 2024) (21TA102).pdf
  Velammal College of Engineering and Technology/CSE/3rd Sem/Computer Organization and Architecture (Nov 2024) (21CS201).pdf
  Velammal College of Engineering and Technology/CSE/3rd Sem/Data Structures (Nov 2023) (21CS202).pdf
  Velammal College of Engineering and Technology/CSE/3rd Sem/Digiital Principles and System Design (Nov 2024) (21EC201).pdf
  Velammal College of Engineering and Technology/CSE/3rd Sem/Discrete Mathematics (Nov 2024) (21MA203).pdf
  Velammal College of Engineering and Technology/CSE/3rd Sem/Object Oriented Programming (Nov 2024) (21CS203).pdf
Labels: enhancement, Advanced, SSOC S4

#123 Psit kanpur
  PSIT_Kanpur/01.Computer Science and Engineering/1st_year_CSE_Syllabus.pdf.pdf
  PSIT_Kanpur/01.Computer Science and Engineering/2nd_year_CSE_Syllabus.pdf.pdf
  PSIT_Kanpur/01.Computer Science and Engineering/3rd Sem/Data Structure (BCS301)/DS (2020) (BCS301).pdf
  PSIT_Kanpur/01.Computer Science and Engineering/3rd Sem/Data Structure (BCS301)/DS (2021) (BCS301).pdf
  PSIT_Kanpur/01.Computer Science and Engineering/3rd Sem/Data Structure (BCS301)/DS (2022) (BCS301).pdf
  PSIT_Kanpur/01.Computer Science and Engineering/3rd Sem/Data Structure (BCS301)/DS (2023) (BCS301).pdf
  PSIT_Kanpur/01.Computer Science and Engineering/3rd Sem/Data Structure (BCS301)/DS (2024) (BCS301).pdf
  PSIT_Kanpur/01.Computer Science and Engineering/3st_year_CSE_Syllabus.pdf.pdf
Labels: enhancement, Beginner, SSOC S4

#125 Added scheme and syllabus of newer branches in nit kkr
  NIT_Kurukshetra/5. IIOT(Industrial Internet Of Things)/Syllabus_1st-4th_sem.pdf
  NIT_Kurukshetra/AI_ML/Scheme-and-Syllabus-of-B.Tech-in-Artificial-Intelligence-and-Machine-Learning_1st_and_2nd.pdf
  NIT_Kurukshetra/Computer Engineering/Scheme-and-Syllabus-of-B.Tech-Computer-Science-and-Engineering.pdf
  NIT_Kurukshetra/Information Technology/Scheme-and-Syllabus-of-B.Tech-Information-Technology.pdf
Labels: good first issue, Advanced, SSOC S4

#138 Added Syllabus for all branches all semesters all majors VIT CHENNAI
  VIT_CHENNAI, Chennai/All majors of B.Tech/Basic Sciences and Maths/BCHY101L_ENGINEERING-CHEMISTRY_TH_1.0_65_BCHY101L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Basic Sciences and Maths/BMAT101L_CALCULUS_TH_1.0_65_BMAT101L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Basic Sciences and Maths/BMAT102L_DIFFERENTIAL-EQUATIONS-AND-TRANSFORMS_TH_1.0_65_BMAT102L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Basic Sciences and Maths/BMAT201L_COMPLEX-VARIABLES-AND-LINEAR-ALGEBRA_TH_1.0_65_BMAT201L (1).pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Basic Sciences and Maths/BMAT202L_PROBABILITY-AND-STATISTICS_TH_1.0_65_BMAT202L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Basic Sciences and Maths/BPHY101L_ENGINEERING-PHYSICS_TH_1.0_65_BPHY101L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Discipline Core/BCSE202L_DATA-STRUCTURES-AND-ALGORITHMS_TH_1.0_67_BCSE202L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Discipline Core/BCSE203E_WEB-PROGRAMMING_ELA_1.0_0_BCSE203E.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Discipline Core/BCSE204L_DESIGN-AND-ANALYSIS-OF-ALGORITHMS_TH_1.0_67_BCSE204L (1).pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Discipline Core/BCSE205L_COMPUTER-ARCHITECTURE-AND-ORGANIZATION_TH_1.0_67_BCSE205L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Discipline Core/BCSE301L_SOFTWARE-ENGINEERING_TH_1.0_67_BCSE301L (1).pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Discipline Core/BCSE302L_DATABASE-SYSTEMS_TH_1.0_67_BCSE302L (1).pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Discipline Core/BCSE303L_OPERATING-SYSTEMS_TH_1.0_67_BCSE303L (1).pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Discipline Core/BCSE304L_THEORY-OF-COMPUTATION_TH_1.0_67_BCSE304L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Discipline Core/BCSE305L_EMBEDDED-SYSTEMS_TH_1.0_67_BCSE305L (1).pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Discipline Core/BCSE306L_ARTIFICIAL-INTELLIGENCE_TH_1.0_67_BCSE306L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Discipline Core/BCSE307L_COMPILER-DESIGN_TH_1.0_67_BCSE307L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Discipline Core/BCSE308L_COMPUTER-NETWORKS_TH_11.0_67_BCSE308L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Discipline Core/BCSE309L_CRYPTOGRAPHY-AND-NETWORK-SECURITY_TH_1.0_67_BCSE309L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Discipline Linked Sciences/BECE102L_DIGITAL-SYSTEMS-DESIGN_TH_1.0_0_BECE102L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Discipline Linked Sciences/BECE204L_MICROPROCESSORS-AND-MICROCONTROLLERS_TH_1.0_0_BECE204L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Discipline Linked Sciences/BMAT205L_DISCRETE-MATHEMATICS-AND-GRAPH-THEORY_TH_1.0_67_BMAT205L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Engineering Sciences (CSE related subjects)/BCSE101E_COMPUTER-PROGRAMMING-PYTHON_ELA_1.0_65_BCSE101E.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Engineering Sciences (CSE related subjects)/BCSE102L_STRUCTURED-AND-OBJECT-ORIENTED-PROGRAMMING_TH_1.0_65_BCSE102L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Engineering Sciences (CSE related subjects)/BCSE103E_COMPUTER-PROGRAMMING-JAVA_ELA_1.0_65_BCSE103E.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Engineering Sciences (CSE related subjects)/BEEE102L_BASIC-ELECTRICAL-AND-ELECTRONICS-ENGINEERING_TH_1.0_0_BEEE102L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Humanities related subjects/BARB101L_ARABIC_TH_1.0_68_BARB101L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Humanities related subjects/BCHI101L_CHINESE-I_TH_1.0_0_BCHI101L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Humanities related subjects/BENG101L_TECHNICAL-ENGLISH-COMMUNICATION_TH_1.0_65_BENG101L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Humanities related subjects/BENG102P_TECHNICAL-REPORT-WRITING_LO_1.0_65_BENG102P.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Humanities related subjects/BESP101L_SPANISH-I_TH_1.0_0_BESP101L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Humanities related subjects/BFRE101L_FRENCH-I_TH_1.0_0_BFRE101L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Humanities related subjects/BGER101L_GERMAN-I_TH_1.0_0_BGER101L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Humanities related subjects/BGRE101L_MODERN-GREEK_TH_1.0_0_BGRE101L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Humanities related subjects/BITL101L_ITALIAN_TH_1.0_0_BITL101L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Humanities related subjects/BJAP101L_JAPANESE-I_TH_1.0_0_BJAP101L (1).pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Humanities related subjects/BKOR101L_BASIC-KOREAN---LEVEL-1_TH_1.0_0_BKOR101L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Specialisation Elective for Robotics/BCSE420L_SENSORS,-ACTUATORS-AND-SIGNAL-CONDITIONING_TH_1.0_0_BCSE420L (2).pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Specialisation Elective for Robotics/BCSE421L_ROBOTICS_-KINEMATICS,-DYNAMICS-AND-MOTION-CONTROL_TH_1.0_0_BCSE421L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Specialisation Elective for Robotics/BCSE422L_ROBOT-MODELING-AND-SIMULATION_TH_1.0_0_BCSE422L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Specialisation Elective for Robotics/BCSE423L_ROBOT-PROGRAMMING_TH_1.0_0_BCSE423L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Specialisation Elective for Robotics/BCSE424L_MACHINE-LEARNING-FOR-ROBOTICS_TH_1.0_0_BCSE424L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Specialisation Elective for Robotics/BCSE425L_ROBOTIC-PERCEPTION_TH_1.0_0_BCSE425L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Specialisation Elective for Robotics/BCSE426L_ROBOTIC-PROCESS-AUTOMATION_TH_1.0_0_BCSE426L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Specialisation Elective for Robotics/BCSE427L_COGNITIVE-ROBOTICS_TH_1.0_0_BCSE427L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Specialisation Elective for Robotics/BCSE428L_AUTONOMOUS-DRONES_TH_1.0_0_BCSE428L.pdf
  VIT_CHENNAI, Chennai/All_branch_curriculum_pdf.pdf
Labels: good first issue, Advanced, SSOC S4

#144 Recommited: Syllabus addition for all majors of VIT CHENNAI
  VIT_CHENNAI, Chennai/All majors of B.Tech/Humanities related subjects/BCLE214L_GLOBAL-WARMING_TH_1.0_0_BCLE214L.pdf
  VIT_CHENNAI, Chennai/All majors of B.Tech/Humanities related subjects/BCLE215L_WASTE-MANAGEMENT_TH_1.0_68_BCLE215L.pdf
Labels: good first issue, Advanced, SSOC S4

#159 Added the pyq of all subject of 2nd sem cse department
  MAKAUT/btech-2-sem-chemistry-1-bsch201-2024.pdf
  MAKAUT/btech-2-sem-english-hmhu201-2024.pdf
  MAKAUT/btech-2-sem-mathematics-2a-bsm201-2024.pdf
  MAKAUT/btech-2-sem-physics-1-bsph201 2024.pdf
  MAKAUT/btech-es-cs-2-sem-programming-for-problem-solving-escs201-2024.pdf
Labels: enhancement, Intermediate, SSOC S4

#175 Added subject directories & 25 PYQs in total in 3 semesters of ECE(Task-2.3.3)
  NIT_Kurukshetra/1. ECE/2nd Sem/Circuit Theory(ECPC-101)/End sem(ECPC-101)(May 2024).pdf
  NIT_Kurukshetra/1. ECE/2nd Sem/Circuit Theory(ECPC-101)/Mid sem1(ECPC-101)(Feb 2024).pdf
  NIT_Kurukshetra/1. ECE/2nd Sem/Circuit Theory(ECPC-101)/Mid sem2(ECPC-101)(April 2024).pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Communication Engineering(ECPC-205)/End sem ECPC 205.pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Communication Engineering(ECPC-205)/Mid sem 2 ECPC 205.pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Communication Engineering(ECPC-205)/Mid sem ECPC 205.pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Digital Design(ECPC-202)/End sem ECPC 202.pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Digital Design(ECPC-202)/Mid sem 2 ECPC 202.pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Digital Design(ECPC-202)/Mid sem ECPC 202.pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Electronic Devices & Circuits(ECPC-201)/End Sem ECPC 201.pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Electronic Devices & Circuits(ECPC-201)/Mid sem 2 ECPC 201.pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Electronic Devices & Circuits(ECPC-201)/Mid sem ECPC 201.pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Field and Waves(ECPC-204)/End sem ECPC 204.pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Field and Waves(ECPC-204)/Mid sem 2 ECPC 204.pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Field and Waves(ECPC-204)/Mid sem ECPC 204.pdf
  NIT_Kurukshetra/1. ECE/4th Sem/Analog Electronics (ECPC-209)/End sem(ECPC-209)(May 2024).pdf
  NIT_Kurukshetra/1. ECE/4th Sem/Applied Linear Algebra (MAIC-204)/End sem(MAIC-204)(May 2024).pdf
  NIT_Kurukshetra/1. ECE/4th Sem/Computer Architecture(ECPC-211)/End sem(ECPC-211)(May 2024).pdf
  NIT_Kurukshetra/1. ECE/4th Sem/Computer Architecture(ECPC-211)/Mid sem2(ECPC-211)(April 2024).pdf
  NIT_Kurukshetra/1. ECE/4th Sem/Digital Communication (ECPC-210)/End sem(ECPC-210)(May 2024)-2.pdf
  NIT_Kurukshetra/1. ECE/4th Sem/Digital Communication (ECPC-210)/Mid sem1(ECPC-210)(Feb 2024).pdf
  NIT_Kurukshetra/1. ECE/4th Sem/Digital Communication (ECPC-210)/Mid sem1b(ECPC-210)(Feb 2024).pdf
  NIT_Kurukshetra/1. ECE/4th Sem/Information Theory & Coding (ECPC-212)/End sem(ECPC-212)(May 2024).pdf
  NIT_Kurukshetra/1. ECE/4th Sem/Information Theory & Coding (ECPC-212)/Mid sem1(ECPC-212)(Feb 2024).pdf
  NIT_Kurukshetra/1. ECE/4th Sem/Information Theory & Coding (ECPC-212)/Mid sem2(ECPC-212)(April 2024).pdf
Labels: enhancement, Advanced, SSOC S4

#161 added branch for NIT_Sikkim
  NIT_SIKKIM/05. Electrical/B.Tech_EEE_Course_structure_2023-27.pdf
Labels: good first issue, Beginner, SSOC S4

#170 ABVIIITM IMT SEM 1-2 PYQs Added
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/1st Sem/Engeneering Mathematics (ES-102)/Maths minor (2023) (IT-102).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/1st Sem/Engineering Physics (ES-101)/EP major (2023) (ES-101).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/1st Sem/Enginnering Design Principles (EE-102)/EDP (2023) (EE-102).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/1st Sem/Fundamentals of Electrical Engineering (EE-101)/edp major (2023) (EEE-102).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/1st Sem/Fundamentals of Electrical Engineering (EE-101)/edp minor (2023) (IT-102).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/1st Sem/Fundamentals of Electrical Engineering (EE-101)/fee major (2023) (EE-101).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/1st Sem/Fundamentals of Electrical Engineering (EE-101)/fee minor (2023) (EE-101).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/1st Sem/Principles of Computer Programming (IT-101)/PCP major (2023) (IT-101).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/1st Sem/Sports and Physical Education/spe major (2023).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/2nd Sem/Data Structures and Algorithms (IT-102)/DS (2024) (IT-102).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/2nd Sem/Data Structures and Algorithms (IT-102)/DS MAJORS_IMG-SEM2 (2024) (IT-102).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/2nd Sem/Digital Electronics (EE-103)/DE MAJORS_IMG-SEM2 (2024) (EE-103).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/2nd Sem/Digital Electronics (EE-103)/DE MINORS_IMG-SEM2-3 (2024) (EE-103).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/2nd Sem/Digital Electronics (EE-103)/digital major (2025) (EE-103).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/2nd Sem/Engineering and environmental sciences (ES-106)/EES MAJORS_IMG-SEM2 (2024) (ES-103).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/2nd Sem/Engineering and environmental sciences (ES-106)/EES MINORS_IMG-SEM2 (2024) (HS-103).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/2nd Sem/Hardware (EE-104)/HWS MAJORS_IMG-SEM2 (2024) (EE-104).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/2nd Sem/Mobile Application Technology (EE-105)/MAT LAB MAJORS_IMG-SEM2 (2024) (EE-105).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/2nd Sem/Mobile Application Technology (EE-105)/MAT MAJORS_IMG-SEM2 (2024) (EE-105).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/2nd Sem/Mobile Application Technology (EE-105)/MAT MINORS_IMG-SEM2 (2024) (EE-105).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/2nd Sem/Object Oriented Programming (IT-104)/OOPS MAJORS_IMG-SEM (2024) (IT-102).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/2nd Sem/Object Oriented Programming (IT-104)/OOPS MINORS_IMG-SEM2 (2024) (IT-102).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/2nd Sem/Object Oriented Programming (IT-104)/OOPS major (2025) (ES-102).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/2nd Sem/Probability and Statistics (ES-103)/PNS MAJORS_IMG-SEM2 (2024) (ES-103).pdf
  ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/2nd Sem/Probability and Statistics (ES-103)/PNS MINORS_IMG-SEM2 (2024) (MA-102).pdf
Labels: enhancement, Advanced, SSOC S4

#172 Added 16 PYQs for MAIT Sem 3
  MAIT DELHI (GGSIPU)/Semester 3/Computer Science Engineering CSE/Discrete Mathematics CIC-205/DM End Term 2024.pdf
  MAIT DELHI (GGSIPU)/Semester 3/Computer Science Engineering CSE/Discrete Mathematics CIC-205/DM mid sem 1 - 2023.pdf
  MAIT DELHI (GGSIPU)/Semester 3/Computer Science Engineering CSE/Discrete Mathematics CIC-205/DM_PYQ_feb_23.pdf
  MAIT DELHI (GGSIPU)/Semester 3/Computer Science Engineering CSE/OOPS CIC-211/End Term April 2016.pdf
  MAIT DELHI (GGSIPU)/Semester 3/Computer Science Engineering CSE/OOPS CIC-211/End Term Feb 2023.pdf
  MAIT DELHI (GGSIPU)/Semester 3/Computer Science Engineering CSE/OOPS CIC-211/OOPS End Term 2024.pdf
  MAIT DELHI (GGSIPU)/Semester 3/Electronics and Communication Engineering ECE/Analog Communication ECC-209/AC mid sem 1.pdf
  MAIT DELHI (GGSIPU)/Semester 3/Electronics and Communication Engineering ECE/Analog Communication ECC-209/Analog Comm Paper 2022-23.pdf
  MAIT DELHI (GGSIPU)/Semester 3/Electronics and Communication Engineering ECE/Digital Logic and Circuit Design/DLCD End Term 2024.pdf
  MAIT DELHI (GGSIPU)/Semester 3/Electronics and Communication Engineering ECE/Digital Logic and Circuit Design/DLCD mid sem 2.pdf
  MAIT DELHI (GGSIPU)/Semester 3/Electronics and Communication Engineering ECE/Digital Logic and Circuit Design/Mid Term PYQs 22.pdf
  MAIT DELHI (GGSIPU)/Semester 3/Information Technology and Engineering ITE/Computational Methods ES-201/CM End Term 2024.pdf
  MAIT DELHI (GGSIPU)/Semester 3/Information Technology and Engineering ITE/Computational Methods ES-201/Mid term QP 2022.pdf
  MAIT DELHI (GGSIPU)/Semester 3/Information Technology and Engineering ITE/Data Structures CIC-209/DS End Term 2024.pdf
  MAIT DELHI (GGSIPU)/Semester 3/Information Technology and Engineering ITE/Data Structures CIC-209/DS mid sem 1 - 2023.pdf
  MAIT DELHI (GGSIPU)/Semester 3/Information Technology and Engineering ITE/Data Structures CIC-209/Endsem 2023 Feb.pdf
Labels: enhancement, Beginner, SSOC S4

#176 Added PYQS for PDPM-IIITDMJ semester 3 and 4 ECE subjects
  PDPM-IIITDMJ/Semester3/DSA(IT2002)/DEMI(2022-PYP).pdf
  PDPM-IIITDMJ/Semester3/Digital_Electronics(DEMI)/DEMI(2022-PYP).pdf
  PDPM-IIITDMJ/Semester3/Electronic_Devices_and_Circuits(EC204a)/EC204a(2022-PYP).pdf
  PDPM-IIITDMJ/Semester3/Electronic_Devices_and_Circuits(EC204a)/EDC Quiz 1.jpg
  PDPM-IIITDMJ/Semester3/Electronic_Devices_and_Circuits(EC204a)/EDC Quiz 2.jpg
  PDPM-IIITDMJ/Semester3/Instrumentation_and_Measurement(EC204b)/EC204b(2022-PYP).pdf
  PDPM-IIITDMJ/Semester3/Network_Theory(EC203b)/EC203b(2022-PYP).pdf
  PDPM-IIITDMJ/Semester3/Network_Theory(EC203b)/Network Theory Quiz 22_09 p1.jpg
  PDPM-IIITDMJ/Semester3/Network_Theory(EC203b)/Network Theory Quiz 22_09 p2.jpg
  PDPM-IIITDMJ/Semester3/Principle_Analog_Communication(EC203a)/EC203a(2022-PYP).pdf
  PDPM-IIITDMJ/Semester3/Principle_Analog_Communication(EC203a)/POAC Quiz 1.jpg
  PDPM-IIITDMJ/Semester3/Principle_Analog_Communication(EC203a)/POAC Quiz 2.jpg
  PDPM-IIITDMJ/Semester4/AI(EC207a)/EC207a_2022PYQ.pdf
  PDPM-IIITDMJ/Semester4/AI(EC207a)/Quiz-1.pdf
  PDPM-IIITDMJ/Semester4/AI(EC207a)/Quiz_2.pdf
  PDPM-IIITDMJ/Semester4/AIC(EC2008)/EC2008_2022PYQ (1).pdf
  PDPM-IIITDMJ/Semester4/Biology(NS2001)/NS2001_2022PYQ (1).pdf
  PDPM-IIITDMJ/Semester4/Cellular_System(EC207b)/ECE207b_2022PYQ.pdf
  PDPM-IIITDMJ/Semester4/Control_Systems(EC2006)/Control Systems Quiz 1.jpg
  PDPM-IIITDMJ/Semester4/Control_Systems(EC2006)/Control Systems Quiz 2.jpg
  PDPM-IIITDMJ/Semester4/Control_Systems(EC2006)/EC2006_2022PYQ.pdf
  PDPM-IIITDMJ/Semester4/DSP(EC2005)/EC2005_2022PYQ.pdf
Labels: enhancement, Intermediate, SSOC S4

#192 Issue #16 Added folders: PS, TE and GE under VRSEC-AP
  VRSEC-AP/11. Power System Engineering/PS_Syllabus.pdf
  VRSEC-AP/12. Thermal Engineering/TE_Syllabus.pdf
  VRSEC-AP/13. Geotechnical Engineering/GE_Syllabus.pdf
Labels: good first issue, Beginner, SSOC S4

#188 UTTRAKHAND TECHNICAL UNIVERSITY PREVIOUS YEAR PAPERS
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM1/AHT001 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM1/AHT002 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM1/AHT003 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM1/AHT004 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM1/BAST101 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM1/BAST102 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM1/BAST104 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM1/BCST101 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM1/BECT101 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM1/BEST101 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM1/BSCT101 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM1/BSCT102 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM1/CST001 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM1/EET001 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM1/MET101 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM2/AHT001 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM2/AHT002 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM2/AHT005 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM2/BAST101 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM2/BAST103 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM2/BAST105 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM2/BAST201 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM2/BAST203 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM2/BCET101 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM2/BCST201 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM2/BECT101 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM2/BEET101 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM2/BEET201 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM2/CST001 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM2/EET001 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2022/SEM2/MET001 (2022).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2023/SEM 3/AHT006 (2023).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2023/SEM 3/AIML001 (2023).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2023/SEM 3/BCET301 (2023).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2023/SEM 3/BCST302 (2023).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2023/SEM 3/BCST303 (2023).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2023/SEM 3/BEET305 (2023).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2023/SEM 3/CST002 (2023).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2023/SEM 3/CST003 (2023).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2023/SEM 3/CST005 (2023).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2023/SEM 3/CST006 (2023).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2023/SEM 3/DST001 (2023).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2023/SEM 3/MET051 (2023).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2023/SEM 3/SAI301 (2023).pdf
  UTTRAKHAND TECHNICAL UNIVERSITY/2023/SEM 3/SCS301 (2023).pdf
Labels: enhancement, Advanced, SSOC S4

#186 Added subject directories & 24 PYQs in total in 3 semesters(Task-2.3.13)
  NIT_Kurukshetra/1. ECE/2nd Sem/Integral Calculus & Difference Equation(MAIC-102)/End sem(MAIC-102)(May 2024).pdf
  NIT_Kurukshetra/1. ECE/2nd Sem/Integral Calculus & Difference Equation(MAIC-102)/Mid sem1(MAIC-102)(Feb 2024).pdf
  NIT_Kurukshetra/1. ECE/2nd Sem/Integral Calculus & Difference Equation(MAIC-102)/Mid sem2(MAIC-102)(April 2024).pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Communication Engineering(ECPC-205)/Mid sem1(ECPC-205)(Sept 2024).pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Communication Engineering(ECPC-205)/Mid sem2(ECPC-205)(Oct 2024).pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Digital Design(ECPC-202)/Mid sem1(ECPC-202)(Sept 2024).pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Electronic Devices & Circuits(ECPC-201)/End sem(ECPC-201)(Dec 2024).pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Electronic Devices & Circuits(ECPC-201)/Mid sem1(ECPC-201)(Sept 2024).pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Electronic Devices & Circuits(ECPC-201)/Mid sem2(ECPC-201)(Oct 2024).pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Field and Waves(ECPC-204)/End sem(ECPC-204)(Dec 2024).pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Field and Waves(ECPC-204)/Mid sem1(ECPC-204)(Sept 2024).pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Field and Waves(ECPC-204)/Mid sem2(ECPC-204)(Oct 2024).pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Machine Learning & Data  Analytics(CSIC-221)/End sem(CSIC-221)(Dec 2024).pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Machine Learning & Data  Analytics(CSIC-221)/Mid sem1(CSIC-221)(Sept 2024).pdf
  NIT_Kurukshetra/1. ECE/3rd Sem/Machine Learning & Data  Analytics(CSIC-221)/Mid sem2(CSIC-221)(Oct 2024).pdf
  NIT_Kurukshetra/5. Computer Engineering/4th Sem/Computer Networks(CSPC-202)/CSPC26 ES 2022.pdf
  NIT_Kurukshetra/5. Computer Engineering/4th Sem/Computer Networks(CSPC-202)/CSPC26 MS1 2022.pdf
  NIT_Kurukshetra/5. Computer Engineering/4th Sem/Computer Networks(CSPC-202)/CSPC26 MS2 2022.pdf
  NIT_Kurukshetra/5. Computer Engineering/4th Sem/Computer Networks(CSPC-202)/CSPC26-MS1-2023.pdf
  NIT_Kurukshetra/5. Computer Engineering/4th Sem/Computer Networks(CSPC-202)/CSPC26-MS2-2023.pdf
  NIT_Kurukshetra/5. Computer Engineering/4th Sem/Operating Systems(CSPC-200)/CSPC20 ES 2022.pdf
  NIT_Kurukshetra/5. Computer Engineering/4th Sem/Operating Systems(CSPC-200)/CSPC20 MS1 2022.pdf
  NIT_Kurukshetra/5. Computer Engineering/4th Sem/Operating Systems(CSPC-200)/CSPC20 MS1 2023.pdf
  NIT_Kurukshetra/5. Computer Engineering/4th Sem/Operating Systems(CSPC-200)/CSPC20 MS2 2023.pdf
  NIT_Kurukshetra/5. Computer Engineering/CE_syllabus(2nd_year).pdf
Labels: enhancement, Advanced, SSOC S4

#197 Added IIIT Jabalpur syllabus structure for CSE, ME, and ECE
  IIIT JABALPUR/01. CSE/CSE_Syllabus.pdf
  IIIT JABALPUR/02. ME/ME_Syllabus.pdf
  IIIT JABALPUR/03. ECE/ECE_Syllabus.pdf
  IIIT JABALPUR/Syllabus.pdf
Labels: good first issue, Intermediate, SSOC S4

#223 [Fixes #220] Added README with Google Drive Link for PLA1001 Notes – VIT Bhopal
  VIT Bhopal University/01. Computer Engineering/README.md
  VIT Bhopal University/01. Computer Engineering/Syllabus Notes/Programming For Computing Engineers (PLA1001)/README.md
Labels: enhancement, Intermediate, SSOC S4

#221 Task 2.2.8: Added 21 PYQs across 2 semesters
  VRSEC-AP/Information Technology/SEMESTER 2/Data Structures (23IT3304)/Data Structures (23IT3304) April-2017.pdf
  VRSEC-AP/Information Technology/SEMESTER 2/Data Structures (23IT3304)/Data Structures (23IT3304) April-2019.pdf
  VRSEC-AP/Information Technology/SEMESTER 2/Data Structures (23IT3304)/Data Structures (23IT3304) December -2023.pdf
  VRSEC-AP/Information Technology/SEMESTER 2/Data Structures (23IT3304)/Data Structures (23IT3304) January -2023.pdf
  VRSEC-AP/Information Technology/SEMESTER 2/Data Structures (23IT3304)/Data Structures (23IT3304) June -2015.pdf
  VRSEC-AP/Information Technology/SEMESTER 2/Data Structures (23IT3304)/Data Structures (23IT3304) March -2021.pdf
  VRSEC-AP/Information Technology/SEMESTER 2/Data Structures (23IT3304)/Data Structures (23IT3304) March -2022.pdf
  VRSEC-AP/Information Technology/SEMESTER 2/Data Structures (23IT3304)/Data Structures (23IT3304) May -2016.pdf
  VRSEC-AP/Information Technology/SEMESTER 2/Data Structures (23IT3304)/Data Structures (23IT3304) November -2015.pdf
  VRSEC-AP/Information Technology/SEMESTER 2/Data Structures (23IT3304)/Data Structures (23IT3304) November -2017.pdf
  VRSEC-AP/Information Technology/SEMESTER 2/Data Structures (23IT3304)/Data Structures (23IT3304) November -2018.pdf
  VRSEC-AP/Information Technology/SEMESTER 2/Data Structures (23IT3304)/Data Structures (23IT3304) November -2019.pdf
  VRSEC-AP/Information Technology/SEMESTER 2/Data Structures (23IT3304)/Data Structures (23IT3304) November -2024.pdf
  VRSEC-AP/Information Technology/SEMESTER 2/Data Structures (23IT3304)/Data Structures (23IT3304) October-2019.pdf
  VRSEC-AP/Information Technology/SEMESTER 3/23HS3102 UNIVERSAL HUMAN VALUES-II/23HS3102 UNIVERSAL HUMAN VALUES-II Dec-2023.PDF
  VRSEC-AP/Information Technology/SEMESTER 3/23HS3102 UNIVERSAL HUMAN VALUES-II/23HS3102 UNIVERSAL HUMAN VALUES-II Dec-2024.PDF
  VRSEC-AP/Information Technology/SEMESTER 3/23HS3102 UNIVERSAL HUMAN VALUES-II/23HS3102 UNIVERSAL HUMAN VALUES-II July-2022.pdf
  VRSEC-AP/Information Technology/SEMESTER 3/23HS3102 UNIVERSAL HUMAN VALUES-II/23HS3102 UNIVERSAL HUMAN VALUES-II June-2023.pdf
  VRSEC-AP/Information Technology/SEMESTER 3/23HS3102 UNIVERSAL HUMAN VALUES-II/23HS3102 UNIVERSAL HUMAN VALUES-II June-2024.PDF
  VRSEC-AP/Information Technology/SEMESTER 3/23HS3102 UNIVERSAL HUMAN VALUES-II/23HS3102 UNIVERSAL HUMAN VALUES-II November-2024.PDF
  VRSEC-AP/Information Technology/SEMESTER 3/23HS3102 UNIVERSAL HUMAN VALUES-II/23HS3102 UNIVERSAL HUMAN VALUES-II October-2019.pdf
Labels: enhancement, Intermediate, SSOC S4

#216 Added AIML Syllabus for VR Siddhartha Engineering College
  VRSEC/01. Computer Engineering/AIML_Syllabus.pdf.pdf
Labels: good first issue, Beginner, SSOC S4

#229 Added RTMNU-CSE-all-8 SEM-PYQs
  RTMNU-Nagpur University (CSE pyq)/1sem/calculus M1/1-sem-basic-calculus-and-differential-equations-2638-winter-2024.pdf
  RTMNU-Nagpur University (CSE pyq)/1sem/chemistry/1-sem-essentials-of-chemistry-2630-winter-2024.pdf
  RTMNU-Nagpur University (CSE pyq)/1sem/communicationSkills/1-sem-communication-skills-12614-winter-2024.pdf
  RTMNU-Nagpur University (CSE pyq)/1sem/digitalCircuit-logicDesign/1-sem-digital-circuits-and-logic-design-2635-winter-2024.pdf
  RTMNU-Nagpur University (CSE pyq)/1sem/enginerringGraphics/1-sem-engineering-graphics-1-3286-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/1sem/programming/1-sem-programming-for-problem-solving-2636-winter-2024.pdf
  RTMNU-Nagpur University (CSE pyq)/2sem/M2/2-sem-applied-mathematics-2-3287-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/2sem/appliedChemistry/2-sem-applied-chemistry-2503-winter-2022.pdf
  RTMNU-Nagpur University (CSE pyq)/2sem/appliedPhysics/2-sem-advanced-physics-3288-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/2sem/bee/2-sem-advanced-electrical-engineering-3291-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/2sem/mechanics/2-sem-engineering-mechanics-3290-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/3sem/CADS/cse-3-sem-computer-architecture-and-digital-system-2572-winter-2023.pdf
  RTMNU-Nagpur University (CSE pyq)/3sem/Etnics IT/cse-3-sem-ethics-in-it-2533-winter-2022.pdf
  RTMNU-Nagpur University (CSE pyq)/3sem/OS/cse-3-sem-operating-system-2571-winter-2023.pdf
  RTMNU-Nagpur University (CSE pyq)/3sem/UHV/cse-3-sem-universal-human-values-2574-winter-2023.pdf
  RTMNU-Nagpur University (CSE pyq)/3sem/appliedMathematics/cse-3-sem-applied-mathematics-3-2569-winter-2023.pdf
  RTMNU-Nagpur University (CSE pyq)/3sem/objectOrientedprograming/cse-3-sem-object-oriented-programming-with-java-2570-winter-2023.pdf
  RTMNU-Nagpur University (CSE pyq)/4sem/OS/cse-4-sem-operating-system-3380-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/4sem/SP/cse-4-sem-system-programming-3382-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/4sem/TOC/cse-4-sem-theoretical-foundations-of-computer-TOC-3381-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/4sem/dmgt/cse-it-4-sem-discrete-mathematics-and-graph-2582-summer-2023.pdf
  RTMNU-Nagpur University (CSE pyq)/4sem/dmgt/cse-it-4-sem-discrete-mathematics-and-graph-theory-2622-summer-2024.pdf
  RTMNU-Nagpur University (CSE pyq)/4sem/dspd/cse-4-sem-data-structure-and-program-design-3379-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/5sem/AI/cse-5-sem-artificial-intelligence-2371-winter-2024.pdf
  RTMNU-Nagpur University (CSE pyq)/5sem/SoftwareEngineering&ProductMangement/cse-5-sem-software-engineering-and-project-management-2373-winter-2024.pdf
  RTMNU-Nagpur University (CSE pyq)/5sem/dataWarehosing&Minimal/cse-5-sem-data-warehousing-and-mining-2376-winter-2024.pdf
  RTMNU-Nagpur University (CSE pyq)/5sem/desing&Analysis&Algorithm/cse-5-sem-design-and-analysis-and-algorithms-2372-winter-2024.pdf
  RTMNU-Nagpur University (CSE pyq)/5sem/effectiveTechnicalCommunication/cse-5-sem-effective-technical-communication-2377-winter-2024.pdf
  RTMNU-Nagpur University (CSE pyq)/6sem/AI/cse-6-sem-ai-artificial-intelligence-3490-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/6sem/CompilerDesign/cse-6-sem-compiler-design-2774-summer-2024.pdf
  RTMNU-Nagpur University (CSE pyq)/6sem/CompurtNetwork/cse-6-sem-computer-networks-3493-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/6sem/ML/cse-6-sem-machine-learning-2775-summer-2024.pdf
  RTMNU-Nagpur University (CSE pyq)/6sem/designPattern/cse-6-sem-design-patterns-3491-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/6sem/distributedOperatingSystem/cse-6-sem-distributed-operating-systems-2779-summer-2024.pdf
  RTMNU-Nagpur University (CSE pyq)/6sem/economicsofIT/cse-6-sem-economics-of-it-industry-2784-summer-2024.pdf
  RTMNU-Nagpur University (CSE pyq)/6sem/linuxFundamental/cse-6-sem-linux-fundamentals-2741-summer-2023.pdf
  RTMNU-Nagpur University (CSE pyq)/6sem/softwareEnginnering/cse-6-sem-software-engineering-and-project-management-sepm-3492-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/7sem/AdvancedComputerArchitecture/cse-7-sem-advanced-computer-architecture-3574-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/7sem/DeepLearning/cse-7-sem-deep-learning-2877-winter-2023.pdf
  RTMNU-Nagpur University (CSE pyq)/7sem/bigDataAnalysis&bussines/cse-7-sem-big-data-analysis-and-business-intelligence-3575-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/7sem/dataWarehosing&Mining/cse-7-sem-data-warehousing-and-mining-3571-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/7sem/pythonPrograming/cse-7-sem-python-programming-2884-winter-2023.pdf
  RTMNU-Nagpur University (CSE pyq)/8sem/AdvancedWirelessSensorNetwork/cse-8-sem-advanced-wireless-sensor-network-3696-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/8sem/Clustering&cloudComputing/cse-8-sem-clustering-and-cloud-computing-3695-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/8sem/NaturalLanguageProcessing(NLP)/cse-8-sem-natural-language-processing-3698-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/8sem/ObjectOriented-SoftwareEnginerring/cse-8-sem-object-oriented-software-engineering.pdf
  RTMNU-Nagpur University (CSE pyq)/8sem/digitalForensic/cse-8-sem-digital-forensic-3699-summer-2019.pdf
  RTMNU-Nagpur University (CSE pyq)/8sem/information&cyberSecurity/cse-8-sem-information-and-cyber-security-3691-summer-2019.pdf
Labels: enhancement, Beginner, SSOC S4

#231 Merged all the 3 directories of KIIT University(issue no :226)
  KIIT UNIVERSITY/PYQs/1st Sem/MA-11001/2018 (1).pdf
  KIIT UNIVERSITY/PYQs/1st Sem/MA-11001/2019.pdf
  KIIT UNIVERSITY/PYQs/1st Sem/MA-11001/2022 (1).pdf
  KIIT UNIVERSITY/PYQs/1st Sem/MA-11001/2022 (2).pdf
  KIIT UNIVERSITY/PYQs/1st Sem/MA-11001/2023 (1).pdf
  KIIT UNIVERSITY/PYQs/1st Sem/MA-11001/2023 (2).pdf
  KIIT UNIVERSITY/PYQs/1st Sem/PH-1003/2024 (2).pdf
  KIIT UNIVERSITY/PYQs/1st Sem/PH-1003/2024 (3).pdf
  KIIT UNIVERSITY/PYQs/2nd Sem/CH-1001/2018 (2).pdf
  KIIT UNIVERSITY/PYQs/2nd Sem/CH-1001/2019 (1).pdf
  KIIT UNIVERSITY/PYQs/2nd Sem/CH-1001/2019_2.pdf
  KIIT UNIVERSITY/PYQs/2nd Sem/EC-1001/2018 (3).pdf
  KIIT UNIVERSITY/PYQs/2nd Sem/HS-10001/2020.pdf
  KIIT UNIVERSITY/PYQs/2nd Sem/HS-10001/2022 (3).pdf
  KIIT UNIVERSITY/PYQs/2nd Sem/HS-10001/2024 (4).pdf
  KIIT UNIVERSITY/PYQs/2nd Sem/HS-10001/2024 (5).pdf
  KIIT UNIVERSITY/PYQs/3rd Sem/EX-20001/2023 (4).pdf
  KIIT UNIVERSITY/PYQs/3rd Sem/EX-20001/2023 (5).pdf
  KIIT UNIVERSITY/PYQs/3rd Sem/EX-20001/2024_1 (1).pdf
  KIIT UNIVERSITY/PYQs/3rd Sem/EX-20001/2024_1.pdf
  KIIT UNIVERSITY/PYQs/3rd Sem/EX-20001/2024_2 (2).pdf
  KIIT UNIVERSITY/PYQs/3rd Sem/EX-20001/2024_2 (3).pdf
  KIIT UNIVERSITY/PYQs/3rd Sem/EX-20003/2023 (3).pdf
  KIIT UNIVERSITY/PYQs/3rd Sem/MA-2011/2023_2.pdf
  KIIT UNIVERSITY/PYQs/4th sem/2020_2.pdf
  KIIT UNIVERSITY/PYQs/4th sem/2024_2 (1).pdf
  KIIT UNIVERSITY/PYQs/4th sem/coa 2018.pdf
  KIIT UNIVERSITY/PYQs/4th sem/os 2018.pdf
  KIIT UNIVERSITY/PYQs/4th sem/stw 2023.pdf
  KIIT UNIVERSITY/SYLLABUS/BEE(Basic electrical engineering)_Lesson Plan Autumn Semester.docx.pdf
  KIIT UNIVERSITY/SYLLABUS/BiomedicalEngineering.pdf
  KIIT UNIVERSITY/SYLLABUS/COA Lesson Plan-spring-2025.docx.pdf
  KIIT UNIVERSITY/SYLLABUS/CS-20006 DBMS Course Handout SPRING 2025.pdf
  KIIT UNIVERSITY/SYLLABUS/Course Handout   Discrete Mathematics.pdf
  KIIT UNIVERSITY/SYLLABUS/Course Handout Basic Electronics.docx.pdf
  KIIT UNIVERSITY/SYLLABUS/Course Handout_Differential_Equations_&_Linear_Algebra.pdf
  KIIT UNIVERSITY/SYLLABUS/Course Handout_Probability and Statistics (MA 21001).pdf
  KIIT UNIVERSITY/SYLLABUS/Course Plan_Day Wise_Automata_Theory_and_Formal_language.pdf
  KIIT UNIVERSITY/SYLLABUS/Creativity,Innovation and Entrepreneurship Handout.docx.pdf
  KIIT UNIVERSITY/SYLLABUS/DBMS Lab (CS 29006) Lesson Plan.pdf
  KIIT UNIVERSITY/SYLLABUS/Industrial Control and Remote monitoring.doc.pdf
  KIIT UNIVERSITY/SYLLABUS/Lesson Plan Economics of Developement.docx.pdf
  KIIT UNIVERSITY/SYLLABUS/Modified_OS-Day wise Course_Handout Spring 2025_4th sem - Copy.doc.pdf
Labels: enhancement, Intermediate, SSOC S4

#232 Added 24 PYQs for CSE 5th,6th,7th Sem of HITK
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/5th Sem/Artificial Intelligence (CSEN3141)/CSEN 3111- 5th Sem 2020.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/5th Sem/Artificial Intelligence (CSEN3141)/CSEN 3111- 5th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/5th Sem/Artificial Intelligence (CSEN3141)/CSEN 3111- 5th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/5th Sem/Artificial Intelligence (CSEN3141)/CSEN 3141- 5th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/5th Sem/Object Oriented Programming (CSEN3003)/CSEN 3003- 5th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/5th Sem/Object Oriented Programming (CSEN3003)/CSEN 3103- 5th Sem 2020.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/5th Sem/Object Oriented Programming (CSEN3003)/CSEN 3103- 5th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/5th Sem/Object Oriented Programming (CSEN3003)/CSEN 3103- 5th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/6th Sem/Machine Learning (CSE3233)/CSEN 3233- 6th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/6th Sem/Machine Learning (CSE3233)/CSEN 3233- 6th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/6th Sem/Machine Learning (CSE3233)/CSEN 3233- 6th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/6th Sem/Machine Learning (CSE3233)/CSEN 3233- 6th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/6th Sem/Software Engineering (CSE3201)/CSEN 3201- 6th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/6th Sem/Software Engineering (CSE3201)/CSEN 3201- 6th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/6th Sem/Software Engineering (CSE3201)/CSEN 3201- 6th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/6th Sem/Software Engineering (CSE3201)/CSEN 3201- 6th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/7th Sem/Cryptography & Network Security (CSE4132)/CSEN 4132- 7th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/7th Sem/Cryptography & Network Security (CSE4132)/CSEN 4132- 7th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/7th Sem/Cryptography & Network Security (CSE4132)/CSEN 4132- 7th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/7th Sem/Cryptography & Network Security (CSE4132)/CSEN 4162- 7th Sem 2019.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/7th Sem/Cryptography & Network Security (CSE4132)/CSEN 4162- 7th Sem 2020.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/7th Sem/Principles of Management (HUM4101)/HMTS 4101- 7th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/7th Sem/Principles of Management (HUM4101)/HMTS 4101- 7th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/7th Sem/Principles of Management (HUM4101)/HMTS 4101- 7th Sem 2023.pdf
Labels: enhancement, Advanced, SSOC S4

#238 Syllabus vrsec update : Added Syllabus PDFs for EEE, MCA, MBA – VRSEC
  VRSEC-AP/14.Electrical & Electronics Engineering/VR20-syllabus-09-08-2023.pdf
  VRSEC-AP/PG Programmes/MBA/Microsoft Word - MBA19 Reg Syllabus_1_ - MBA19_SYLLABUS.pdf
  VRSEC-AP/PG Programmes/MCA/Course Structure – VR10 - MCA-SyllabusMCA20-Regulations_n.pdf
  VRSEC-AP/syllabus-md/CSE_Syllabus.md
  VRSEC-AP/syllabus-md/ECE_Syllabus.md
  VRSEC-AP/syllabus-md/IT_Syllabus.md
Labels: good first issue, Intermediate, SSOC S4

#245 Added the pyq of ECE department
  MAKAUT/2nd Sem/C.S.E/btech-2-sem-chemistry-1-bsch201-2024.pdf
  MAKAUT/2nd Sem/C.S.E/btech-2-sem-english-hmhu201-2024.pdf
  MAKAUT/2nd Sem/C.S.E/btech-2-sem-mathematics-2a-bsm201-2024.pdf
  MAKAUT/2nd Sem/C.S.E/btech-2-sem-physics-1-bsph201 2024.pdf
  MAKAUT/2nd Sem/C.S.E/btech-es-cs-2-sem-programming-for-problem-solving-escs201-2024.pdf
  MAKAUT/2nd Sem/E.C.E/btech-2-sem-basic-electrical-engineering-es-ee101-2024e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-2-sem-chemistry-1-bsch201-2023e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-2-sem-chemistry-1-bsch201-2024 (1)e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-2-sem-chemistry-bsch201-2025.pdf
  MAKAUT/2nd Sem/E.C.E/btech-2-sem-english-hmhu201-2023e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-2-sem-english-hmhu201-2024 (1)e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-2-sem-mathematics-2-b-bsm202-2023e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-2-sem-mathematics-2a-bsm-201n-2019e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-2-sem-mathematics-2a-bsm201-2023e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-2-sem-mathematics-2a-bsm201-2024 (1)e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-2-sem-physics-1-bs-ph-201-n-2019e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-2-sem-physics-1-bsph201-2023e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-2-sem-physics-1-bsph201-2024 e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-2-sem-programming-for-problem-solving-escs201-2023e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-cs-201-basic-computation-and-principles-of-computer-programming-2018e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-cs-201-basic-computation-and-principles-of-computer-programming-2019e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-cs-201-chemistry-1-2017e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-es-201-basic-electrical-and-electronic-engineering-2-2018e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-es-201-part-2-basic-electrical-and-electronic-engineering-2-2017e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-es-cs-2-sem-programming-for-problem-solving-escs201-2024 (1)e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-hm-hu-201n-english-2019e.pdf
  MAKAUT/2nd Sem/E.C.E/btech-m-201-mathematics-2-2019e.pdf
Labels: enhancement, Intermediate, SSOC S4

#247 Added PYQs for CSE 3rd,4th,5th,6th,8th Sem
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/3rd Sem/Discrete Mathematics (MTH2103)/CSEN 2102- 3rd Sem 2020.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/3rd Sem/Discrete Mathematics (MTH2103)/CSEN 2102- 3rd Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/3rd Sem/Discrete Mathematics (MTH2103)/CSEN 2102- 3rd Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/3rd Sem/Discrete Mathematics (MTH2103)/CSEN 2102- 3rd Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/4th Sem/Environmental Science (EVSC2016)/EVSC 2016- 4th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/4th Sem/Environmental Science (EVSC2016)/EVSC 2016- 4th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/4th Sem/Environmental Science (EVSC2016)/EVSC 2016- 4th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/4th Sem/Environmental Science (EVSC2016)/EVSC 2016- 4th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/5th Sem/Formal Language & Automata Theory (CSE3002)/CSEN 3002- 5th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/5th Sem/Formal Language & Automata Theory (CSE3002)/CSEN 3101- 5th Sem (Backlog) 2020.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/5th Sem/Formal Language & Automata Theory (CSE3002)/CSEN 3102- 5th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/5th Sem/Formal Language & Automata Theory (CSE3002)/CSEN 3102- 5th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/6th Sem/Economics for Engineers (HUM3201)/HMTS 3101- 5th Sem (Backlog) 2020.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/6th Sem/Economics for Engineers (HUM3201)/HMTS 3201- 6th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/6th Sem/Economics for Engineers (HUM3201)/HMTS 3201- 6th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/6th Sem/Economics for Engineers (HUM3201)/HMTS 3201- 6th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/8th Sem/Introduction to French Language (HMTS4222)/HMTS 4222- 8th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/8th Sem/Introduction to French Language (HMTS4222)/HMTS 4222- 8th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/8th Sem/Introduction to French Language (HMTS4222)/HMTS 4222- 8th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/8th Sem/Pattern Recognition (CSEN4233)/CSEN 4233- 8th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/8th Sem/Pattern Recognition (CSEN4233)/CSEN 4233- 8th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/8th Sem/Pattern Recognition (CSEN4233)/CSEN 4244- 8th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/8th Sem/Web Development With Node and Express (CSEN4237)/CSEN 4237- 8th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/01. Computer Science and Engineering/8th Sem/Web Development With Node and Express (CSEN4237)/CSEN 4237- 8th Sem 2024.pdf
Labels: enhancement, Advanced, SSOC S4

#248 Added PYQ for 8 Subjects
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AD3301-Data Exploration and Visualization Question Papers/PYQ/AD3301 Data Exploration and Visualization Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AD3301-Data Exploration and Visualization Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AD3301-Data Exploration and Visualization Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AD3301-Data Exploration and Visualization Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AD3351-Design and Analysis of Algorithms Question Papers/Lecture Notes/AD3351 Design and Analysis of Algorithms Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AD3351-Design and Analysis of Algorithms Question Papers/PYQ/AD3351 Design and Analysis of Algorithms Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AD3351-Design and Analysis of Algorithms Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AD3351-Design and Analysis of Algorithms Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AD3351-Design and Analysis of Algorithms Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AD3351-Design and Analysis of Algorithms Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AD3391-Database Design and Management Question Papers/Lecture Notes/AD3391 Database Design and Management Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AD3391-Database Design and Management Question Papers/PYQ/AD3391 Database Design and Management Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AD3391-Database Design and Management Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AD3391-Database Design and Management Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AD3391-Database Design and Management Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AD3391-Database Design and Management Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AE3301-Elements of Aeronautical Engineering Question Papers/PYQ/AE3301 Elements of Aeronautical Engineering Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AE3301-Elements of Aeronautical Engineering Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AE3301-Elements of Aeronautical Engineering Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AE3301-Elements of Aeronautical Engineering Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AE3302-Aircraft Systems and Instruments Question Papers/PYQ/AE3302 Aircraft Systems and Instruments Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AE3302-Aircraft Systems and Instruments Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AE3302-Aircraft Systems and Instruments Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AE3302-Aircraft Systems and Instruments Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AE3351-Aero Engineering Thermodynamics Question Papers/PYQ/AE3351 Aero Engineering Thermodynamics Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AE3351-Aero Engineering Thermodynamics Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AE3351-Aero Engineering Thermodynamics Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AE3351-Aero Engineering Thermodynamics Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AE3351-Aero Engineering Thermodynamics Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AE3352-Solid Mechanics Question Papers/PYQ/AE3352 Solid Mechanics Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AE3352-Solid Mechanics Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AE3352-Solid Mechanics Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AE3352-Solid Mechanics Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AE3352-Solid Mechanics Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AL3391-Artificial Intelligence Question Papers/Lecture Notes/AL3391 Artificial Intelligence Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AL3391-Artificial Intelligence Question Papers/PYQ/AL3391 Artificial Intelligence Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AL3391-Artificial Intelligence Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AL3391-Artificial Intelligence Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AL3391-Artificial Intelligence Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/AL3391-Artificial Intelligence Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
Labels: enhancement, Advanced, SSOC S4

#251 #26 Issue - Added SRK-VIJ folder with CSE, AIML, and IT directories
  SRK-VIJ/01. Computer Science Engineering/CSE_Syllabus.pdf
  SRK-VIJ/02. Information Technology/IT_Syllabus.pdf
  SRK-VIJ/03. Artificial Intelligence and Machine Learning/CSE(AIML)_Syllabus.pdf
Labels: good first issue, Intermediate, SSOC S4

#254 [SSOC] Added PYQs for BCSE202L (Data Structures) and BCSE208L (Data Mining) – VIT Bhopal [#241]
  VIT Bhopal University/01. Computer Engineering/Data Mining(BCSE208L)/Data Mining (Dec 2024) (BCSE208L).pdf
  VIT Bhopal University/01. Computer Engineering/Data Mining(BCSE208L)/README.md
  VIT Bhopal University/01. Computer Engineering/Data Structure and algorithm(BCSE202L)/Data Structure and algorithm (Dec 2023) (BCSE202L) (1).pdf
  VIT Bhopal University/01. Computer Engineering/Data Structure and algorithm(BCSE202L)/Data Structure and algorithm (Dec 2023) (BCSE202L) (10).pdf
  VIT Bhopal University/01. Computer Engineering/Data Structure and algorithm(BCSE202L)/Data Structure and algorithm (Dec 2023) (BCSE202L) (2).pdf
  VIT Bhopal University/01. Computer Engineering/Data Structure and algorithm(BCSE202L)/Data Structure and algorithm (Dec 2023) (BCSE202L) (3).pdf
  VIT Bhopal University/01. Computer Engineering/Data Structure and algorithm(BCSE202L)/Data Structure and algorithm (Dec 2023) (BCSE202L) (4).pdf
  VIT Bhopal University/01. Computer Engineering/Data Structure and algorithm(BCSE202L)/Data Structure and algorithm (Dec 2023) (BCSE202L) (5).pdf
  VIT Bhopal University/01. Computer Engineering/Data Structure and algorithm(BCSE202L)/Data Structure and algorithm (Dec 2023) (BCSE202L) (6).pdf
  VIT Bhopal University/01. Computer Engineering/Data Structure and algorithm(BCSE202L)/Data Structure and algorithm (Dec 2023) (BCSE202L) (7).pdf
  VIT Bhopal University/01. Computer Engineering/Data Structure and algorithm(BCSE202L)/Data Structure and algorithm (Dec 2023) (BCSE202L) (8).pdf
  VIT Bhopal University/01. Computer Engineering/Data Structure and algorithm(BCSE202L)/Data Structure and algorithm (Dec 2023) (BCSE202L) (9).pdf
  VIT Bhopal University/01. Computer Engineering/Data Structure and algorithm(BCSE202L)/README.md
  VIT Bhopal University/01. Computer Engineering/README.md
Labels: enhancement, Advanced, SSOC S4

#258 Added 24 PYQs for IT 3rd, 4th, 5th Sem of HITK
  Heritage Institute of Technology, Kolkata/02. Information Technology/3rd Sem/Digital Systems Design (ECEN2002)/ECEN 2002- 3rd Sem 2019.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/3rd Sem/Digital Systems Design (ECEN2002)/ECEN 2002- 3rd Sem 2020.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/3rd Sem/Digital Systems Design (ECEN2002)/ECEN 2002- 3rd Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/3rd Sem/Digital Systems Design (ECEN2002)/ECEN 2002- 3rd Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/3rd Sem/Digital Systems Design (ECEN2002)/ECEN 2002- 3rd Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/3rd Sem/Fundamentals of DSA (INF2101)/INFO 2101- 3rd Sem 2020.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/3rd Sem/Fundamentals of DSA (INF2101)/INFO 2101- 3rd Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/3rd Sem/Fundamentals of DSA (INF2101)/INFO 2101- 3rd Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/3rd Sem/Fundamentals of DSA (INF2101)/INFO 2101- 3rd Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/4th Sem/Algebric Structures (MTH2201)/MATH 2201- 4th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/4th Sem/Algebric Structures (MTH2201)/MATH 2201- 4th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/4th Sem/Algebric Structures (MTH2201)/MATH 2201- 4th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/4th Sem/Algebric Structures (MTH2201)/MATH 2201- 4th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/4th Sem/Database Management Systems (INF2203)/INFO 2204- 4th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/4th Sem/Database Management Systems (INF2203)/INFO 2204- 4th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/4th Sem/Database Management Systems (INF2203)/INFO 2204- 4th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/4th Sem/Database Management Systems (INF2203)/INFO 2204- 4th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/4th Sem/Database Management Systems (INF2203)/INFO 3104- 5th Sem (Backlog) 2020.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/5th Sem/Adavanced Java and Web Technology (INF3101)/INFO 3101- 5th Sem 2020.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/5th Sem/Adavanced Java and Web Technology (INF3101)/INFO 3101- 5th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/5th Sem/Adavanced Java and Web Technology (INF3101)/INFO 3101- 5th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/5th Sem/Adavanced Java and Web Technology (INF3101)/INFO 3101- 5th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/5th Sem/Adavanced Java and Web Technology (INF3101)/INFO 3203- 6th Sem(Backlog) 2022.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/5th Sem/Cyber Security (INF3133)/INFO 3133- 5th Sem 2023.pdf
Labels: enhancement, Advanced, SSOC S4

#256 [#255] Uploaded PYQs for OS, PDC, Web Tech, and Cryptography Lab – VIT Bhopal
  VIT Bhopal University/01. Computer Engineering/Cryptography(BCSE309L)/Cryptography Lab (Dec 2023) (BCSE309L).pdf (2).pdf
  VIT Bhopal University/01. Computer Engineering/Cryptography(BCSE309L)/Cryptography Lab (Dec 2023) (BCSE309L).pdf.pdf
  VIT Bhopal University/01. Computer Engineering/Operating Systems(CSE2005)/Operating Systems (Dec 2018) (CSE2005).pdf (4).pdf
  VIT Bhopal University/01. Computer Engineering/Operating Systems(CSE2005)/Operating Systems (Dec 2019) (CSE2005).pdf (3).pdf
  VIT Bhopal University/01. Computer Engineering/Operating Systems(CSE2005)/Operating Systems (Dec 2020) (CSE2005).pdf (2).pdf
  VIT Bhopal University/01. Computer Engineering/Operating Systems(CSE2005)/Operating Systems (Dec 2020) (CSE2005).pdf.pdf
  VIT Bhopal University/01. Computer Engineering/Operating Systems(CSE2005)/Operating Systems (Dec 2023) (CSE2005).pdf (2).pdf
  VIT Bhopal University/01. Computer Engineering/Operating Systems(CSE2005)/Operating Systems (Dec 2023) (CSE2005).pdf (3).pdf
  VIT Bhopal University/01. Computer Engineering/Operating Systems(CSE2005)/Operating Systems (Dec 2023) (CSE2005).pdf (4).pdf
  VIT Bhopal University/01. Computer Engineering/Operating Systems(CSE2005)/Operating Systems (Dec 2023) (CSE2005).pdf (5).pdf
  VIT Bhopal University/01. Computer Engineering/Operating Systems(CSE2005)/Operating Systems (Dec 2023) (CSE2005).pdf (6).pdf
  VIT Bhopal University/01. Computer Engineering/Operating Systems(CSE2005)/Operating Systems (Dec 2023) (CSE2005).pdf (7).pdf
  VIT Bhopal University/01. Computer Engineering/Operating Systems(CSE2005)/Operating Systems (Dec 2023) (CSE2005).pdf.pdf
  VIT Bhopal University/01. Computer Engineering/Operating Systems(CSE2005)/operating system _Operating Systems (Dec 2023) (CSE2005).pdf.pdf
  VIT Bhopal University/01. Computer Engineering/Parallel and Distributed Computing(CSE4001)/Parallel and Distributed Computing (Dec 2024) (CSE4004).pdf.pdf
  VIT Bhopal University/01. Computer Engineering/web technologies(ITE10012)/Web Technologies (Mar 2019) (ITE10012).pdf (2).pdf
  VIT Bhopal University/01. Computer Engineering/web technologies(ITE10012)/Web Technologies (Mar 2020) (ITE10012).pdf (2).pdf
  VIT Bhopal University/01. Computer Engineering/web technologies(ITE10012)/Web Technologies (Mar 2020) (ITE10012).pdf (3).pdf
  VIT Bhopal University/01. Computer Engineering/web technologies(ITE10012)/Web Technologies (Mar 2020) (ITE10012).pdf (4).pdf
  VIT Bhopal University/01. Computer Engineering/web technologies(ITE10012)/Web Technologies (Mar 2020) (ITE10012).pdf.pdf
  VIT Bhopal University/01. Computer Engineering/web technologies(ITE10012)/Web Technologies (Mar 2025) (ITE10012).pdf.pdf
Labels: enhancement, Advanced, SSOC S4

#260 Added PYQ for Anna University 8 subjects (Semester 3)
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CD3291-Data Structures and Algorithms Question Papers/Lecture Notes/CD3291 Data Structures and Algorithms Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CD3291-Data Structures and Algorithms Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CD3291-Data Structures and Algorithms Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CD3291-Data Structures and Algorithms Question Papers/PYQ/CD3291 Data Structures and Algorithms Question Bank.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CD3291-Data Structures and Algorithms Question Papers/PYQ/CD3291 Data Structures and Algorithms Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CD3291-Data Structures and Algorithms Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CD3291-Data Structures and Algorithms Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CD3291-Data Structures and Algorithms Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3301-Fluid Mechanics Question Papers/Lecture Notes/CE3301 Fluid Mechanics Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3301-Fluid Mechanics Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3301-Fluid Mechanics Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3301-Fluid Mechanics Question Papers/PYQ/CE3301 Fluid Mechanics Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3301-Fluid Mechanics Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3301-Fluid Mechanics Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3302-Construction Materials and Technology Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3302-Construction Materials and Technology Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3302-Construction Materials and Technology Question Papers/PYQ/CE3302 Construction Materials and Technology Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3302-Construction Materials and Technology Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3302-Construction Materials and Technology Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3303-Water Supply and Wastewater Engineering Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3303-Water Supply and Wastewater Engineering Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3303-Water Supply and Wastewater Engineering Question Papers/PYQ/CE3303 Water Supply and Wastewater Engineering Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3303-Water Supply and Wastewater Engineering Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3303-Water Supply and Wastewater Engineering Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3351-Surveying and Levelling Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3351-Surveying and Levelling Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3351-Surveying and Levelling Question Papers/PYQ/CE3351 Surveying and Levelling Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3351-Surveying and Levelling Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3351-Surveying and Levelling Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3391-Fluid Mechanics and Machinery Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3391-Fluid Mechanics and Machinery Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3391-Fluid Mechanics and Machinery Question Papers/PYQ/CE3391 Fluid Mechanics and Machinery Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3391-Fluid Mechanics and Machinery Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3391-Fluid Mechanics and Machinery Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CE3391-Fluid Mechanics and Machinery Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CS3301-Data Structures Question Papers/Lecture Notes/CS3301 Data Structures Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CS3301-Data Structures Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CS3301-Data Structures Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CS3301-Data Structures Question Papers/PYQ/CS3301 Data Structures Question Bank.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CS3301-Data Structures Question Papers/PYQ/CS3301 Data Structures Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CS3301-Data Structures Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CS3301-Data Structures Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CS3301-Data Structures Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CS3351-Digital Principles and Computer Organization Question Papers/Lecture Notes/CS3351 Digital Principles and Computer Organization Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CS3351-Digital Principles and Computer Organization Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CS3351-Digital Principles and Computer Organization Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CS3351-Digital Principles and Computer Organization Question Papers/PYQ/CS3351 Digital Principles and Computer Organization Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CS3351-Digital Principles and Computer Organization Question Papers/PYQ/CS3351 Digital Principles and Computer Organization Two Mark Questions.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CS3351-Digital Principles and Computer Organization Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CS3351-Digital Principles and Computer Organization Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CS3351-Digital Principles and Computer Organization Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
Labels: enhancement, Advanced, SSOC S4

#268 Added the files
  MAKAUT/4th Sem/btech-4-sem-biology-bs-b401-2024.pdf
  MAKAUT/4th Sem/btech-4-sem-environmental-sciences-mc-401-2024.pdf
  MAKAUT/4th Sem/btech-cse-4-sem-advanced-computer-architecture-2013.pdf
  MAKAUT/4th Sem/btech-cse-4-sem-communication-engineering-and-coding-theory-2015.pdf
  MAKAUT/4th Sem/btech-cse-4-sem-communication-engineering-and-coding-theory-2017.pdf
  MAKAUT/4th Sem/btech-cse-4-sem-computer-architecture-2014.pdf
  MAKAUT/4th Sem/btech-cse-4-sem-computer-architecture-2016.pdf
  MAKAUT/4th Sem/btech-cse-4-sem-computer-architecture-2017.pdf
  MAKAUT/4th Sem/btech-cse-4-sem-discrete-mathematics-pcc-cs401-2025.pdf
  MAKAUT/4th Sem/btech-cse-4-sem-formal-language-and-automata-theory-2015.pdf
  MAKAUT/4th Sem/btech-cse-4-sem-formal-language-and-automata-theory-2017.pdf
  MAKAUT/4th Sem/btech-cse-4-sem-formal-language-and-automata-theory-pcc-cs-403-2023 (1).pdf
  MAKAUT/4th Sem/btech-cse-4-sem-formal-language-and-automata-theory-pcc-cs-403-2023.pdf
  MAKAUT/4th Sem/btech-cse-4-sem-numerical-methods-2014.pdf
  MAKAUT/4th Sem/btech-cse-4-sem-numerical-methods-2016.pdf
  MAKAUT/4th Sem/btech-es-4-sem-design-and-analysis-of-algorithms-es-cs401-2023 1.pdf
  MAKAUT/4th Sem/btech-es-4-sem-design-and-analysis-of-algorithms-es-cs401-2023.pdf
  MAKAUT/4th Sem/btech-es-cs-pcc-4-sem-design-and-analysis-of-algorithms-es-cs401-2024.pdf
  MAKAUT/4th Sem/btech-pcc-cs-4-sem-computer-architecture-pcc-cs402-2024.pdf
  MAKAUT/4th Sem/btech-pcc-cs-4-sem-discrete-mathematics-pcc-cs401-2024.pdf
  MAKAUT/4th Sem/btech-pcc-cs-4-sem-formal-language-and-automata-theory-pcc-cs-403-2024.pdf
  MAKAUT/4th Sem/btech-pcc-csd-4-sem-object-oriented-programming-and-design-pcc-csd-403-2023.pdf
  MAKAUT/4th Sem/btech-pcc-cse-4-sem-computer-architecture-pcc-cs402-2023.pdf
  MAKAUT/4th Sem/btech-pcc-cse-4-sem-discrete-mathematics-pcc-cs401-2023.pdf
  MAKAUT/4th Sem/btech-pcc-cse-4-sem-formal-language-and-automata-pcc-cse-403-2023.pdf
Labels: enhancement, Intermediate, SSOC S4

#273 Added PYQs for IT 5th,6th,7th,8th Sem of HITK
  Heritage Institute of Technology, Kolkata/02. Information Technology/5th Sem/Distributed Database Management Systems (INF3132)/INFO 3132-5th Sem 2020.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/5th Sem/Distributed Database Management Systems (INF3132)/INFO 3132-5th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/5th Sem/Distributed Database Management Systems (INF3132)/INFO 3132-5th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/6th Sem/Cryptography and Network Security (INF3202)/INFO 3201- 6th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/6th Sem/Cryptography and Network Security (INF3202)/INFO 3233- 6th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/6th Sem/Cryptography and Network Security (INF3202)/INFO 3233- 6th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/6th Sem/Cryptography and Network Security (INF3202)/INFO 4243- 8th Sem 2018.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/6th Sem/Cryptography and Network Security (INF3202)/INFO 4243- 8th Sem 2019.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/6th Sem/Cryptography and Network Security (INF3202)/INFO 4243- 8th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/6th Sem/Cryptography and Network Security (INF3202)/INFO 4243- 8th Sem(Special Supple) 2018.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/6th Sem/E-Commerce and ERP (INFO3232)/INFO 3231- 6th Sem 2018.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/6th Sem/E-Commerce and ERP (INFO3232)/INFO 3231- 6th Sem(Backlog)  2021.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/6th Sem/E-Commerce and ERP (INFO3232)/INFO 3232- 6th Sem 2019.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/6th Sem/E-Commerce and ERP (INFO3232)/INFO 3232- 6th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/6th Sem/E-Commerce and ERP (INFO3232)/INFO 3232- 6th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/6th Sem/E-Commerce and ERP (INFO3232)/INFO 3232- 6th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/7th Sem/Introduction to IOT (INF4131)/INFO 4131- 7th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/8th Sem/Cloud Computing (INFO4242)/INFO 4242- 8th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/8th Sem/Cloud Computing (INFO4242)/INFO 4242- 8th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/8th Sem/Cloud Computing (INFO4242)/INFO 4242- 8th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/8th Sem/Computational Biology (BIOT4221)/BIOT 4221- 8th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/8th Sem/Computational Biology (BIOT4221)/BIOT 4281- 8th Sem 2018.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/8th Sem/Computational Biology (BIOT4221)/BIOT 4281- 8th Sem 2019.pdf
  Heritage Institute of Technology, Kolkata/02. Information Technology/8th Sem/Computational Biology (BIOT4221)/BIOT 4281- 8th Sem 2021.pdf
Labels: enhancement, Advanced, SSOC S4

#274 Added PYQs for Digital Forensics (CSE4004) and Human Computer Interaction (CSE4015) #269
  VIT Bhopal University/01. Computer Engineering/Digital Forensics(CSE4004)/digital forensics(may 2019)(CSE4004) (2).pdf
  VIT Bhopal University/01. Computer Engineering/Digital Forensics(CSE4004)/digital forensics(may 2019)(CSE4004) (3).pdf
  VIT Bhopal University/01. Computer Engineering/Digital Forensics(CSE4004)/digital forensics(may 2019)(CSE4004).pdf
  VIT Bhopal University/01. Computer Engineering/Human Computer Interaction(CSE4015)/Human Computer Interaction(may 2019)(CSE4015).pdf
  VIT Bhopal University/01. Computer Engineering/Human Computer Interaction(CSE4015)/Human Computer Interaction(may 2020)(CSE4015) (2).pdf
  VIT Bhopal University/01. Computer Engineering/Human Computer Interaction(CSE4015)/Human Computer Interaction(may 2020)(CSE4015) (3).pdf
  VIT Bhopal University/01. Computer Engineering/Human Computer Interaction(CSE4015)/Human Computer Interaction(may 2020)(CSE4015) (4).pdf
  VIT Bhopal University/01. Computer Engineering/Human Computer Interaction(CSE4015)/Human Computer Interaction(may 2020)(CSE4015) (5).pdf
  VIT Bhopal University/01. Computer Engineering/Human Computer Interaction(CSE4015)/Human Computer Interaction(may 2020)(CSE4015) (6).pdf
  VIT Bhopal University/01. Computer Engineering/Human Computer Interaction(CSE4015)/Human Computer Interaction(may 2020)(CSE4015).pdf
  VIT Bhopal University/01. Computer Engineering/Internet and Web Programming(CSE3002 )/Internet and Web Programming(dec 2020)CSE3002 (2).pdf
  VIT Bhopal University/01. Computer Engineering/Internet and Web Programming(CSE3002 )/Internet and Web Programming(dec 2020)CSE3002 (3).pdf
  VIT Bhopal University/01. Computer Engineering/Internet and Web Programming(CSE3002 )/Internet and Web Programming(dec 2020)CSE3002 (4).pdf
  VIT Bhopal University/01. Computer Engineering/Internet and Web Programming(CSE3002 )/Internet and Web Programming(dec 2020)CSE3002 (5).pdf
  VIT Bhopal University/01. Computer Engineering/Internet and Web Programming(CSE3002 )/Internet and Web Programming(dec 2020)CSE3002 (6).pdf
  VIT Bhopal University/01. Computer Engineering/Internet and Web Programming(CSE3002 )/Internet and Web Programming(dec 2020)CSE3002.pdf
  VIT Bhopal University/01. Computer Engineering/Software Engineering(CES3001)/SOFTWARE ENGINEERING (dec 2020)(CES3001) (10).pdf
  VIT Bhopal University/01. Computer Engineering/Software Engineering(CES3001)/SOFTWARE ENGINEERING (dec 2020)(CES3001) (11).pdf
  VIT Bhopal University/01. Computer Engineering/Software Engineering(CES3001)/SOFTWARE ENGINEERING (dec 2020)(CES3001) (2).pdf
  VIT Bhopal University/01. Computer Engineering/Software Engineering(CES3001)/SOFTWARE ENGINEERING (dec 2020)(CES3001) (3).pdf
  VIT Bhopal University/01. Computer Engineering/Software Engineering(CES3001)/SOFTWARE ENGINEERING (dec 2020)(CES3001) (4).pdf
  VIT Bhopal University/01. Computer Engineering/Software Engineering(CES3001)/SOFTWARE ENGINEERING (dec 2020)(CES3001) (5).pdf
  VIT Bhopal University/01. Computer Engineering/Software Engineering(CES3001)/SOFTWARE ENGINEERING (dec 2020)(CES3001) (6).pdf
  VIT Bhopal University/01. Computer Engineering/Software Engineering(CES3001)/SOFTWARE ENGINEERING (dec 2020)(CES3001) (7).pdf
  VIT Bhopal University/01. Computer Engineering/Software Engineering(CES3001)/SOFTWARE ENGINEERING (dec 2020)(CES3001) (8).pdf
  VIT Bhopal University/01. Computer Engineering/Software Engineering(CES3001)/SOFTWARE ENGINEERING (dec 2020)(CES3001) (9).pdf
  VIT Bhopal University/01. Computer Engineering/Software Engineering(CES3001)/SOFTWARE ENGINEERING (dec 2020)(CES3001).pdf
Labels: enhancement, Intermediate, SSOC S4

#278 Updated README.md for VIT Bhopal – Computer Engineering Section #276
  VIT Bhopal University/01. Computer Engineering/README.md
Labels: enhancement, Intermediate, SSOC S4

#281 Added pyq of 6th sem
  MAKAUT/6th Sem/btech-cse-6-sem-computer-graphics-2014.pdf
  MAKAUT/6th Sem/btech-cse-6-sem-computer-graphics-2016.pdf
  MAKAUT/6th Sem/btech-cse-6-sem-computer-network-2016.pdf
  MAKAUT/6th Sem/btech-cse-6-sem-computer-networks-2017.pdf
  MAKAUT/6th Sem/btech-cse-6-sem-database-management-systems-pcc-cs601-2024.pdf
  MAKAUT/6th Sem/btech-cse-6-sem-database-management-systems-pcc-cs601-2025.pdf
  MAKAUT/6th Sem/btech-cse-6-sem-erp-2018.pdf
  MAKAUT/6th Sem/btech-cse-6-sem-erp-2019.pdf
  MAKAUT/6th Sem/btech-cse-6-sem-multimedia-technology-2016.pdf
  MAKAUT/6th Sem/btech-cse-6-sem-operating-system-2017.pdf
  MAKAUT/6th Sem/btech-cse-6-sem-operating-system-2019.pdf
  MAKAUT/6th Sem/btech-cse-6-sem-operations-research-2015.pdf
  MAKAUT/6th Sem/btech-cse-6-sem-software-engineering-2015.pdf
  MAKAUT/6th Sem/btech-cse-it-6-sem-advanced-algorithms-pec-it-601a-2024.pdf
  MAKAUT/6th Sem/btech-cse-it-6-sem-data-warehousing-and-data-mining-pec-it602b-2024.pdf
  MAKAUT/6th Sem/btech-cse-it-6-sem-distributed-systems-pec-it601b-2024.pdf
  MAKAUT/6th Sem/btech-cse-it-6-sem-distributed-systems-pec-it601b-2025.pdf
  MAKAUT/6th Sem/btech-cse-it-6-sem-human-resource-development-and-organizational-behaviour-oec-it-601b-2024.pdf
  MAKAUT/6th Sem/btech-cse-it-6-sem-image-processing-pec-it601d-2024.pdf
  MAKAUT/6th Sem/btech-cse-it-6-sem-numerical-methods-oec-it-601a-2024.pdf
  MAKAUT/6th Sem/btech-ec-cse-6-sem-computer-networks-ec602-2024.pdf
  MAKAUT/6th Sem/btech-ec-cse-6-sem-computer-networks-ec602-2025.pdf
  MAKAUT/6th Sem/btech-hm-hu-6-sem-operations-research-hm-hu601-2023.pdf
Labels: enhancement, Intermediate, SSOC S4

#290 Added PYQs for Core ECE Subjects – VIT Bhopal University (Electronics & Communication Engineering) issue #288
  VIT Bhopal University/02. Electronics & Communication Engineering/Digital Communication Systems(ECE4001)/Digital Communication Systems(Dec 2019)(ECE4001) (2)..pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/Digital Communication Systems(ECE4001)/Digital Communication Systems(Dec 2019)(ECE4001) (2).pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/Digital Communication Systems(ECE4001)/Digital Communication Systems(Dec 2019)(ECE4001) (3)..pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/Digital Communication Systems(ECE4001)/Digital Communication Systems(Dec 2019)(ECE4001)..pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/Digital Communication Systems(ECE4001)/Digital Communication Systems(Dec 2019)(ECE4001).pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/Digital Signal Processing(ECE2006)/Digital Signal Processing(ECE2006) (5).pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/Digital Signal Processing(ECE2006)/Digital Signal Processing(ECE2006) (6).pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/Digital Signal Processing(ECE2006)/Digital Signal Processing(ECE2006) (7).pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/Digital Signal Processing(ECE2006)/Digital Signal Processing(ECE2006) (8).pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/Embedded Systems (ECE3031)/Embedded Systems (Dec 2020)(ECE3031) (2).pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/Embedded Systems (ECE3031)/Embedded Systems (Dec 2020)(ECE3031) (3).pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/Embedded Systems (ECE3031)/Embedded Systems (Dec 2020)(ECE3031).pdf
Labels: enhancement, Advanced, SSOC S4

#294 Add the pyq of 4th sem of IT
  MAKAUT/3rd Sem/ECE/btech-ec-301-circuit-theory-and-networks-2017.pdf MAKAUT Question Paper and solutions MAKAUT, Maulana Abul Kalam Azad University of Technology, West Bengal pdf makaut.com
  MAKAUT/3rd Sem/ECE/btech-ec-ei-302-analog-electronic-circuit-2019.pdf MAKAUT Question Paper and solutions MAKAUT, Maulana Abul Kalam Azad University of Technology, West Bengal pdf makaut.com
  MAKAUT/4th Sem/C.S.E/btech-4-sem-biology-bs-b401-2024.pdf
  MAKAUT/4th Sem/C.S.E/btech-4-sem-environmental-sciences-mc-401-2024.pdf
  MAKAUT/4th Sem/C.S.E/btech-cse-4-sem-advanced-computer-architecture-2013.pdf
  MAKAUT/4th Sem/C.S.E/btech-cse-4-sem-communication-engineering-and-coding-theory-2015.pdf
  MAKAUT/4th Sem/C.S.E/btech-cse-4-sem-communication-engineering-and-coding-theory-2017.pdf
  MAKAUT/4th Sem/C.S.E/btech-cse-4-sem-computer-architecture-2014.pdf
  MAKAUT/4th Sem/C.S.E/btech-cse-4-sem-computer-architecture-2016.pdf
  MAKAUT/4th Sem/C.S.E/btech-cse-4-sem-computer-architecture-2017.pdf
  MAKAUT/4th Sem/C.S.E/btech-cse-4-sem-discrete-mathematics-pcc-cs401-2025.pdf
  MAKAUT/4th Sem/C.S.E/btech-cse-4-sem-formal-language-and-automata-theory-2015.pdf
  MAKAUT/4th Sem/C.S.E/btech-cse-4-sem-formal-language-and-automata-theory-2017.pdf
  MAKAUT/4th Sem/C.S.E/btech-cse-4-sem-formal-language-and-automata-theory-pcc-cs-403-2023 (1).pdf
  MAKAUT/4th Sem/C.S.E/btech-cse-4-sem-formal-language-and-automata-theory-pcc-cs-403-2023.pdf
  MAKAUT/4th Sem/C.S.E/btech-cse-4-sem-numerical-methods-2014.pdf
  MAKAUT/4th Sem/C.S.E/btech-cse-4-sem-numerical-methods-2016.pdf
  MAKAUT/4th Sem/C.S.E/btech-es-4-sem-design-and-analysis-of-algorithms-es-cs401-2023 1.pdf
  MAKAUT/4th Sem/C.S.E/btech-es-4-sem-design-and-analysis-of-algorithms-es-cs401-2023.pdf
  MAKAUT/4th Sem/C.S.E/btech-es-cs-pcc-4-sem-design-and-analysis-of-algorithms-es-cs401-2024.pdf
  MAKAUT/4th Sem/C.S.E/btech-pcc-cs-4-sem-computer-architecture-pcc-cs402-2024.pdf
  MAKAUT/4th Sem/C.S.E/btech-pcc-cs-4-sem-discrete-mathematics-pcc-cs401-2024.pdf
  MAKAUT/4th Sem/C.S.E/btech-pcc-cs-4-sem-formal-language-and-automata-theory-pcc-cs-403-2024.pdf
  MAKAUT/4th Sem/C.S.E/btech-pcc-csd-4-sem-object-oriented-programming-and-design-pcc-csd-403-2023.pdf
  MAKAUT/4th Sem/C.S.E/btech-pcc-cse-4-sem-computer-architecture-pcc-cs402-2023.pdf
  MAKAUT/4th Sem/C.S.E/btech-pcc-cse-4-sem-discrete-mathematics-pcc-cs401-2023.pdf
  MAKAUT/4th Sem/C.S.E/btech-pcc-cse-4-sem-formal-language-and-automata-pcc-cse-403-2023.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-analysis-and-design-of-information-system-2009.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-analysis-and-design-of-information-system-2012.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-analysis-and-design-of-information-system-2013.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-communication-engineering-and-coding-theory-2013.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-computer-organization-and-architecture-2012.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-computer-organization-and-architecture-2013.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-control-system-2012.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-control-systems-2010.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-control-systems-2013.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-formal-language-and-automata-theory-2013.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-mathematics-2009.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-mathematics-2010.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-mathematics-2013.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-mathematics-3-2013.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-numerical-methods-2012.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-numerical-methods-2013.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-object-oriented-programming-and-uml-2013.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-object-oriented-programming-and-uml-2015.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-object-oriented-programming-and-uml-2016.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-principle-of-communication-engineering-2013.pdf
  MAKAUT/4th Sem/I.T/btech-it-4-sem-principles-of-communication-engg.-2009.pdf
Labels: enhancement, Advanced, SSOC S4

#297 Added the pyq question of ECE department of 3rd semester
  MAKAUT/3rd Sem/C.S.E/btech-3-sem-mathematics-3-bs-m301-2025.pdf
  MAKAUT/3rd Sem/C.S.E/btech-cse-3-sem-analog-and-digital-electronics-esc-301-2024.pdf
  MAKAUT/3rd Sem/C.S.E/btech-cse-3-sem-analog-and-digital-electronics-esc-301-2025.pdf
  MAKAUT/3rd Sem/C.S.E/btech-cse-3-sem-computer-organisation-pc-ecs302-2025.pdf
  MAKAUT/3rd Sem/C.S.E/btech-cse-3-sem-computer-organisation-pcc-cs302-2023.pdf
  MAKAUT/3rd Sem/C.S.E/btech-cse-3-sem-computer-organisation-pcc-cs302-2024.pdf
  MAKAUT/3rd Sem/C.S.E/btech-cse-3-sem-data-structure-and-algorithms-pcc-cs301-2024.pdf
  MAKAUT/3rd Sem/C.S.E/btech-cse-3-sem-data-structure-and-algorithms-pcc-csbs301-2023.pdf
  MAKAUT/3rd Sem/C.S.E/btech-cse-3-sem-economics-for-engineers-humanities-2-hm-hu301-2025.pdf
  MAKAUT/3rd Sem/C.S.E/btech-cse-3-sem-economics-for-engineers-humanities-2-hsmc-301-2024.pdf
  MAKAUT/3rd Sem/C.S.E/btech-cse-3-sem-linear-algebra-bscaids301-2025.pdf
  MAKAUT/3rd Sem/C.S.E/btech-cse-3-sem-mathematics-3-differential-calculus-bsc-301-2024.pdf
  MAKAUT/3rd Sem/C.S.E/btech-cse-3-sem-mathematics-3-differential-calculus-bsc301-2023.pdf
  MAKAUT/3rd Sem/ECE/btech-ec-3-sem-digital-system-design-ec302-2023.pdf
  MAKAUT/3rd Sem/ECE/btech-ec-3-sem-digital-system-design-ec302-2024.pdf
  MAKAUT/3rd Sem/ECE/btech-ec-3-sem-digital-system-design-ec302-2025.pdf
  MAKAUT/3rd Sem/ECE/btech-ec-3-sem-electronic-devices-ec301-2023.pdf
  MAKAUT/3rd Sem/ECE/btech-ec-3-sem-electronic-devices-ec301-2025.pdf
  MAKAUT/3rd Sem/ECE/btech-ec-3-sem-network-theory-ec304-2025.pdf
  MAKAUT/3rd Sem/ECE/btech-ec-3-sem-signals-and-systems-ec303-2024.pdf
  MAKAUT/3rd Sem/ECE/btech-ec-3-sem-signals-and-systems-ec303-2025.pdf
  MAKAUT/3rd Sem/ECE/btech-ec-301-circuit-theory-and-networks-2012.pdf
  MAKAUT/3rd Sem/ECE/btech-ec-301-circuit-theory-and-networks-2017.pdf
  MAKAUT/3rd Sem/ECE/btech-ec-301-digital-electronics-circuits-2012.pdf
  MAKAUT/3rd Sem/ECE/btech-ec-302-solid-state-devices-2018.pdf
  MAKAUT/3rd Sem/ECE/btech-ec-303-signals-and-systems-2016.pdf
  MAKAUT/3rd Sem/ECE/btech-ec-304-analog-electronics-circuits-2014.pdf
  MAKAUT/3rd Sem/ECE/btech-ec-304-analog-electronics-circuits-2015.pdf
  MAKAUT/3rd Sem/ECE/btech-ec-ee-301-digital-electronic-circuits-2019.pdf
  MAKAUT/3rd Sem/ECE/btech-ec-ei-302-analog-electronic-circuit-2019.pdf
  MAKAUT/3rd Sem/ECE/btech-ece-3-sem-circuit-theory-and-networks-2012.pdf
  MAKAUT/3rd Sem/ECE/btech-ece-3-sem-data-structure-and-algorithms-2011.pdf
  MAKAUT/3rd Sem/ECE/btech-ece-3-sem-data-structure-and-algorithms-2011h.pdf
  MAKAUT/3rd Sem/ECE/btech-ece-3-sem-electronic-measurement-and-instrumentation-2012.pdf
Labels: enhancement, Intermediate, SSOC S4

#300 Added PYQs for Core Mechanical Engineering Subjects – Issue #296
  VIT Bhopal University/03.Mechanical Engineering (ME)/Engineering Mechanics(MEE1001 )/Engineering Mechanics(Dec 2020)(MEE1001 ) (10).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Engineering Mechanics(MEE1001 )/Engineering Mechanics(Dec 2020)(MEE1001 ) (11).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Engineering Mechanics(MEE1001 )/Engineering Mechanics(Dec 2020)(MEE1001 ) (2).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Engineering Mechanics(MEE1001 )/Engineering Mechanics(Dec 2020)(MEE1001 ) (3).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Engineering Mechanics(MEE1001 )/Engineering Mechanics(Dec 2020)(MEE1001 ) (4).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Engineering Mechanics(MEE1001 )/Engineering Mechanics(Dec 2020)(MEE1001 ) (5).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Engineering Mechanics(MEE1001 )/Engineering Mechanics(Dec 2020)(MEE1001 ) (6).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Engineering Mechanics(MEE1001 )/Engineering Mechanics(Dec 2020)(MEE1001 ) (7).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Engineering Mechanics(MEE1001 )/Engineering Mechanics(Dec 2020)(MEE1001 ) (8).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Engineering Mechanics(MEE1001 )/Engineering Mechanics(Dec 2020)(MEE1001 ) (9).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Engineering Mechanics(MEE1001 )/Engineering Mechanics(Dec 2020)(MEE1001 ).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Engineering Mechanics(MEE1001 )/README.md
  VIT Bhopal University/03.Mechanical Engineering (ME)/Ergonomics & Styling(MEE2043)/Ergonomics & Styling(MEE1042).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Ergonomics & Styling(MEE2043)/README.md
  VIT Bhopal University/03.Mechanical Engineering (ME)/Fluid Mechanics(MEE1004)/Fluid Mechanics(June 2020)(MEE1004) (2).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Fluid Mechanics(MEE1004)/Fluid Mechanics(June 2020)(MEE1004) (3).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Fluid Mechanics(MEE1004)/Fluid Mechanics(June 2020)(MEE1004) (4).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Fluid Mechanics(MEE1004)/Fluid Mechanics(June 2020)(MEE1004) (5).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Fluid Mechanics(MEE1004)/Fluid Mechanics(June 2020)(MEE1004) (6).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Fluid Mechanics(MEE1004)/Fluid Mechanics(June 2020)(MEE1004) (7).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Fluid Mechanics(MEE1004)/Fluid Mechanics(June 2020)(MEE1004) (8).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Fluid Mechanics(MEE1004)/Fluid Mechanics(June 2020)(MEE1004) (9).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Fluid Mechanics(MEE1004)/Fluid Mechanics(June 2020)(MEE1004).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Fluid Mechanics(MEE1004)/README.md
  VIT Bhopal University/03.Mechanical Engineering (ME)/README.md
Labels: enhancement, Intermediate, SSOC S4

#303 Added PYQs for Core Mechanical Engineering Subjects – Issue #302
  VIT Bhopal University/03.Mechanical Engineering (ME)/Heat Transfer (MEE2005)/Heat Transfer(Dec 2020) (MEE2005) (10).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Heat Transfer (MEE2005)/Heat Transfer(Dec 2020) (MEE2005) (11).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Heat Transfer (MEE2005)/Heat Transfer(Dec 2020) (MEE2005) (12).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Heat Transfer (MEE2005)/Heat Transfer(Dec 2020) (MEE2005) (13).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Heat Transfer (MEE2005)/Heat Transfer(Dec 2020) (MEE2005) (14).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Heat Transfer (MEE2005)/Heat Transfer(Dec 2020) (MEE2005) (15).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Heat Transfer (MEE2005)/Heat Transfer(Dec 2020) (MEE2005) (2).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Heat Transfer (MEE2005)/Heat Transfer(Dec 2020) (MEE2005) (3).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Heat Transfer (MEE2005)/Heat Transfer(Dec 2020) (MEE2005) (4).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Heat Transfer (MEE2005)/Heat Transfer(Dec 2020) (MEE2005) (5).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Heat Transfer (MEE2005)/Heat Transfer(Dec 2020) (MEE2005) (6).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Heat Transfer (MEE2005)/Heat Transfer(Dec 2020) (MEE2005) (7).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Heat Transfer (MEE2005)/Heat Transfer(Dec 2020) (MEE2005) (8).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Heat Transfer (MEE2005)/Heat Transfer(Dec 2020) (MEE2005) (9).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Heat Transfer (MEE2005)/Heat Transfer(Dec 2020) (MEE2005).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Heat Transfer (MEE2005)/README.md
  VIT Bhopal University/03.Mechanical Engineering (ME)/Machining Processes and Metrology (MEE2006 )/Machining Processes and Metrology (MEE2006 ) (2).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Machining Processes and Metrology (MEE2006 )/Machining Processes and Metrology (MEE2006 ).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Machining Processes and Metrology (MEE2006 )/README.md
  VIT Bhopal University/03.Mechanical Engineering (ME)/Manufacturing Processes(MEE1007)/Manufacturing Processes(MEE1007) (2).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Manufacturing Processes(MEE1007)/Manufacturing Processes(MEE1007) (3).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Manufacturing Processes(MEE1007)/Manufacturing Processes(MEE1007) (4).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Manufacturing Processes(MEE1007)/Manufacturing Processes(MEE1007) (5).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Manufacturing Processes(MEE1007)/Manufacturing Processes(MEE1007) (6).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Manufacturing Processes(MEE1007)/Manufacturing Processes(MEE1007) (7).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Manufacturing Processes(MEE1007)/Manufacturing Processes(MEE1007).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Manufacturing Processes(MEE1007)/README.md
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanical Operations(CHE1022)/Mechanical Operations(CHE1022) (2).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanical Operations(CHE1022)/Mechanical Operations(CHE1022) (3).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanical Operations(CHE1022)/Mechanical Operations(CHE1022).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanical Operations(CHE1022)/README.md
Labels: enhancement, Advanced, SSOC S4

#304 Added PYQs for Information Technology 3rd Sem,4th Sem COA(ITPC 203),DAA(ITPC 201),SE(ITPC 207),CN(ITPC 202),OS(ITPC 200)
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/CS3351-Digital Principles and Computer Organization Question Papers/Lecture Notes/CS3351 Digital Principles and Computer Organization Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/MA3351-Transforms and Partial Differential Equations Question Papers/Lecture Notes/MA3351 Transforms and Partial Differential Equations Lecture Notes.pdf
  NIT_Kurukshetra/Information Technology/3rd Sem/Computer Organization and Architecture(ITPC 203)/ITPC29 ES 2018.pdf
  NIT_Kurukshetra/Information Technology/3rd Sem/Computer Organization and Architecture(ITPC 203)/ITPC29 ES 2019.pdf
  NIT_Kurukshetra/Information Technology/3rd Sem/Computer Organization and Architecture(ITPC 203)/ITPC29 ES 2020.pdf
  NIT_Kurukshetra/Information Technology/3rd Sem/Computer Organization and Architecture(ITPC 203)/ITPC29 ES 2021.pdf
  NIT_Kurukshetra/Information Technology/3rd Sem/Design And Analysis of Algorithms(ITPC 201)/ITPC21 ES 2018.pdf
  NIT_Kurukshetra/Information Technology/3rd Sem/Design And Analysis of Algorithms(ITPC 201)/ITPC21 ES 2019.pdf
  NIT_Kurukshetra/Information Technology/3rd Sem/Design And Analysis of Algorithms(ITPC 201)/ITPC21 ES 2020.pdf
  NIT_Kurukshetra/Information Technology/3rd Sem/Design And Analysis of Algorithms(ITPC 201)/ITPC21 ES 2021.pdf
  NIT_Kurukshetra/Information Technology/3rd Sem/Software Engineering(ITPC 207)/ITPC27 ES 2018.pdf
  NIT_Kurukshetra/Information Technology/3rd Sem/Software Engineering(ITPC 207)/ITPC27 ES 2019.pdf
  NIT_Kurukshetra/Information Technology/3rd Sem/Software Engineering(ITPC 207)/ITPC27 ES 2020.pdf
  NIT_Kurukshetra/Information Technology/3rd Sem/Software Engineering(ITPC 207)/ITPC27 ES 2021.pdf
  NIT_Kurukshetra/Information Technology/3rd Sem/Software Engineering(ITPC 207)/ITPC27 MS 2020.pdf
  NIT_Kurukshetra/Information Technology/4th Sem/Computer Networks(ITPC 202)/ITPC26 ES 2019.pdf
  NIT_Kurukshetra/Information Technology/4th Sem/Computer Networks(ITPC 202)/ITPC26 ES 2025.pdf
  NIT_Kurukshetra/Information Technology/4th Sem/Computer Networks(ITPC 202)/ITPC26 ES1 2019.pdf
  NIT_Kurukshetra/Information Technology/4th Sem/Computer Networks(ITPC 202)/ITPC26 MS1 2025.pdf
  NIT_Kurukshetra/Information Technology/4th Sem/Operating Systems(ITPC 200)/ITPC20 ES 2018.pdf
  NIT_Kurukshetra/Information Technology/4th Sem/Operating Systems(ITPC 200)/ITPC20 ES 2019.pdf
  NIT_Kurukshetra/Information Technology/4th Sem/Operating Systems(ITPC 200)/ITPC20 ES 2021.pdf
  NIT_Kurukshetra/Information Technology/4th Sem/Operating Systems(ITPC 200)/ITPC20 MS 2021.pdf
Labels: enhancement, Intermediate, SSOC S4

#307 Added PYQs for Core Mechanical Engineering Subjects – Issue #305
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanics of machines(MEE2004 )/README.md
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanics of machines(MEE2004 )/mechanics of machines(dec 2020)(MEE2004 ) (2).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanics of machines(MEE2004 )/mechanics of machines(dec 2020)(MEE2004 ) (3).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanics of machines(MEE2004 )/mechanics of machines(dec 2020)(MEE2004 ) (4).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanics of machines(MEE2004 )/mechanics of machines(dec 2020)(MEE2004 ) (5).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanics of machines(MEE2004 )/mechanics of machines(dec 2020)(MEE2004 ) (6).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanics of machines(MEE2004 )/mechanics of machines(dec 2020)(MEE2004 ) (7).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanics of machines(MEE2004 )/mechanics of machines(dec 2020)(MEE2004 ) (8).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanics of machines(MEE2004 )/mechanics of machines(dec 2020)(MEE2004 ).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanics of solids(MEE1032 )/Mechanics of solids(Dec 2019)(MEE1032 ) (2).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanics of solids(MEE1032 )/Mechanics of solids(Dec 2019)(MEE1032 ) (3).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanics of solids(MEE1032 )/Mechanics of solids(Dec 2019)(MEE1032 ) (4).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanics of solids(MEE1032 )/Mechanics of solids(Dec 2019)(MEE1032 ) (5).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanics of solids(MEE1032 )/Mechanics of solids(Dec 2019)(MEE1032 ) (6).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanics of solids(MEE1032 )/Mechanics of solids(Dec 2019)(MEE1032 ) (7).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanics of solids(MEE1032 )/Mechanics of solids(Dec 2019)(MEE1032 ) (8).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanics of solids(MEE1032 )/Mechanics of solids(Dec 2019)(MEE1032 ) (9).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanics of solids(MEE1032 )/Mechanics of solids(Dec 2019)(MEE1032 ).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Mechanics of solids(MEE1032 )/README.md
  VIT Bhopal University/03.Mechanical Engineering (ME)/Momentum Transfer(CHE1001)/Momentum Transfer(dec 2019)(CHE1001) (2).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Momentum Transfer(CHE1001)/Momentum Transfer(dec 2019)(CHE1001) (3).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Momentum Transfer(CHE1001)/Momentum Transfer(dec 2019)(CHE1001) (4).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Momentum Transfer(CHE1001)/Momentum Transfer(dec 2019)(CHE1001) (5).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Momentum Transfer(CHE1001)/Momentum Transfer(dec 2019)(CHE1001) (6).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Momentum Transfer(CHE1001)/Momentum Transfer(dec 2019)(CHE1001).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Momentum Transfer(CHE1001)/README.md
Labels: enhancement, Advanced, SSOC S4

#310 Added PYQ for 3,4 semeseter - Anna University
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3351-Engineering Mechanics Question Papers/Lecture Notes/ME3351 Engineering Mechanics Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3351-Engineering Mechanics Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3351-Engineering Mechanics Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3351-Engineering Mechanics Question Papers/PYQ/ME3351 Engineering Mechanics Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3351-Engineering Mechanics Question Papers/PYQ/ME3351 Engineering Mechanics Two Mark Questions.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3351-Engineering Mechanics Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3351-Engineering Mechanics Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3351-Engineering Mechanics Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3391-Engineering Thermodynamics Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3391-Engineering Thermodynamics Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3391-Engineering Thermodynamics Question Papers/PYQ/ME3391 Engineering Thermodynamics Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3391-Engineering Thermodynamics Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3391-Engineering Thermodynamics Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3391-Engineering Thermodynamics Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3392-Engineering Materials and Metallurgy Question Papers/Lecture Notes/ME3392 Engineering Materials and Metallurgy Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3392-Engineering Materials and Metallurgy Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3392-Engineering Materials and Metallurgy Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3392-Engineering Materials and Metallurgy Question Papers/PYQ/ME3392 Engineering Materials and Metallurgy Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3392-Engineering Materials and Metallurgy Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3392-Engineering Materials and Metallurgy Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3392-Engineering Materials and Metallurgy Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3393-Manufacturing Processes Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3393-Manufacturing Processes Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3393-Manufacturing Processes Question Papers/PYQ/ME3393 Manufacturing Processes Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3393-Manufacturing Processes Question Papers/PYQ/ME3393 Manufacturing Processes Two Mark Questions.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3393-Manufacturing Processes Question Papers/PYQ/Nov Dec 2022 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3393-Manufacturing Processes Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 1/ME3393-Manufacturing Processes Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/AD3491-Fundamentals of Data Science and Analytics Question Papers/Lecture Notes/AD3491 Fundamentals of Data Science and Analytics Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/AD3491-Fundamentals of Data Science and Analytics Question Papers/PYQ/AD3491 Fundamentals of Data Science and Analytics Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/AD3491-Fundamentals of Data Science and Analytics Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/AD3491-Fundamentals of Data Science and Analytics Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/AE3491-Mechanics of Machines Question Papers/PYQ/AE3491 Mechanics of Machines Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/AE3491-Mechanics of Machines Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/AE3491-Mechanics of Machines Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/AE3491-Mechanics of Machines Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/AL3451-Machine Learning Question Papers/Lecture Notes/AL3451 Machine Learning Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/AL3451-Machine Learning Question Papers/PYQ/AL3451 Machine Learning Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/AL3451-Machine Learning Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/AL3451-Machine Learning Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/AL3451-Machine Learning Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/AL3452-Operating Systems Question Papers/Lecture Notes/AL3452 Operating Systems Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/AL3452-Operating Systems Question Papers/PYQ/AL3452 Operating Systems Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/AL3452-Operating Systems Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/AL3452-Operating Systems Question Papers/PYQ/Apr May 2024 Question Paper.pdf
Labels: enhancement, Advanced, SSOC S4

#311 Added the pyq of civil department of 2nd semester
  MAKAUT/2nd Sem/C.E./btech-2-sem-basic-electrical-engineering-es-ee101-2024.pdf
  MAKAUT/2nd Sem/C.E./btech-2-sem-chemistry-1-bsch201-2023.pdf
  MAKAUT/2nd Sem/C.E./btech-2-sem-chemistry-1-bsch201-2024.pdf
  MAKAUT/2nd Sem/C.E./btech-2-sem-chemistry-bsch201-2025 (1).pdf
  MAKAUT/2nd Sem/C.E./btech-2-sem-english-hmhu201-2024.pdf
  MAKAUT/2nd Sem/C.E./btech-2-sem-mathematics-2-b-bsm202-2023.pdf
  MAKAUT/2nd Sem/C.E./btech-2-sem-mathematics-2-bsm-202-n-2019.pdf
  MAKAUT/2nd Sem/C.E./btech-2-sem-mathematics-2a-bsm-201n-2019.pdf
  MAKAUT/2nd Sem/C.E./btech-2-sem-mathematics-2a-bsm201-2023.pdf
  MAKAUT/2nd Sem/C.E./btech-2-sem-mathematics-2a-bsm201-2024.pdf
  MAKAUT/2nd Sem/C.E./btech-2-sem-physics-1-bsph201-2023.pdf
  MAKAUT/2nd Sem/C.E./btech-2-sem-physics-1-bsph201-2024.pdf
  MAKAUT/2nd Sem/C.E./btech-2-sem-programming-for-problem-solving-escs201-2023.pdf
  MAKAUT/2nd Sem/C.E./btech-cs-201-basic-computation-and-principles-of-computer-programming-2017.pdf
  MAKAUT/2nd Sem/C.E./btech-cs-201-basic-computation-and-principles-of-computer-programming-2018.pdf
  MAKAUT/2nd Sem/C.E./btech-cs-201-basic-computation-and-principles-of-computer-programming-2019.pdf
  MAKAUT/2nd Sem/C.E./btech-cs-201-chemistry-1-2017.pdf
  MAKAUT/2nd Sem/C.E./btech-es-201-basic-electrical-and-electronic-engineering-2-2018.pdf
  MAKAUT/2nd Sem/C.E./btech-es-201-basic-electrical-and-electronics-engineering-2-2016.pdf
  MAKAUT/2nd Sem/C.E./btech-es-201-part-2-basic-electrical-and-electronic-engineering-2-2017.pdf
  MAKAUT/2nd Sem/C.E./btech-es-201-part-2-basic-electrical-and-electronics-engineering-2-2017.pdf
  MAKAUT/2nd Sem/C.E./btech-es-201t-basic-electrical-and-electronic-engineering-2-2018.pdf
  MAKAUT/2nd Sem/C.E./btech-es-cs-2-sem-programming-for-problem-solving-escs201-2024.pdf
  MAKAUT/2nd Sem/C.E./btech-hm-hu-201n-english-2019.pdf
  MAKAUT/2nd Sem/C.E./btech-m-201-mathematics-2-2016.pdf
  MAKAUT/2nd Sem/C.E./btech-m-201-mathematics-2-2017.pdf
  MAKAUT/2nd Sem/C.E./btech-m-201-mathematics-2-2018.pdf
  MAKAUT/2nd Sem/C.E./btech-m-201-mathematics-2-2019.pdf
  MAKAUT/2nd Sem/C.E./btech-me-201-engineering-thermodynamics-and-fluid-mechanics-2016.pdf
  MAKAUT/2nd Sem/C.E./btech-me-201-engineering-thermodynamics-and-fluid-mechanics-2017.pdf
Labels: enhancement, Intermediate, SSOC S4

#318 Add the pyq of electrical department of 1st semester
  MAKAUT/1st Sem/EE/btech-1-sem-basic-electrical-and-electronic-engineering-1-es-101-part-2-2018.pdf
  MAKAUT/1st Sem/EE/btech-1-sem-basic-electrical-engineering-es-ee-101-2019.pdf
  MAKAUT/1st Sem/EE/btech-1-sem-basic-electrical-engineering-es-ee-101-2020.pdf
  MAKAUT/1st Sem/EE/btech-1-sem-basic-electrical-engineering-esee101-2023.pdf
  MAKAUT/1st Sem/EE/btech-1-sem-chemistry-1-bs-ch-101-2019.pdf
  MAKAUT/1st Sem/EE/btech-1-sem-chemistry-1-bs-ch-101-2020.pdf
  MAKAUT/1st Sem/EE/btech-1-sem-mathematics-1a-bsm-101-2020.pdf
  MAKAUT/1st Sem/EE/btech-1-sem-mathematics-1a-bsm101-2023.pdf
  MAKAUT/1st Sem/EE/btech-1-sem-mathematics-1b-bs-m-102-2019.pdf
  MAKAUT/1st Sem/EE/btech-1-sem-mathematics-1b-bs-m-102-2020.pdf
  MAKAUT/1st Sem/EE/btech-1-sem-mathematics-1b-bsm102-2023.pdf
  MAKAUT/1st Sem/EE/btech-1-sem-physics-1-bs-ph101-2024.pdf
  MAKAUT/1st Sem/EE/btech-1-sem-physics-1-bsph101-2023.pdf
  MAKAUT/1st Sem/EE/btech-1-sem-physics-1-ph-101-2017.pdf
  MAKAUT/1st Sem/EE/btech-es-101-basic-electrical-and-electronic-engineering-1-2019.pdf
  MAKAUT/1st Sem/EE/btech-es-101-basic-electrical-and-electronic-engineering-1-v2-2019.pdf
  MAKAUT/1st Sem/EE/btech-es-101-basic-electrical-and-electronics-engineering-1-2015.pdf
  MAKAUT/1st Sem/EE/btech-es-101-basic-electrical-and-electronics-engineering-1-2016.pdf
  MAKAUT/1st Sem/EE/btech-hu-101-english-language-and-communication-2015.pdf
  MAKAUT/1st Sem/EE/btech-hu-101-english-language-and-communication-2016.pdf
  MAKAUT/1st Sem/EE/btech-hu-101-english-language-and-communication-2017.pdf
  MAKAUT/1st Sem/EE/btech-m-101-mathematics-2014.pdf
  MAKAUT/1st Sem/EE/btech-m-101-mathematics-2016.pdf
  MAKAUT/1st Sem/EE/btech-me-1-sem-engineering-mechanics-me-101-2018.pdf
  MAKAUT/1st Sem/EE/btech-me-101-mechanical-sciences-2014.pdf
  MAKAUT/1st Sem/EE/btech-me-101-mechanical-sciences-2017.pdf
Labels: enhancement, Intermediate, SSOC S4

#322 Added the pyq of I.T. department of 2nd semester
  MAKAUT/2nd Sem/I.T./btech-2-sem-basic-electrical-engineering-es-ee101-2024.pdf
  MAKAUT/2nd Sem/I.T./btech-2-sem-chemistry-1-bsch201-2023.pdf
  MAKAUT/2nd Sem/I.T./btech-2-sem-chemistry-1-bsch201-2024 (1).pdf
  MAKAUT/2nd Sem/I.T./btech-2-sem-chemistry-1-bsch201-2024.pdf
  MAKAUT/2nd Sem/I.T./btech-2-sem-chemistry-bsch201-2025.pdf
  MAKAUT/2nd Sem/I.T./btech-2-sem-english-hmhu201-2023.pdf
  MAKAUT/2nd Sem/I.T./btech-2-sem-english-hmhu201-2024.pdf
  MAKAUT/2nd Sem/I.T./btech-2-sem-mathematics-2a-bsm201-2023.pdf
  MAKAUT/2nd Sem/I.T./btech-2-sem-mathematics-2a-bsm201-2024 (1).pdf
  MAKAUT/2nd Sem/I.T./btech-2-sem-mathematics-2a-bsm201-2024.pdf
  MAKAUT/2nd Sem/I.T./btech-2-sem-physics-1-bs-ph-201-n-2019.pdf
  MAKAUT/2nd Sem/I.T./btech-2-sem-physics-1-bsph201-2023.pdf
  MAKAUT/2nd Sem/I.T./btech-2-sem-physics-1-bsph201-2024.pdf
  MAKAUT/2nd Sem/I.T./btech-2-sem-programming-for-problem-solving-escs201-2023.pdf
  MAKAUT/2nd Sem/I.T./btech-cs-201-basic-computation-and-principles-of-computer-programming-2017.pdf
  MAKAUT/2nd Sem/I.T./btech-cs-201-basic-computation-and-principles-of-computer-programming-2018.pdf
  MAKAUT/2nd Sem/I.T./btech-cs-201-basic-computation-and-principles-of-computer-programming-2019.pdf
  MAKAUT/2nd Sem/I.T./btech-es-201-basic-electrical-and-electronic-engineering-2-2018.pdf
  MAKAUT/2nd Sem/I.T./btech-es-201t-basic-electrical-and-electronic-engineering-2-2018.pdf
  MAKAUT/2nd Sem/I.T./btech-es-cs-2-sem-programming-for-problem-solving-escs201-2024.pdf
  MAKAUT/2nd Sem/I.T./btech-m-201-mathematics-2-2018.pdf
  MAKAUT/2nd Sem/I.T./btech-m-201-mathematics-2-2019.pdf
  MAKAUT/2nd Sem/I.T./btech-me-201-engineering-thermodynamics-and-fluid-mechanics-2017.pdf
Labels: enhancement, Intermediate, SSOC S4

#324 Add the pyq of information technology department of 5th semester
  MAKAUT/5th Sem/I.T./btech-5-sem-economics-for-engineers-hu-501-2019.pdf
  MAKAUT/5th Sem/I.T./btech-esc-5-sem-software-engineering-esc501-2023.pdf
  MAKAUT/5th Sem/I.T./btech-hsmc-5-sem-introduction-to-industrial-management-hsmc-501-2023.pdf
  MAKAUT/5th Sem/I.T./btech-hsmc-5-sem-introduction-to-industrial-management-humanities-3-hsmc-501-2023.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-circuit-theory-and-networks-2012.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-computer-architecture-2015.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-computer-architecture-2017.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-computer-architecture-2019.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-data-communication-2013.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-design-and-analysis-of-algorithm-2012.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-design-and-analysis-of-algorithms-2016.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-design-and-analysis-of-algorithms-2017.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-design-and-analysis-of-algorithms-it-501-2019.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-economics-for-engineers-2012.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-microprocessors-and-microcontrollers-2016.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-object-technology-and-uml-2011.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-object-technology-and-uml-2012.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-operating-system-2015.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-operating-system-2016.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-operating-system-2017.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-operating-system-2019.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-operation-research-and-optimization-technique-2012.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-programming-practices-using-cpp-2012.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-programming-practices-using-cpp-2014.pdf
  MAKAUT/5th Sem/I.T./btech-it-5-sem-programming-practices-using-cpp-2017.pdf
  MAKAUT/5th Sem/I.T./btech-pec-it-5-sem-artificial-intelligence-pec-it-501b-2023.pdf
  MAKAUT/5th Sem/I.T./btech-pec-it-5-sem-artificial-intelligence-pec-it501b-2023.pdf
Labels: enhancement, Intermediate, SSOC S4

#326 Added PYQs for ME 3rd, 4th, 5th Sem
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/3rd Sem/Mathematical Methods (MTH2001)/MATH 2001- 3rd Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/3rd Sem/Mathematical Methods (MTH2001)/MATH 2001- 3rd Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/3rd Sem/Mathematical Methods (MTH2001)/MATH 2001- 3rd Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/3rd Sem/Physics- II (PHY2101)/PHYS 2101- 3rd Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/3rd Sem/Physics- II (PHY2101)/PHYS 2101- 3rd Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/3rd Sem/Physics- II (PHY2101)/PHYS 2101- 3rd Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/3rd Sem/Physics- II (PHY2101)/PHYS 2101- 3rd Sem(Backlog) 2021.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/4th Sem/Fluid Machinery (MEC2202)/MECH 2201- 4th Sem(Backlog)  2021.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/4th Sem/Fluid Machinery (MEC2202)/MECH 2201- 4th Sem(Backlog)  2022.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/4th Sem/Fluid Machinery (MEC2202)/MECH 2202- 4th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/4th Sem/Fluid Machinery (MEC2202)/MECH 2202- 4th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/4th Sem/Fluid Machinery (MEC2202)/MECH 2202- 4th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/4th Sem/Manufacturing Processes (MEC2204)/MECH 2204- 4th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/4th Sem/Manufacturing Processes (MEC2204)/MECH 2204- 4th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/4th Sem/Manufacturing Processes (MEC2204)/MECH 2204- 4th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/4th Sem/Manufacturing Processes (MEC2204)/MECH 2204- 4th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/5th Sem/Aerodynamics (MEC3143)/MECH 3238- 6th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/5th Sem/Aerodynamics (MEC3143)/MECH 3238- 6th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/5th Sem/Aerodynamics (MEC3143)/MECH 3238- 6th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/5th Sem/Heat Transfer (MEC3102)/MECH 3102- 5th Sem 2020.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/5th Sem/Heat Transfer (MEC3102)/MECH 3102- 5th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/5th Sem/Heat Transfer (MEC3102)/MECH 3102- 5th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/5th Sem/Heat Transfer (MEC3102)/MECH 3102- 5th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/5th Sem/Heat Transfer (MEC3102)/MECH 3102- 5th Sem(Backlog) 2021.pdf
Labels: enhancement, Advanced, SSOC S4

#328 Added Structured `README.md` for Electronics & Communication Engineering – VIT Bhopal University (#321)
  VIT Bhopal University/02. Electronics & Communication Engineering/README.md
Labels: enhancement, Advanced, SSOC S4, Drive Links

#330 Added the pyq of electrical department of 5th semester
  MAKAUT/5th Sem/ECE/btech-5-sem-economics-for-engineers-hu-501-2019.pdf
  MAKAUT/5th Sem/ECE/btech-ec-5-sem-control-system-ec-503-2020.pdf
  MAKAUT/5th Sem/ECE/btech-ec-5-sem-data-structure-and-c-ec-504b-2019.pdf
  MAKAUT/5th Sem/ECE/btech-ec-501-analog-communication-2012.pdf
  MAKAUT/5th Sem/ECE/btech-ec-501-analog-communication-2014.pdf
  MAKAUT/5th Sem/ECE/btech-ec-501-analog-communication-2016.pdf
  MAKAUT/5th Sem/ECE/btech-ec-501-analog-communication-2017.pdf
  MAKAUT/5th Sem/ECE/btech-ec-501-telecommunication-systems-old-2012.pdf
  MAKAUT/5th Sem/ECE/btech-ec-502-microprocessor-and-microcontroller-2010.pdf
  MAKAUT/5th Sem/ECE/btech-ec-502-microprocessor-and-microcontroller-2014.pdf
  MAKAUT/5th Sem/ECE/btech-ec-502-microprocessor-and-microcontroller-2015.pdf
  MAKAUT/5th Sem/ECE/btech-ec-502-microprocessor-and-microcontroller-2017.pdf
  MAKAUT/5th Sem/ECE/btech-ec-502-microprocessor-and-microcontrollers-2016.pdf
  MAKAUT/5th Sem/ECE/btech-ec-503-computer-architecture-and-organization-old-2012.pdf
  MAKAUT/5th Sem/ECE/btech-ec-503-control-system-2011.pdf
  MAKAUT/5th Sem/ECE/btech-ec-503-control-system-2014.pdf
  MAKAUT/5th Sem/ECE/btech-ec-503-control-system-2017.pdf
  MAKAUT/5th Sem/ECE/btech-ec-504a-computer-architecture-2012.pdf
  MAKAUT/5th Sem/ECE/btech-ec-504a-computer-architecture-2015.pdf
  MAKAUT/5th Sem/ECE/btech-ec-504a-computer-architecture-2016.pdf
  MAKAUT/5th Sem/ECE/btech-ec-504a-computer-architecture-2017.pdf
  MAKAUT/5th Sem/ECE/btech-ec-504b-data-structure-and-c-2012.pdf
  MAKAUT/5th Sem/ECE/btech-ec-504b-data-structure-and-c-2014.pdf
  MAKAUT/5th Sem/ECE/btech-ec-504b-data-structure-and-c-2015.pdf
  MAKAUT/5th Sem/ECE/btech-ec-504b-data-structure-and-c-2016.pdf
  MAKAUT/5th Sem/ECE/btech-ec-504b-data-structure-and-c-2017.pdf
  MAKAUT/5th Sem/ECE/btech-ece-5-sem-computer-architecture-and-organization-2012.pdf
  MAKAUT/5th Sem/ECE/btech-ece-5-sem-digital-communication-2012.pdf
  MAKAUT/5th Sem/ECE/btech-ece-5-sem-microprocessor-and-microcontroller-s3-2012.pdf
  MAKAUT/5th Sem/ECE/btech-esc-5-sem-software-engineering-esc501-2023.pdf
Labels: enhancement, Advanced, SSOC S4

#338 Add the pyq of information technology department of 6th sem
  MAKAUT/6th Sem/IT/btech-cse-it-6-sem-distributed-systems-pec-it601b-2025.pdf
  MAKAUT/6th Sem/IT/btech-hm-hu-6-sem-operations-research-hm-hu601-2023.pdf
  MAKAUT/6th Sem/IT/btech-it-6-sem-artificial-intelligence-2015.pdf
  MAKAUT/6th Sem/IT/btech-it-6-sem-artificial-intelligence-2017.pdf
  MAKAUT/6th Sem/IT/btech-it-6-sem-compiler-design-2015.pdf
  MAKAUT/6th Sem/IT/btech-it-6-sem-compiler-design-2017.pdf
  MAKAUT/6th Sem/IT/btech-it-6-sem-computer-graphics-2017.pdf
  MAKAUT/6th Sem/IT/btech-it-6-sem-computer-networking-2013.pdf
  MAKAUT/6th Sem/IT/btech-it-6-sem-database-management-system-2014.pdf
  MAKAUT/6th Sem/IT/btech-it-6-sem-database-management-system-2016.pdf
  MAKAUT/6th Sem/IT/btech-it-6-sem-database-management-system-2017.pdf
  MAKAUT/6th Sem/IT/btech-it-6-sem-distributed-systems-pec-it601b-2023.pdf
  MAKAUT/6th Sem/IT/btech-it-6-sem-erp-2016.pdf
  MAKAUT/6th Sem/IT/btech-it-6-sem-erp-2019.pdf
  MAKAUT/6th Sem/IT/btech-it-6-sem-image-processing-pec-it601d-2023.pdf
  MAKAUT/6th Sem/IT/btech-oec-it-6-sem-human-resource-development-and-organizational-behavior-oec-it-601b-2023.pdf
  MAKAUT/6th Sem/IT/btech-oec-it-6-sem-human-resource-development-and-organizational-behavior-oec-it601b-2023.pdf
  MAKAUT/6th Sem/IT/btech-oec-it-6-sem-numerical-methods-oec-it601a-2023.pdf
  MAKAUT/6th Sem/IT/btech-pec-it-6-sem-data-warehousing-and-data-mining-pec-it602b-2023.pdf
  MAKAUT/6th Sem/IT/btech-pec-it-6-sem-distributed-systems-pec-it-601b-2023.pdf
  MAKAUT/6th Sem/IT/btech-pec-it-6-sem-distributed-systems-pec-it601b-2024.pdf
Labels: enhancement, Intermediate, SSOC S4

#342 Isuue#341 resolved
  Malla Reddy University/IOT/sem2/I - I SEM.pdf
  Malla Reddy University/IOT/sem3/QB_merged.pdf
  Malla Reddy University/IT/3-1 IT Question Bank All.pdf
  Malla Reddy University/IT/sem3/2-1 IT Question Bank ALL.pdf
  Malla Reddy University/IT/sem3/sem4/II-II IT Question Bank(2022-23).pdf
  Malla Reddy University/IT/sem5/3-1 IT Question Bank All.pdf
Labels: enhancement, Advanced, SSOC S4

#344 Added the pyq of civil department of 3rd semester
  MAKAUT/3rd Sem/CE/btech-3-sem-mathematics-3-bs-m301-2025.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-basic-environmental-engineering-and-elementary-biology-2011.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-basic-environmental-engineering-and-elementary-biology-2012.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-building-materials-and-construction-2010.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-building-materials-and-construction-2011.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-building-materials-and-construction-2012.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-building-materials-and-construction-s3-2012.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-engineering-geology-2011.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-engineering-geology-2012.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-fluid-mechanics-2012.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-humanities-1-effective-technical-communication-ce-hs-301-2023.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-introduction-to-civil-engineering-ce-hs-302-2023.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-mathematics-2011.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-mathematics-2012.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-physics-2-2012.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-solid-mechanics-ce-301-2019.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-structural-mechanics-2009.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-structural-mechanics-2010.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-structural-mechanics-2012.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-surveying-2012.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-surveying-ce-302-2019.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-values-and-ethics-in-profession-2011.pdf
  MAKAUT/3rd Sem/CE/btech-ce-3-sem-values-and-ethics-in-profession-2012.pdf
  MAKAUT/3rd Sem/CE/btech-ce-au-me-3-sem-engineering-mechanics-ce-es-301-2023.pdf
  MAKAUT/3rd Sem/CE/btech-ce-bs-3-sem-biology-for-engineers-ce-bs-301-2023.pdf
  MAKAUT/3rd Sem/CE/btech-ce-bs-3-sem-mathematics-3-transform-and-discrete-mathematics-ce-bs-302-2023.pdf
Labels: enhancement, Intermediate, SSOC S4

#348 Add the pyq of mechanical department of 3rd semester
  MAKAUT/3rd Sem/ME/btech-3-sem-mathematics-3-bs-m301-2023.pdf
  MAKAUT/3rd Sem/ME/btech-3-sem-mathematics-3-differential-calculus-bsc301-2023.pdf
  MAKAUT/3rd Sem/ME/btech-es-me-3-sem-engineering-mechanics-es-me-301-2023.pdf
  MAKAUT/3rd Sem/ME/btech-me-3-sem-applied-thermodynamics-2011.pdf
  MAKAUT/3rd Sem/ME/btech-me-3-sem-applied-thermodynamics-2012.pdf
  MAKAUT/3rd Sem/ME/btech-me-3-sem-applied-thermodynamics-2014.pdf
  MAKAUT/3rd Sem/ME/btech-me-3-sem-applied-thermodynamics-2016.pdf
  MAKAUT/3rd Sem/ME/btech-me-3-sem-applied-thermodynamics-2017.pdf
  MAKAUT/3rd Sem/ME/btech-me-3-sem-engineering-materials-2012.pdf
  MAKAUT/3rd Sem/ME/btech-me-3-sem-engineering-materials-2016.pdf
  MAKAUT/3rd Sem/ME/btech-me-3-sem-engineering-materials-2017.pdf
  MAKAUT/3rd Sem/ME/btech-me-3-sem-engineering-mechanics-me-ce-aue-301-2020.pdf
  MAKAUT/3rd Sem/ME/btech-me-3-sem-manufacturing-processes-pc-me302-2025.pdf
  MAKAUT/3rd Sem/ME/btech-me-3-sem-strength-of-material-2012.pdf
  MAKAUT/3rd Sem/ME/btech-me-3-sem-strength-of-material-2015.pdf
  MAKAUT/3rd Sem/ME/btech-me-3-sem-strength-of-materials-2011.pdf
  MAKAUT/3rd Sem/ME/btech-me-3-sem-strength-of-materials-2014.pdf
  MAKAUT/3rd Sem/ME/btech-me-3-sem-strength-of-materials-2017.pdf
  MAKAUT/3rd Sem/ME/btech-pc-me-3-sem-manufacturing-processes-pc-me-302-2024.pdf
  MAKAUT/3rd Sem/ME/btech-pc-me-3-sem-thermodynamics-pc-me301-2023.pdf
  MAKAUT/3rd Sem/ME/btech-pc-me-3-sem-thermodynamics-pc-me301-2024.pdf
Labels: enhancement, Intermediate, SSOC S4

#353 Added the pyq of fashion technology of 3rd semester
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-basic-environmental-engineering-and-elementary-biology-2011.pdf
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-basic-environmental-engineering-and-elementary-biology-2012.pdf
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-biochemistry-and-nutrition-2009.pdf
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-biochemistry-and-nutrition-2012.pdf
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-chemistry-of-food-2012.pdf
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-food-microbiology-2011.pdf
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-food-microbiology-2012.pdf
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-food-microbiology-s3-2012.pdf
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-mathematics-3-2009.pdf
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-mathematics-3-2012.pdf
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-mechanical-design-of-process-equipment-2009.pdf
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-mechanical-design-of-process-equipment-2010.pdf
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-mechanical-design-of-process-equipment-2011.pdf
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-mechanical-design-of-process-equipment-2012.pdf
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-process-calculation-thermodynamics-and-food-science-2009.pdf
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-process-calculations-thermodynamics-and-food-science-2011.pdf
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-process-calculations-thermodynamics-and-food-science-2012.pdf
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-thermodynamics-and-kinetics-2012.pdf
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-values-and-ethics-in-profession-2011.pdf
  MAKAUT/3rd Sem/FT/btech-ft-3-sem-values-and-ethics-in-profession-2012.pdf
  MAKAUT/3rd Sem/FT/btech-me-4-sem-manufacturing-technology-2009.pdf
Labels: enhancement, Intermediate, SSOC S4

#358 Added README.md for Mechanical Engineering – VIT Bhopal University / 03. ME (#347)
  VIT Bhopal University/03.Mechanical Engineering (ME)/README.md
Labels: enhancement, Intermediate, SSOC S4, Drive Links

#359 Add the pyq of automobile engineering
  MAKAUT/1st Sem/AUE/btech-1-sem-basic-electrical-engineering-es-ee-101-2019.pdf
  MAKAUT/1st Sem/AUE/btech-1-sem-basic-electrical-engineering-esee101-2023.pdf
  MAKAUT/1st Sem/AUE/btech-1-sem-chemistry-1-bs-ch101-2024.pdf
  MAKAUT/1st Sem/AUE/btech-1-sem-chemistry-1-bsch101-2023.pdf
  MAKAUT/1st Sem/AUE/btech-1-sem-mathematics-1a-bs-m101-2025.pdf
  MAKAUT/1st Sem/AUE/btech-1-sem-mathematics-1a-bsm-101-2020.pdf
  MAKAUT/1st Sem/AUE/btech-1-sem-mathematics-1a-bsm101-2023.pdf
  MAKAUT/1st Sem/AUE/btech-1-sem-mathematics-1b-bsm102-2023.pdf
  MAKAUT/1st Sem/AUE/btech-1-sem-physics-1-bs-ph101-2025.pdf
  MAKAUT/1st Sem/AUE/btech-1-sem-physics-1-bsph101-2023.pdf
  MAKAUT/1st Sem/AUE/btech-1-sem-physics-1-ph-101-2020.pdf
  MAKAUT/1st Sem/AUE/btech-2-sem-basic-electrical-engineering-es-ee101-2024.pdf
  MAKAUT/1st Sem/AUE/btech-2-sem-chemistry-1-bsch201-2023.pdf
  MAKAUT/1st Sem/AUE/btech-2-sem-chemistry-1-bsch201-2024.pdf
  MAKAUT/1st Sem/AUE/btech-2-sem-chemistry-bsch201-2025.pdf
  MAKAUT/1st Sem/AUE/btech-2-sem-english-hmhu201-2024.pdf
  MAKAUT/1st Sem/AUE/btech-2-sem-mathematics-2a-bsm201-2024.pdf
  MAKAUT/1st Sem/AUE/btech-2-sem-physics-1-bsph201-2024.pdf
  MAKAUT/1st Sem/AUE/btech-es-101-basic-electrical-and-electronic-engineering-1-2019.pdf
  MAKAUT/1st Sem/AUE/btech-es-cs-2-sem-programming-for-problem-solving-escs201-2024.pdf
  MAKAUT/1st Sem/AUE/btech-hm-hu-201n-english-2019.pdf
Labels: enhancement, Intermediate, SSOC S4

#367 [#74] Added 22 PYQs for 1st and 2nd Sem | Reorganized CSE & ECE folders [Task 2.2.10]
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/1st Sem/Applied Chemistry (BS-103)/Applied Chemistry (Jan 2024) (BS-103).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/1st Sem/Applied Chemistry (BS-103)/Applied Chemistry (Nov 2023) (BS-103).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/1st Sem/Applied Mathematics-I (BS-111)/Applied Mathematics-I (Dec 2024) (BS-111).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/1st Sem/Applied Mathematics-I (BS-111)/Applied Mathematics-I (Mar 2023) (BS-111).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/1st Sem/Applied Physics-I (BS-105)/Applied Physics-I (Jan 2024) (BS-105).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/1st Sem/Applied Physics-I (BS-105)/Applied Physics-I (Nov 2023) (BS-105).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/1st Sem/Communication Skills (HS-113)/Communication Skills (Jan 2024) (HS-113).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/1st Sem/Communication Skills (HS-113)/Communication Skills (Jan 2025) (HS-113).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/1st Sem/Electrical Science (ES 107)/Electrical Science (Jan 2025) (ES 107).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/1st Sem/Electrical Science (ES 107)/Electrical Science (Mar 2023) (ES 107).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/1st Sem/Manufacturing Process (ES-119)/Manufacturing Process (Dec 2024) (ES-119).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/1st Sem/Manufacturing Process (ES-119)/Manufacturing Process (Nov 2023) (ES-119).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/2nd Sem/Applied Mathematics-2 (BS-112)/Applied Mathematics-2 (Jul 2023) (BS-112).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/2nd Sem/Applied Mathematics-2 (BS-112)/Applied Mathematics-2 (Jun 2024) (BS-112).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/2nd Sem/Applied Physics-2  (BS-106)/Applied Physics-2 (July 2023) (BS-106).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/2nd Sem/Applied Physics-2  (BS-106)/Applied Physics-2 (Jun 2024) (BS-106).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/2nd Sem/Engineering Mechanics (ES-114)/Engineering Mechanics (July 2023) (ES-114).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/2nd Sem/Engineering Mechanics (ES-114)/Engineering Mechanics (Jun 2024) (ES-114).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/2nd Sem/Environmental Studies (BS-110)/Environmental Studies (July 2023) (BS-110).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/2nd Sem/Environmental Studies (BS-110)/Environmental Studies (Jun 2024) (BS-110).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/2nd Sem/Programming In C (ES-102)/Programming In C (July 2023) (ES-102).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/2nd Sem/Programming In C (ES-102)/Programming In C (Jun 2024) (ES-102).pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/3rd Sem/Discrete Mathematics CIC-205/DM End Term 2024.pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/3rd Sem/Discrete Mathematics CIC-205/DM mid sem 1 - 2023.pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/3rd Sem/Discrete Mathematics CIC-205/DM_PYQ_feb_23.pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/3rd Sem/OOPS CIC-211/End Term April 2016.pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/3rd Sem/OOPS CIC-211/End Term Feb 2023.pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/3rd Sem/OOPS CIC-211/OOPS End Term 2024.pdf
  MAIT DELHI (GGSIPU)/01.Computer Science Engineering CSE/CSE_Syllabus.pdf
  MAIT DELHI (GGSIPU)/02.Electronics and Communication Engineering ECE/3rd Sem/Analog Communication ECC-209/AC mid sem 1.pdf
  MAIT DELHI (GGSIPU)/02.Electronics and Communication Engineering ECE/3rd Sem/Analog Communication ECC-209/Analog Comm Paper 2022-23.pdf
  MAIT DELHI (GGSIPU)/02.Electronics and Communication Engineering ECE/3rd Sem/Digital Logic and Circuit Design/DLCD End Term 2024.pdf
  MAIT DELHI (GGSIPU)/02.Electronics and Communication Engineering ECE/3rd Sem/Digital Logic and Circuit Design/DLCD mid sem 2.pdf
  MAIT DELHI (GGSIPU)/02.Electronics and Communication Engineering ECE/3rd Sem/Digital Logic and Circuit Design/Mid Term PYQs 22.pdf
  MAIT DELHI (GGSIPU)/03.Information Technology and Engineering ITE/3rd Sem/Computational Methods ES-201/CM End Term 2024.pdf
  MAIT DELHI (GGSIPU)/03.Information Technology and Engineering ITE/3rd Sem/Computational Methods ES-201/Mid term QP 2022.pdf
  MAIT DELHI (GGSIPU)/03.Information Technology and Engineering ITE/3rd Sem/Data Structures CIC-209/DS End Term 2024.pdf
  MAIT DELHI (GGSIPU)/03.Information Technology and Engineering ITE/3rd Sem/Data Structures CIC-209/DS mid sem 1 - 2023.pdf
  MAIT DELHI (GGSIPU)/03.Information Technology and Engineering ITE/3rd Sem/Data Structures CIC-209/Endsem 2023 Feb.pdf
Labels: enhancement, Intermediate, SSOC S4

#370 Added PYQs for AIML 2nd and 3rd sems
  NIT_Kurukshetra/AI_ML/2nd Sem/Digital System Design(CSIC 100)/CSIC10 ES 2018.pdf
  NIT_Kurukshetra/AI_ML/2nd Sem/Digital System Design(CSIC 100)/CSIC10 ES 2019.pdf
  NIT_Kurukshetra/AI_ML/2nd Sem/Digital System Design(CSIC 100)/CSIC10 ES1 2018.pdf
  NIT_Kurukshetra/AI_ML/2nd Sem/Digital System Design(CSIC 100)/CSIC10 ES1 2019.pdf
  NIT_Kurukshetra/AI_ML/2nd Sem/Digital System Design(CSIC 100)/CSIC10 ES2 2019.pdf
  NIT_Kurukshetra/AI_ML/2nd Sem/Digital System Design(CSIC 100)/CSIC10 ES3 2019.pdf
  NIT_Kurukshetra/AI_ML/2nd Sem/Digital System Design(CSIC 100)/CSIC10 MS 2022.pdf
  NIT_Kurukshetra/AI_ML/2nd Sem/Digital System Design(CSIC 100)/CSIC10 MS1 2025.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Database Management Systems(AIPC 205)/AIPC25 ES 2018.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Database Management Systems(AIPC 205)/AIPC25 ES 2019.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Database Management Systems(AIPC 205)/AIPC25 ES 2020.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Database Management Systems(AIPC 205)/AIPC25 ES 2021.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Database Management Systems(AIPC 205)/AIPC25 ES 2022.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Database Management Systems(AIPC 205)/AIPC25 ES1 2018.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Database Management Systems(AIPC 205)/AIPC25 ES1 2019.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Database Management Systems(AIPC 205)/AIPC25 ES1 2020.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Database Management Systems(AIPC 205)/AIPC25 ES1 2021.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Database Management Systems(AIPC 205)/AIPC25 MS 2020.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Database Management Systems(AIPC 205)/AIPC25 MS 2021.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Database Management Systems(AIPC 205)/AIPC25 MS1 2020.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Database Management Systems(AIPC 205)/AIPC25 MS1 2021.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Database Management Systems(AIPC 205)/AIPC25 MS2 2021.pdf
Labels: enhancement, Intermediate, SSOC S4

#372 Added PYQ for 8 subjects Anna University under semester 4
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/Lecture Notes/EC3492 Digital Signal Processing Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/EC3492 Digital Signal Processing Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/Old Regulation PYQ/DSP (2010) (EC-3492).pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/Old Regulation PYQ/DSP (2011) (EC-3492).pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/Old Regulation PYQ/DSP (2012) (EC-3492).pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/Old Regulation PYQ/DSP (2013) (EC-3492).pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/Old Regulation PYQ/DSP (2014) (EC-3492).pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/Old Regulation PYQ/DSP (2015) (EC-3492).pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/Old Regulation PYQ/DSP (2016) (EC-3492).pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/Old Regulation PYQ/DSP (2017) (EC-3492).pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/Old Regulation PYQ/DSP (2018) (EC-3492).pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/Old Regulation PYQ/DSP (2019) (EC-3492).pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/Old Regulation PYQ/DSP (2020) (EC-3492).pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/Old Regulation PYQ/DSP (2021) (EC-3492).pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/Old Regulation PYQ/DSP (2022) (EC-3492).pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/Old Regulation PYQ/DSP (2024) (EC-3492).pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EC3492-Digital Signal Processing Question Papers/PYQ/Old Regulation PYQ/DSP (2025) (EC-3492).pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3401-Transmission and Distribution Question Papers/Lecture Notes/EE3401 Transmission and Distribution Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3401-Transmission and Distribution Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3401-Transmission and Distribution Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3401-Transmission and Distribution Question Papers/PYQ/EE3401 Transmission and Distribution Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3401-Transmission and Distribution Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3401-Transmission and Distribution Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3402-Linear Integrated Circuits Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3402-Linear Integrated Circuits Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3402-Linear Integrated Circuits Question Papers/PYQ/EE3402 Linear Integrated Circuits Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3402-Linear Integrated Circuits Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3403-Measurements and Instrumentation Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3403-Measurements and Instrumentation Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3403-Measurements and Instrumentation Question Papers/PYQ/EE3403 Measurements and Instrumentation Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3403-Measurements and Instrumentation Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3404-Microprocessor and Microcontroller Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3404-Microprocessor and Microcontroller Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3404-Microprocessor and Microcontroller Question Papers/PYQ/EE3404 Microprocessor and Microcontroller Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3404-Microprocessor and Microcontroller Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3405-Electrical Machines II Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3405-Electrical Machines II Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3405-Electrical Machines II Question Papers/PYQ/EE3405 Electrical Machines II Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3405-Electrical Machines II Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/EE3405-Electrical Machines II Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/GE3451-Environmental Sciences and Sustainability Question Papers/Lecture Notes/GE3451 Environmental Sciences and Sustainability Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/GE3451-Environmental Sciences and Sustainability Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/GE3451-Environmental Sciences and Sustainability Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/GE3451-Environmental Sciences and Sustainability Question Papers/PYQ/GE3451 Environmental Sciences and Sustainability Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/GE3451-Environmental Sciences and Sustainability Question Papers/PYQ/GE3451 Environmental Sciences and Sustainability Syllabus.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/GE3451-Environmental Sciences and Sustainability Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/IT3401-Web Essentials Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/IT3401-Web Essentials Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/IT3401-Web Essentials Question Papers/PYQ/IT3401 Web Essentials Question Papers.pdf
Labels: enhancement, Advanced, SSOC S4

#378 Added syllabus for IT, MECH departments
  Chennai-Institute-of-Technology-Kanchipuram-TN/Information Technology/IT_Syllabus.pdf
  Chennai-Institute-of-Technology-Kanchipuram-TN/Mechanical Engineering/MECH_Syllabus.pdf
Labels: enhancement, Advanced, SSOC S4

#382 Added 6 subjects PYQ for Semester 4 Anna University
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/MA3391-Probability and Statistics Question Papers/Lecture Notes/MA3391 Probability and Statistics Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/MA3391-Probability and Statistics Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/MA3391-Probability and Statistics Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/MA3391-Probability and Statistics Question Papers/PYQ/MA3391 Probability and Statistics Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/MA3391-Probability and Statistics Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/MA3452-Vector Calculus and Complex Functions Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/MA3452-Vector Calculus and Complex Functions Question Papers/PYQ/MA3452 Vector Calculus and Complex Functions Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3451-Thermal Engineering Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3451-Thermal Engineering Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3451-Thermal Engineering Question Papers/PYQ/ME3451 Thermal Engineering Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3451-Thermal Engineering Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3451-Thermal Engineering Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3491-Theory of Machines Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3491-Theory of Machines Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3491-Theory of Machines Question Papers/PYQ/ME3491 Theory of Machines Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3491-Theory of Machines Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3491-Theory of Machines Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3492-Hydraulics and Pneumatics Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3492-Hydraulics and Pneumatics Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3492-Hydraulics and Pneumatics Question Papers/PYQ/ME3492 Hydraulics and Pneumatics Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3492-Hydraulics and Pneumatics Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3492-Hydraulics and Pneumatics Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3493-Manufacturing Technology Question Papers/PYQ/Apr May 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3493-Manufacturing Technology Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3493-Manufacturing Technology Question Papers/PYQ/ME3493 Manufacturing Technology Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3493-Manufacturing Technology Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Second Year/Semester 2/ME3493-Manufacturing Technology Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
Labels: enhancement, Advanced, SSOC S4

#380 Added PYQs for Chemical Engineering Courses – VIT Bhopal University / 05. Chemical Engineering (ChE) (#379)
  VIT Bhopal University/05.Chemical Engineering (ChE)/Chemical Technology(CHE1004 )/Chemical Technology(Dec 2019)(CHE1004 ) (2).pdf
  VIT Bhopal University/05.Chemical Engineering (ChE)/Chemical Technology(CHE1004 )/Chemical Technology(Dec 2019)(CHE1004 ) (3).pdf
  VIT Bhopal University/05.Chemical Engineering (ChE)/Chemical Technology(CHE1004 )/Chemical Technology(Dec 2019)(CHE1004 ).pdf
  VIT Bhopal University/05.Chemical Engineering (ChE)/Chemical Technology(CHE1004 )/README.md
  VIT Bhopal University/05.Chemical Engineering (ChE)/Environmental Engineering(CLE1006 )/Environmental Engineering(Dec 2020)(CLE1006 ) (2).pdf
  VIT Bhopal University/05.Chemical Engineering (ChE)/Environmental Engineering(CLE1006 )/Environmental Engineering(Dec 2020)(CLE1006 ) (3).pdf
  VIT Bhopal University/05.Chemical Engineering (ChE)/Environmental Engineering(CLE1006 )/Environmental Engineering(Dec 2020)(CLE1006 ) (4).pdf
  VIT Bhopal University/05.Chemical Engineering (ChE)/Environmental Engineering(CLE1006 )/Environmental Engineering(Dec 2020)(CLE1006 ) (5).pdf
  VIT Bhopal University/05.Chemical Engineering (ChE)/Environmental Engineering(CLE1006 )/Environmental Engineering(Dec 2020)(CLE1006 ) (6).pdf
  VIT Bhopal University/05.Chemical Engineering (ChE)/Environmental Engineering(CLE1006 )/Environmental Engineering(Dec 2020)(CLE1006 )(1).pdf
  VIT Bhopal University/05.Chemical Engineering (ChE)/Environmental Engineering(CLE1006 )/Environmental Engineering(Dec 2020)(CLE1006 )..pdf
  VIT Bhopal University/05.Chemical Engineering (ChE)/Environmental Engineering(CLE1006 )/Environmental Engineering(Dec 2020)(CLE1006 ).pdf
  VIT Bhopal University/05.Chemical Engineering (ChE)/Environmental Engineering(CLE1006 )/README.md
  VIT Bhopal University/05.Chemical Engineering (ChE)/Fuel Cells(MEE1013 )/Fuel Cells(MEE1013 ) (2).pdf
  VIT Bhopal University/05.Chemical Engineering (ChE)/Fuel Cells(MEE1013 )/Fuel Cells(MEE1013 )(1).pdf
  VIT Bhopal University/05.Chemical Engineering (ChE)/Fuel Cells(MEE1013 )/Fuel Cells(MEE1013 ).pdf
  VIT Bhopal University/05.Chemical Engineering (ChE)/Fuel Cells(MEE1013 )/Fuel Cells(MEE1013),.pdf
  VIT Bhopal University/05.Chemical Engineering (ChE)/Fuel Cells(MEE1013 )/Fuel Cells(dec 2021)(MEE1013 ) (2).pdf
  VIT Bhopal University/05.Chemical Engineering (ChE)/Fuel Cells(MEE1013 )/Fuel Cells(dec 2021)(MEE1013 ).pdf
  VIT Bhopal University/05.Chemical Engineering (ChE)/Fuel Cells(MEE1013 )/README.md
Labels: enhancement, Advanced, SSOC S4

#386 Added the pyq of electrical engineering department of 5th semester
  MAKAUT/5th Sem/EE/btech-5-sem-economics-for-engineers-hu-501-2019.pdf
  MAKAUT/5th Sem/EE/btech-ee-5-sem-control-system-1-2012.pdf
  MAKAUT/5th Sem/EE/btech-ee-5-sem-control-system-1-v2-2012.pdf
  MAKAUT/5th Sem/EE/btech-ee-5-sem-data-structure-and-algorithm-2012.pdf
  MAKAUT/5th Sem/EE/btech-ee-5-sem-economics-for-engineers-2012.pdf
  MAKAUT/5th Sem/EE/btech-ee-5-sem-electrical-machine-2-2012.pdf
  MAKAUT/5th Sem/EE/btech-ee-5-sem-electrical-machines-2-2012.pdf
  MAKAUT/5th Sem/EE/btech-ee-5-sem-microprocessor-and-microcontroller-2012.pdf
  MAKAUT/5th Sem/EE/btech-ee-5-sem-power-electronics-2012.pdf
  MAKAUT/5th Sem/EE/btech-ee-5-sem-power-systems-1-2012.pdf
  MAKAUT/5th Sem/EE/btech-ee-5-sem-system-programming-and-operating-system-2012.pdf
  MAKAUT/5th Sem/EE/btech-ee-501-electric-machines-2-2015.pdf
  MAKAUT/5th Sem/EE/btech-ee-501-electric-machines-2-2016.pdf
  MAKAUT/5th Sem/EE/btech-ee-501-electric-machines-2-2017.pdf
  MAKAUT/5th Sem/EE/btech-ee-501-electrical-machine-2-2012.pdf
  MAKAUT/5th Sem/EE/btech-ee-501-electrical-machine-2-2019.pdf
  MAKAUT/5th Sem/EE/btech-ee-501-electrical-machines-2-2014.pdf
  MAKAUT/5th Sem/EE/btech-ee-502-power-system-1-2015.pdf
  MAKAUT/5th Sem/EE/btech-ee-502-power-system-1-2016.pdf
  MAKAUT/5th Sem/EE/btech-ee-502-power-system-1-2017.pdf
  MAKAUT/5th Sem/EE/btech-ee-502-power-systems-1-2014.pdf
  MAKAUT/5th Sem/EE/btech-ee-503-control-system-1-2012.pdf
  MAKAUT/5th Sem/EE/btech-ee-503-control-system-1-2014.pdf
  MAKAUT/5th Sem/EE/btech-ee-503-control-system-1-2015.pdf
  MAKAUT/5th Sem/EE/btech-ee-503-control-system-1-2016.pdf
  MAKAUT/5th Sem/EE/btech-ee-503-control-system-1-2017.pdf
  MAKAUT/5th Sem/EE/btech-ee-503-control-system-1-2019.pdf
  MAKAUT/5th Sem/EE/btech-ee-504c-microprocessor-and-microcontroller-2014.pdf
  MAKAUT/5th Sem/EE/btech-ee-504c-microprocessor-and-microcontroller-2016.pdf
  MAKAUT/5th Sem/EE/btech-ee-504c-microprocessor-and-microcontroller-2019.pdf
  MAKAUT/5th Sem/EE/btech-ee-504c-microprocessors-and-microcontroller-2015.pdf
  MAKAUT/5th Sem/EE/btech-ee-504c-microprocessors-and-microcontrollers-2017.pdf
  MAKAUT/5th Sem/EE/btech-ee-eee-5-sem-computer-organization-oe-ee501c-2025.pdf
  MAKAUT/5th Sem/EE/btech-ee-eee-5-sem-control-system-pc-ee503-2025.pdf
  MAKAUT/5th Sem/EE/btech-ee-eee-5-sem-object-oriented-programming-oe-ee501b-2025.pdf
  MAKAUT/5th Sem/EE/btech-ee-eee-5-sem-power-electronics-pc-ee501-2025.pdf
  MAKAUT/5th Sem/EE/btech-ee-eee-5-sem-power-system-1-pc-ee502-2025.pdf
  MAKAUT/5th Sem/EE/btech-ee-eee-5-sem-renewable-and-non-conventional-energy-pe-ee501c-2025.pdf
  MAKAUT/5th Sem/EE/btech-esc-5-sem-software-engineering-esc501-2023.pdf
  MAKAUT/5th Sem/EE/btech-hsmc-5-sem-introduction-to-industrial-management-hsmc-501-2023.pdf
Labels: enhancement, Advanced, SSOC S4

#399 Added PYQs for CLE1007, CLE2014, CLE3001, and CLE1004 – VIT Bhopal University / 06. Civil Engineering #398
  VIT Bhopal University/06.Civil Engineering/Construction materials and techniques(CLE1007)/Construction materials and techniques(dec 2020)(CLE1007) (2).pdf
  VIT Bhopal University/06.Civil Engineering/Construction materials and techniques(CLE1007)/Construction materials and techniques(dec 2020)(CLE1007).pdf
  VIT Bhopal University/06.Civil Engineering/Construction materials and techniques(CLE1007)/README.md
  VIT Bhopal University/06.Civil Engineering/Geotechnical earthquake engineering(CLE2014 )/README.me
  VIT Bhopal University/06.Civil Engineering/Geotechnical earthquake engineering(CLE2014 )/geotechnical earthquake engineering(dec 2019)(CLE2014 ) (2).pdf
  VIT Bhopal University/06.Civil Engineering/Geotechnical earthquake engineering(CLE2014 )/geotechnical earthquake engineering(dec 2019)(CLE2014 ) (3).pdf
  VIT Bhopal University/06.Civil Engineering/Geotechnical earthquake engineering(CLE2014 )/geotechnical earthquake engineering(dec 2019)(CLE2014 ) -(1).pdf
  VIT Bhopal University/06.Civil Engineering/Geotechnical earthquake engineering(CLE2014 )/geotechnical earthquake engineering(dec 2019)(CLE2014 ).pdf
  VIT Bhopal University/06.Civil Engineering/Quantity Surveying and Estimating(CLE3001)/Quantity Surveying and Estimating(CLE3001).pdf
  VIT Bhopal University/06.Civil Engineering/Quantity Surveying and Estimating(CLE3001)/README.md
  VIT Bhopal University/06.Civil Engineering/Soil mechanics and foundation engineering(CLE1004 )/README.md
  VIT Bhopal University/06.Civil Engineering/Soil mechanics and foundation engineering(CLE1004 )/Soil mechanics and foundation engineering(dec 2019)(CLE1004 ) (1).pdf
  VIT Bhopal University/06.Civil Engineering/Soil mechanics and foundation engineering(CLE1004 )/Soil mechanics and foundation engineering(dec 2019)(CLE1004 ) (2).pdf
  VIT Bhopal University/06.Civil Engineering/Soil mechanics and foundation engineering(CLE1004 )/Soil mechanics and foundation engineering(dec 2019)(CLE1004 ) (3).pdf
  VIT Bhopal University/06.Civil Engineering/Soil mechanics and foundation engineering(CLE1004 )/Soil mechanics and foundation engineering(dec 2019)(CLE1004 ) (4).pdf
  VIT Bhopal University/06.Civil Engineering/Soil mechanics and foundation engineering(CLE1004 )/Soil mechanics and foundation engineering(dec 2019)(CLE1004 )..pdf
  VIT Bhopal University/06.Civil Engineering/Soil mechanics and foundation engineering(CLE1004 )/Soil mechanics and foundation engineering(dec 2019)(CLE1004 ).pdf
Labels: enhancement, Advanced, SSOC S4

#404 Added PYQs for 6th, 7th and 8th Sem of ME branch of HITK
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/6th Sem/Computational Fluid Dynamics (MEC3232)/MECH 3221- 6th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/6th Sem/Computational Fluid Dynamics (MEC3232)/MECH 3221- 6th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/6th Sem/Computational Fluid Dynamics (MEC3232)/MECH 3221- 6th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/6th Sem/Computational Fluid Dynamics (MEC3232)/MECH 3221- 6th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/6th Sem/Computational Fluid Dynamics (MEC3232)/MECH 4144- 7th Sem 2019.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/6th Sem/Computational Fluid Dynamics (MEC3232)/MECH 4144- 7th Sem 2020.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/6th Sem/IC Engine (MECH3211)/MECH 3201- 6th Sem (Backlog) 2021.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/6th Sem/IC Engine (MECH3211)/MECH 3211- 6th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/6th Sem/IC Engine (MECH3211)/MECH 3211- 6th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/6th Sem/IC Engine (MECH3211)/MECH 3211- 6th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/7th Sem/Materials Handling (MEC4132)/MECH 3263- 6th Sem (Backlog) 2021.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/7th Sem/Materials Handling (MEC4132)/MECH 4142- 7th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/7th Sem/Materials Handling (MEC4132)/MECH 4142- 7th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/7th Sem/Materials Handling (MEC4132)/MECH 4142- 7th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/7th Sem/Micro and Nano Manufacturing (MEC4121)/MECH 4122- 7th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/7th Sem/Micro and Nano Manufacturing (MEC4121)/MECH 4122- 7th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/7th Sem/Micro and Nano Manufacturing (MEC4121)/MECH 4122- 7th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/8th Sem/Building Materials (CIVL4221)/CIVL 4181- 8th Sem 2020.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/8th Sem/Building Materials (CIVL4221)/CIVL 4221- 8th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/8th Sem/Building Materials (CIVL4221)/CIVL 4221- 8th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/8th Sem/Building Materials (CIVL4221)/CIVL 4221- 8th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/8th Sem/Gas Dynamics and Jet Propulsion (MECH4243)/MECH 4243- 8th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/8th Sem/Gas Dynamics and Jet Propulsion (MECH4243)/MECH 4243- 8th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/03. Mechanical Engineering/8th Sem/Gas Dynamics and Jet Propulsion (MECH4243)/MECH 4243- 8th Sem 2024.pdf
  README.md
Labels: enhancement, Advanced, SSOC S4

#408 Added PYQ for 7 subjects under sem5 Anna-University
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/EC3552-VLSI and Chip Design Question Papers/Lecture Notes/EC3552 VLSI and Chip Design Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/EC3552-VLSI and Chip Design Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/EC3552-VLSI and Chip Design Question Papers/PYQ/EC3552 VLSI and Chip Design Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/EC3552-VLSI and Chip Design Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/EC3552-VLSI and Chip Design Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/EE3501-Power System Analysis Question Papers/Lecture Notes/EE3501 Power System Analysis Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/EE3501-Power System Analysis Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/EE3501-Power System Analysis Question Papers/PYQ/EE3501 Power System Analysis Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/EE3501-Power System Analysis Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/EE3503-Control Systems Question Papers/Lecture Notes/EE3503 Control Systems Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/EE3503-Control Systems Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/EE3503-Control Systems Question Papers/PYQ/EE3503 Control Systems Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/EE3503-Control Systems Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/EE3591-Power Electronics Question Papers/Lecture Notes/EE3591 Power Electronics Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/EE3591-Power Electronics Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/EE3591-Power Electronics Question Papers/PYQ/EE3591 Power Electronics Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/EE3591-Power Electronics Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/ME3591-Design of Machine Elements Question Papers/Lecture Notes/ME3591 Design of Machine Elements Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/ME3591-Design of Machine Elements Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/ME3591-Design of Machine Elements Question Papers/PYQ/ME3591 Design of Machine Elements Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/ME3591-Design of Machine Elements Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/ME3591-Design of Machine Elements Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/ME3592-Metrology and Measurements Question Papers/Lecture Notes/ME3592 Metrology and Measurements Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/ME3592-Metrology and Measurements Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/ME3592-Metrology and Measurements Question Papers/PYQ/ME3592 Metrology and Measurements Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/ME3592-Metrology and Measurements Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/ME3592-Metrology and Measurements Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/MV3501-Marine Propulsion Question Papers/PYQ/MV3501 Marine Propulsion Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/MV3501-Marine Propulsion Question Papers/PYQ/Nov Dec 2023 Question Paper.pdf
Labels: enhancement, Advanced, SSOC S4

#405 Add the pyq of automobile engineering department of 4th semester
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-automotive-petrol-engine-2009.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-automotive-petrol-engine-2011.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-automotive-petrol-engines-2010.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-business-communication-2011.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-design-of-machine-elements-2009.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-design-of-machine-elements-2010.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-design-of-machine-elements-2011.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-design-of-machine-elements-2012.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-engineering-analysis-and-numerical-methods-2009.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-engineering-analysis-and-numerical-methods-2010.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-engineering-analysis-and-numerical-methods-2011.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-engineering-analysis-and-numerical-methods-2012.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-fluid-mechanics-and-hydraulic-machines-2012.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-fluid-mechanics-and-hydraulic-machines-2013.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-heat-transfer-and-combustion-2009.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-heat-transfer-and-combustion-2011.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-heat-transfer-and-combustion-2012.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-mathematics-3-2012.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-mathematics-3-2013.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-measurement-and-instrumentation-2009.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-measurement-and-instrumentation-2010.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-measurement-and-instrumentation-2011.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-measurement-and-instrumentation-2012.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-mechanism-2013.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-mechanisms-2012.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-numerical-methods-2012.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-numerical-methods-2013.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-primary-manufacturing-process-2012.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-primary-manufacturing-processes-2013.pdf
  MAKAUT/4th Sem/AUE/btech-aue-4-sem-theory-of-machines-2009.pdf
Labels: enhancement, Advanced, SSOC S4

#410 Added PYQs for CLE2003, CLE2005, CLE1016, and CLE2004 – VIT Bhopal University / 06. Civil Engineering #400
  VIT Bhopal University/06.Civil Engineering/Transportation engineering(CLE2005 )/README.md
  VIT Bhopal University/06.Civil Engineering/Transportation engineering(CLE2005 )/Transportation engineering(CLE2005 ) (2).pdf
  VIT Bhopal University/06.Civil Engineering/Transportation engineering(CLE2005 )/Transportation engineering(CLE2005 ) (3).pdf
  VIT Bhopal University/06.Civil Engineering/Transportation engineering(CLE2005 )/Transportation engineering(CLE2005 ).pdf
  VIT Bhopal University/06.Civil Engineering/Urban planning(CLE1016 )/README.md
  VIT Bhopal University/06.Civil Engineering/Urban planning(CLE1016 )/Urban planning(may 2020)(CLE1016 ) (2).pdf
  VIT Bhopal University/06.Civil Engineering/Urban planning(CLE1016 )/Urban planning(may 2020)(CLE1016 ) (3).pdf
  VIT Bhopal University/06.Civil Engineering/Urban planning(CLE1016 )/Urban planning(may 2020)(CLE1016 ) (4).pdf
  VIT Bhopal University/06.Civil Engineering/Urban planning(CLE1016 )/Urban planning(may 2020)(CLE1016 ) (5).pdf
  VIT Bhopal University/06.Civil Engineering/Urban planning(CLE1016 )/Urban planning(may 2020)(CLE1016 ) (6).pdf
  VIT Bhopal University/06.Civil Engineering/Urban planning(CLE1016 )/Urban planning(may 2020)(CLE1016 ) (7).pdf
  VIT Bhopal University/06.Civil Engineering/Urban planning(CLE1016 )/Urban planning(may 2020)(CLE1016 ) (8).pdf
  VIT Bhopal University/06.Civil Engineering/Urban planning(CLE1016 )/Urban planning(may 2020)(CLE1016 ).pdf
  VIT Bhopal University/06.Civil Engineering/Water Resource management(CLE2004)/README.md
  VIT Bhopal University/06.Civil Engineering/Water Resource management(CLE2004)/Water Resource management(CLE2004)..pdf
  VIT Bhopal University/06.Civil Engineering/Water Resource management(CLE2004)/Water Resource management(CLE2004).pdf
  VIT Bhopal University/06.Civil Engineering/structural analysis(CLE2003 )/README.md
  VIT Bhopal University/06.Civil Engineering/structural analysis(CLE2003 )/structural analysis(CLE2003 ) (2).pdf
  VIT Bhopal University/06.Civil Engineering/structural analysis(CLE2003 )/structural analysis(CLE2003 ) (3).pdf
  VIT Bhopal University/06.Civil Engineering/structural analysis(CLE2003 )/structural analysis(CLE2003 ).pdf
Labels: enhancement, Intermediate, SSOC S4

#418 Added the pyq of automobile engineering department of 6th semester
  MAKAUT/6th Sem/AUE/btech-aue-6-sem-automotive-electrical-system-and-electronics-2009.pdf
  MAKAUT/6th Sem/AUE/btech-aue-6-sem-automotive-electrical-system-and-electronics-2010.pdf
  MAKAUT/6th Sem/AUE/btech-aue-6-sem-automotive-electrical-system-and-electronics-2013.pdf
  MAKAUT/6th Sem/AUE/btech-aue-6-sem-automotive-electrical-systems-and-electronics-2012.pdf
  MAKAUT/6th Sem/AUE/btech-aue-6-sem-automotive-petrol-and-diesel-engine-2013.pdf
  MAKAUT/6th Sem/AUE/btech-aue-6-sem-automotive-pollution-and-control-2011.pdf
  MAKAUT/6th Sem/AUE/btech-aue-6-sem-automotive-pollution-and-control-2012.pdf
  MAKAUT/6th Sem/AUE/btech-aue-6-sem-automotive-pollution-control-2010.pdf
  MAKAUT/6th Sem/AUE/btech-aue-6-sem-design-of-automotive-system-2013.pdf
  MAKAUT/6th Sem/AUE/btech-aue-6-sem-metrology-and-measurement-2013.pdf
  MAKAUT/6th Sem/AUE/btech-aue-6-sem-power-units-and-transmission-2013.pdf
  MAKAUT/6th Sem/AUE/btech-aue-6-sem-production-management-and-operation-research-2013.pdf
  MAKAUT/6th Sem/AUE/btech-aue-6-sem-quality-control-and-reliability-engineering-2011.pdf
  MAKAUT/6th Sem/AUE/btech-aue-6-sem-quality-control-and-reliability-engineering-2012.pdf
  MAKAUT/6th Sem/AUE/btech-aue-6-sem-two-and-three-wheeler-2009.pdf
  MAKAUT/6th Sem/AUE/btech-aue-6-sem-two-and-three-wheeler-2012.pdf
  MAKAUT/6th Sem/AUE/btech-aue-6-sem-vehicle-body-engineering-2009.pdf
  MAKAUT/6th Sem/AUE/btech-aue-6-sem-vehicle-body-engineering-2012.pdf
  MAKAUT/6th Sem/AUE/btech-aue-6-sem-vehicle-body-engineering-2013.pdf
  MAKAUT/6th Sem/AUE/btech-aue-601-automotive-petrol-and-diesel-engine-2013.pdf
  MAKAUT/6th Sem/AUE/btech-aue-601-automotive-petrol-and-diesel-engine-2015.pdf
  MAKAUT/6th Sem/AUE/btech-aue-601-automotive-petrol-and-diesel-engine-2016.pdf
  MAKAUT/6th Sem/AUE/btech-aue-601-automotive-petrol-and-diesel-engines-2014.pdf
  MAKAUT/6th Sem/AUE/btech-aue-602-power-unit-and-transmission-2014.pdf
  MAKAUT/6th Sem/AUE/btech-aue-602-power-unit-and-transmission-2015.pdf
  MAKAUT/6th Sem/AUE/btech-aue-602-power-unit-and-transmission-2016.pdf
  MAKAUT/6th Sem/AUE/btech-aue-602-power-units-and-transmission-2013.pdf
  MAKAUT/6th Sem/AUE/btech-aue-603-metrology-and-measurement-2013.pdf
  MAKAUT/6th Sem/AUE/btech-aue-603-metrology-and-measurement-2014.pdf
  MAKAUT/6th Sem/AUE/btech-aue-603-metrology-and-measurement-2015.pdf
  MAKAUT/6th Sem/AUE/btech-aue-603-metrology-and-measurement-2016.pdf
  MAKAUT/6th Sem/AUE/btech-aue-604a-vehicle-body-engineering-2013.pdf
  MAKAUT/6th Sem/AUE/btech-aue-604a-vehicle-body-engineering-2014.pdf
  MAKAUT/6th Sem/AUE/btech-aue-604a-vehicle-body-engineering-2016.pdf
  MAKAUT/6th Sem/AUE/btech-aue-605a-design-of-automotive-system-2016.pdf
  MAKAUT/6th Sem/AUE/btech-aue-605a-design-of-automotive-systems-2014.pdf
  MAKAUT/6th Sem/AUE/btech-aue-605a-design-of-automotive-systems-2015.pdf
  MAKAUT/6th Sem/AUE/btech-aue-606-hu-production-management-and-operation-research-2016.pdf
  MAKAUT/6th Sem/AUE/btech-aue-606-production-management-and-operation-research-2013.pdf
  MAKAUT/6th Sem/AUE/btech-aue-606hu-production-management-and-operation-research-2016.pdf
  MAKAUT/6th Sem/AUE/btech-aue-606hu-production-management-and-operations-2014.pdf
  MAKAUT/6th Sem/FT/btech-ft-6-sem-process-instrumentation-and-control-2009.pdf
Labels: enhancement, Advanced, SSOC S4

#420 Created README.md for Civil Engineering Subjects – VIT Bhopal University / 06. Civil Engineering #411
  VIT Bhopal University/06.Civil Engineering/README.md
Labels: enhancement, Advanced, SSOC S4

#427 Added PYQs for AIML 2nd and 3rd Sems
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/CE3501-Design of Reinforced Concrete Structural Elements Question Papers/Lecture Notes/CE3501 Design of Reinforced Concrete Structural Elements Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 1/CE3501-Design of Reinforced Concrete Structural Elements Question Papers/PYQ/CE3501 Design of Reinforced Concrete Structural Elements Question Papers.pdf
  NIT_Kurukshetra/AI_ML/2nd Sem/Data Structures(AIPC 100)/AIPC12 ES 2018.pdf
  NIT_Kurukshetra/AI_ML/2nd Sem/Data Structures(AIPC 100)/AIPC12 ES 2019.pdf
  NIT_Kurukshetra/AI_ML/2nd Sem/Data Structures(AIPC 100)/AIPC12 ES 2021.pdf
  NIT_Kurukshetra/AI_ML/2nd Sem/Data Structures(AIPC 100)/AIPC12 ES1 2018.pdf
  NIT_Kurukshetra/AI_ML/2nd Sem/Data Structures(AIPC 100)/AIPC12 ES1 2019.pdf
  NIT_Kurukshetra/AI_ML/2nd Sem/Data Structures(AIPC 100)/AIPC12 ES2 2019.pdf
  NIT_Kurukshetra/AI_ML/2nd Sem/Data Structures(AIPC 100)/AIPC12 ES3 2019.pdf
  NIT_Kurukshetra/AI_ML/2nd Sem/Data Structures(AIPC 100)/AIPC12 MS 2021.pdf
  NIT_Kurukshetra/AI_ML/2nd Sem/Data Structures(AIPC 100)/AIPC12 MS 2022.pdf
  NIT_Kurukshetra/AI_ML/2nd Sem/Data Structures(AIPC 100)/AIPC12 MS1 2021.pdf
  NIT_Kurukshetra/AI_ML/2nd Sem/Data Structures(AIPC 100)/AIPC12 MS1 2025.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Design and Analysis of Algorithms(AIPC 203)/AIPC21 ES 2018.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Design and Analysis of Algorithms(AIPC 203)/AIPC21 ES 2019.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Design and Analysis of Algorithms(AIPC 203)/AIPC21 ES 2020.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Design and Analysis of Algorithms(AIPC 203)/AIPC21 ES 2021.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Design and Analysis of Algorithms(AIPC 203)/AIPC21 ES1 2018.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Design and Analysis of Algorithms(AIPC 203)/AIPC21 ES1 2019.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Design and Analysis of Algorithms(AIPC 203)/AIPC21 ES1 2020.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Design and Analysis of Algorithms(AIPC 203)/AIPC21 ES1 2021.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Design and Analysis of Algorithms(AIPC 203)/AIPC21 MS 2021.pdf
  NIT_Kurukshetra/AI_ML/3rd Sem/Design and Analysis of Algorithms(AIPC 203)/AIPC21 MS1 2021.pdf
  README.md
Labels: enhancement, Intermediate, SSOC S4

#428 Added PYQs for Biotechnology and Biomedical Engineering Subjects – VIT Bhopal University / 07. Biotechnology Biomedical Engineering #423
  VIT Bhopal University/07.Biotechnology  Biomedical Engineering/Analytical Bioinformatics(BIT2001)/Analytical Bioinformatics(BIT2001).pdf
  VIT Bhopal University/07.Biotechnology  Biomedical Engineering/Analytical Bioinformatics(BIT2001)/README.md
  VIT Bhopal University/07.Biotechnology  Biomedical Engineering/Biometric systems(SWE1015)/Biometric systems(DEC 2025)(SWE1015).pdf
  VIT Bhopal University/07.Biotechnology  Biomedical Engineering/Biometric systems(SWE1015)/README.md
  VIT Bhopal University/07.Biotechnology  Biomedical Engineering/Introduction to Nanoscience and Nanotechnology(ECE1006 )/Introduction to Nanoscience and Nanotechnology(DEC 2019)(ECE1006 ) (1).pdf
  VIT Bhopal University/07.Biotechnology  Biomedical Engineering/Introduction to Nanoscience and Nanotechnology(ECE1006 )/Introduction to Nanoscience and Nanotechnology(DEC 2019)(ECE1006 ) (2).pdf
  VIT Bhopal University/07.Biotechnology  Biomedical Engineering/Introduction to Nanoscience and Nanotechnology(ECE1006 )/Introduction to Nanoscience and Nanotechnology(DEC 2019)(ECE1006 ) (3).pdf
  VIT Bhopal University/07.Biotechnology  Biomedical Engineering/Introduction to Nanoscience and Nanotechnology(ECE1006 )/Introduction to Nanoscience and Nanotechnology(DEC 2019)(ECE1006 ) (4).pdf
  VIT Bhopal University/07.Biotechnology  Biomedical Engineering/Introduction to Nanoscience and Nanotechnology(ECE1006 )/Introduction to Nanoscience and Nanotechnology(DEC 2019)(ECE1006 ) (5).pdf
  VIT Bhopal University/07.Biotechnology  Biomedical Engineering/Introduction to Nanoscience and Nanotechnology(ECE1006 )/Introduction to Nanoscience and Nanotechnology(DEC 2019)(ECE1006 ) (7).pdf
  VIT Bhopal University/07.Biotechnology  Biomedical Engineering/Introduction to Nanoscience and Nanotechnology(ECE1006 )/Introduction to Nanoscience and Nanotechnology(DEC 2019)(ECE1006 ) 1.pdf
  VIT Bhopal University/07.Biotechnology  Biomedical Engineering/Introduction to Nanoscience and Nanotechnology(ECE1006 )/Introduction to Nanoscience and Nanotechnology(DEC 2019)(ECE1006 ) 10.pdf
  VIT Bhopal University/07.Biotechnology  Biomedical Engineering/Introduction to Nanoscience and Nanotechnology(ECE1006 )/Introduction to Nanoscience and Nanotechnology(DEC 2019)(ECE1006 ) 2.pdf
  VIT Bhopal University/07.Biotechnology  Biomedical Engineering/Introduction to Nanoscience and Nanotechnology(ECE1006 )/Introduction to Nanoscience and Nanotechnology(DEC 2019)(ECE1006 ) 8.pdf
  VIT Bhopal University/07.Biotechnology  Biomedical Engineering/Introduction to Nanoscience and Nanotechnology(ECE1006 )/Introduction to Nanoscience and Nanotechnology(DEC 2019)(ECE1006 ) 9.pdf
  VIT Bhopal University/07.Biotechnology  Biomedical Engineering/Introduction to Nanoscience and Nanotechnology(ECE1006 )/Introduction to Nanoscience and Nanotechnology(DEC 2019)(ECE1006 )..pdf
  VIT Bhopal University/07.Biotechnology  Biomedical Engineering/Introduction to Nanoscience and Nanotechnology(ECE1006 )/Introduction to Nanoscience and Nanotechnology(DEC 2019)(ECE1006 ).pdf
  VIT Bhopal University/07.Biotechnology  Biomedical Engineering/Introduction to Nanoscience and Nanotechnology(ECE1006 )/README.md
Labels: enhancement, Advanced, SSOC S4

#436 Added the pyq of chemical engineering department of 2nd and 1st semester
  MAKAUT/1st Sem/CT/btech-1-sem-basic-electrical-engineering-es-ee-101-2019.pdf
  MAKAUT/1st Sem/CT/btech-1-sem-basic-electrical-engineering-esee101-2023.pdf
  MAKAUT/1st Sem/CT/btech-1-sem-chemistry-1-bs-ch101-2024.pdf
  MAKAUT/1st Sem/CT/btech-1-sem-chemistry-1-bsch101-2023.pdf
  MAKAUT/1st Sem/CT/btech-1-sem-mathematics-1a-bs-m101-2025.pdf
  MAKAUT/1st Sem/CT/btech-1-sem-mathematics-1a-bsm-101-2020.pdf
  MAKAUT/1st Sem/CT/btech-1-sem-mathematics-1a-bsm101-2023.pdf
  MAKAUT/1st Sem/CT/btech-1-sem-mathematics-1b-bsm102-2023.pdf
  MAKAUT/1st Sem/CT/btech-1-sem-physics-1-bs-ph101-2025.pdf
  MAKAUT/1st Sem/CT/btech-1-sem-physics-1-bsph101-2023.pdf
  MAKAUT/1st Sem/CT/btech-1-sem-physics-1-ph-101-2020.pdf
  MAKAUT/1st Sem/CT/btech-es-cs-2-sem-programming-for-problem-solving-escs201-2024.pdf
  MAKAUT/1st Sem/CT/btech-hm-hu-201n-english-2019.pdf
  MAKAUT/2nd Sem/CT/btech-2-sem-basic-electrical-engineering-es-ee101-2024.pdf
  MAKAUT/2nd Sem/CT/btech-2-sem-chemistry-1-bsch201-2023.pdf
  MAKAUT/2nd Sem/CT/btech-2-sem-chemistry-1-bsch201-2024.pdf
  MAKAUT/2nd Sem/CT/btech-2-sem-chemistry-bsch201-2025.pdf
  MAKAUT/2nd Sem/CT/btech-2-sem-english-hmhu201-2023.pdf
  MAKAUT/2nd Sem/CT/btech-2-sem-english-hmhu201-2024.pdf
  MAKAUT/2nd Sem/CT/btech-2-sem-mathematics-2-b-bsm202-2023.pdf
  MAKAUT/2nd Sem/CT/btech-2-sem-mathematics-2a-bsm-201n-2019.pdf
  MAKAUT/2nd Sem/CT/btech-2-sem-mathematics-2a-bsm201-2023.pdf
  MAKAUT/2nd Sem/CT/btech-2-sem-mathematics-2a-bsm201-2024.pdf
  MAKAUT/2nd Sem/CT/btech-2-sem-physics-1-bsph201-2024.pdf
Labels: enhancement, Intermediate, SSOC S4

#440 Added the pyq of chemical engineering department of 3rd semester
  MAKAUT/3rd Sem/CHE/btech-ch(che)-301-basic-environmental-engg-and-elementary-biology-2018.pdf
  MAKAUT/3rd Sem/CHE/btech-ch-301-basic-environmental-engg-and-elementary-biology-2018.pdf
  MAKAUT/3rd Sem/CHE/btech-ch-301-basic-environmental-engineering-and-elementary-biology-2011.pdf
  MAKAUT/3rd Sem/CHE/btech-ch-301-basic-environmental-engineering-and-elementary-biology-2012.pdf
  MAKAUT/3rd Sem/CHE/btech-ch-301-basic-environmental-engineering-and-elementary-biology-2014.pdf
  MAKAUT/3rd Sem/CHE/btech-ch-301-basic-environmental-engineering-and-elementary-biology-2015.pdf
  MAKAUT/3rd Sem/CHE/btech-ch-301-basic-environmental-engineering-and-elementary-biology-2016.pdf
  MAKAUT/3rd Sem/CHE/btech-ch-301-basic-environmental-engineering-and-elementary-biology-2017.pdf
  MAKAUT/3rd Sem/CHE/btech-ch-301-basic-environmental-engineering-and-elementary-biology-2019.pdf
  MAKAUT/3rd Sem/CHE/btech-ch-302-chemistry-2-2012.pdf
  MAKAUT/3rd Sem/CHE/btech-che-3-sem-basic-environmental-engg.-and-elementary-biology-2011.pdf
  MAKAUT/3rd Sem/CHE/btech-che-3-sem-basic-environmental-engineering-and-elementary-biology-2012.pdf
  MAKAUT/3rd Sem/CHE/btech-che-3-sem-chemistry-2-2011.pdf
  MAKAUT/3rd Sem/CHE/btech-che-3-sem-chemistry-2-2012.pdf
  MAKAUT/3rd Sem/CHE/btech-che-3-sem-chemistry-2012.pdf
  MAKAUT/3rd Sem/CHE/btech-che-3-sem-data-structure-and-database-concepts-2010.pdf
  MAKAUT/3rd Sem/CHE/btech-che-3-sem-data-structure-and-database-concepts-2011.pdf
  MAKAUT/3rd Sem/CHE/btech-che-3-sem-data-structure-and-database-concepts-2012.pdf
  MAKAUT/3rd Sem/CHE/btech-che-3-sem-electrical-machines-2011.pdf
  MAKAUT/3rd Sem/CHE/btech-che-3-sem-electrical-machines-2012.pdf
  MAKAUT/3rd Sem/CHE/btech-che-3-sem-energy-technology-2012.pdf
  MAKAUT/3rd Sem/CHE/btech-che-3-sem-fluid-mechanics-2012.pdf
  MAKAUT/3rd Sem/CHE/btech-che-3-sem-industrial-stoichiometry-2011.pdf
  MAKAUT/3rd Sem/CHE/btech-che-3-sem-industrial-stoichiometry-2012.pdf
  MAKAUT/3rd Sem/CHE/btech-che-3-sem-mathematics-2011.pdf
  MAKAUT/3rd Sem/CHE/btech-che-3-sem-mathematics-3-2012.pdf
  MAKAUT/3rd Sem/CHE/btech-che-3-sem-values-and-ethics-in-profession-2012.pdf
  MAKAUT/3rd Sem/CHE/btech-che-301-basic-environmental-engineering-and-elementary-biology-2018.pdf
  MAKAUT/3rd Sem/CHE/btech-che-301-fluid-mechanics-2012.pdf
  MAKAUT/3rd Sem/CHE/btech-che-301-fluid-mechanics-2018.pdf
  MAKAUT/3rd Sem/CHE/btech-che-301-industrial-stoichiometry-2012.pdf
  MAKAUT/3rd Sem/CHE/btech-che-302-chemistry-2-2018.pdf
  MAKAUT/3rd Sem/CHE/btech-che-302-industrial-stoichiometry-2011.pdf
  MAKAUT/3rd Sem/CHE/btech-che-302-industrial-stoichiometry-2018.pdf
Labels: enhancement, Intermediate, SSOC S4

#448 Added PYQ for 5 subjects Anna University
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/AG3601-Engineering Geology Question Papers/PYQ/AG3601 Engineering Geology Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/AG3601-Engineering Geology Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/AI3404-Hydrology and Water Resources Engineering Question Papers/PYQ/AI3404 Hydrology and Water Resources Engineering Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/AI3404-Hydrology and Water Resources Engineering Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/CCS356-Object Oriented Software Engineering Question Papers/Lecture Notes/CCS356 Object Oriented Software Engineering Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/CCS356-Object Oriented Software Engineering Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/CCS356-Object Oriented Software Engineering Question Papers/PYQ/CCS356 Object Oriented Software Engineering Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/CE3601-Design of Steel Structural Elements Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/CE3601-Design of Steel Structural Elements Question Papers/PYQ/CE3601 Design of Steel Structural Elements Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/CE3602-Structural Analysis II Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/CE3602-Structural Analysis II Question Papers/PYQ/CE3602 Structural Analysis II Question Papers.pdf
Labels: enhancement, Beginner, SSOC S4

#449 Added MNC Sem 3 and Sem 4 PYQs
  ABV-IIITM Gwalior/MNC/Sem3/DAA/daa_minors.pdf
  ABV-IIITM Gwalior/MNC/Sem3/DS/dsminor'23.pdf
  ABV-IIITM Gwalior/MNC/Sem3/ICEMV/icemv_minor.pdf
  ABV-IIITM Gwalior/MNC/Sem4/ANM/anm_major.pdf
  ABV-IIITM Gwalior/MNC/Sem4/E&I/E&I_minor.pdf
  ABV-IIITM Gwalior/MNC/Sem4/M&I/M&I_minor.pdf
  ABV-IIITM Gwalior/MNC/Sem4/MDA/mda_major.pdf
  ABV-IIITM Gwalior/MNC/Sem4/OS/OS_minor.pdf
  ABV-IIITM Gwalior/MNC/Sem4/SE/SE_minor.pdf
  ABV-IIITM Gwalior/MNC/Sem4/SE/se_major.pdf
Labels: enhancement, Beginner, SSOC S4

#446 Added Central README for VIT Bhopal University Directory – #434
  VIT Bhopal University/README.md
Labels: enhancement, Advanced, SSOC S4

#451 Added Core Subjects under VIT Bhopal University/08. Automobile Automotive Engineering/ #447
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Aerodynamics(MEE2028)/Automative Aerodynamics(dec 2020)(MEE2028).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Aerodynamics(MEE2028)/README.md
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Chassis(MEE1036 )/Automative Chassis(dec 2019)(MEE1036 ).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Chassis(MEE1036 )/Automative Chassis(dec 2020)(MEE1036 ) (2).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Chassis(MEE1036 )/Automative Chassis(dec 2020)(MEE1036 ) (3).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Chassis(MEE1036 )/Automative Chassis(dec 2020)(MEE1036 ) (4).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Chassis(MEE1036 )/Automative Chassis(dec 2020)(MEE1036 ) (5).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Chassis(MEE1036 )/Automative Chassis(dec 2020)(MEE1036 ) (6).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Chassis(MEE1036 )/Automative Chassis(dec 2020)(MEE1036 ).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Chassis(MEE1036 )/README.md
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Electricals(MEE1035 )/Automative Electricals(dec 2020)(MEE1035 ) (2).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Electricals(MEE1035 )/Automative Electricals(dec 2020)(MEE1035 ) (3).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Electricals(MEE1035 )/Automative Electricals(dec 2020)(MEE1035 ) (4).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Electricals(MEE1035 )/Automative Electricals(dec 2020)(MEE1035 ) (5).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Electricals(MEE1035 )/Automative Electricals(dec 2020)(MEE1035 ) (6).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Electricals(MEE1035 )/Automative Electricals(dec 2020)(MEE1035 ).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Electricals(MEE1035 )/README.md
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Electronics(MEE1037)/Automative Electronics(dec 2020)(MEE1037) (2).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Electronics(MEE1037)/Automative Electronics(dec 2020)(MEE1037).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automative Electronics(MEE1037)/README.md
Labels: enhancement, Advanced, SSOC S4

#460 Added PYQ for sem6 Anna University
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/CS3691-Embedded Systems and IoT Question Papers/Lecture Notes/CS3691 Embedded Systems and IoT Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/CS3691-Embedded Systems and IoT Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/CS3691-Embedded Systems and IoT Question Papers/PYQ/CS3691 Embedded Systems and IoT Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/CS3691-Embedded Systems and IoT Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/EE3601-Protection and Switchgear Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/EE3601-Protection and Switchgear Question Papers/PYQ/EE3601 Protection and Switchgear Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/EE3602-Power System Operation and Control Question Papers/Lecture Notes/EE3602 Power System Operation and Control Lecture Notes.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/EE3602-Power System Operation and Control Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/EE3602-Power System Operation and Control Question Papers/PYQ/EE3602 Power System Operation and Control Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/ET3491-Embedded Systems and IOT Design Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/ET3491-Embedded Systems and IOT Design Question Papers/PYQ/ET3491 Embedded Systems and IOT Design Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/ET3491-Embedded Systems and IOT Design Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/ME3691-Heat and Mass Transfer Question Papers/PYQ/Apr May 2024 Question Paper.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/ME3691-Heat and Mass Transfer Question Papers/PYQ/ME3691 Heat and Mass Transfer Question Papers.pdf
  Anna-University/R2021/All Branches PYQ/Third Year/Semester 2/ME3691-Heat and Mass Transfer Question Papers/PYQ/Nov Dec 2024 Question Paper.pdf
Labels: enhancement, Beginner, SSOC S4

#461 Added Core Subjects under Automobile Automotive Engineering - #452
  VIT Bhopal University/07.Biotechnology  Biomedical Engineering/README.md
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automotive Braking Systems (MEE2046)/Automotive braking systems(MEE2046) (2).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automotive Braking Systems (MEE2046)/Automotive braking systems(MEE2046) (3).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automotive Braking Systems (MEE2046)/Automotive braking systems(MEE2046).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automotive Braking Systems (MEE2046)/README.md
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automotive Safety Systems (MEE1041)/Automotive Safety Systems(dec 2020)(MEE1041) (2).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automotive Safety Systems (MEE1041)/Automotive Safety Systems(dec 2020)(MEE1041) (3).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automotive Safety Systems (MEE1041)/Automotive Safety Systems(dec 2020)(MEE1041).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automotive Safety Systems (MEE1041)/README.md
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automotive Transmission Systems (MEE2039)/Automotive transmission systems(dec 2019)(MEE2039 ).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Automotive Transmission Systems (MEE2039)/README.md
  VIT Bhopal University/08.Automobile  Automotive Engineering/Internal Combustion Engines (MEE3004)/Internal Combustion Engines(MEE3004 ).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Internal Combustion Engines (MEE3004)/README.md
  VIT Bhopal University/08.Automobile  Automotive Engineering/Vehicle Inspection & Maintenance (MEE2043)/README.md
  VIT Bhopal University/08.Automobile  Automotive Engineering/Vehicle Inspection & Maintenance (MEE2043)/Vehicle Inspection & Maintenance(dec 2020)(MEE2043) (2).pdf
  VIT Bhopal University/08.Automobile  Automotive Engineering/Vehicle Inspection & Maintenance (MEE2043)/Vehicle Inspection & Maintenance(dec 2020)(MEE2043).pdf
Labels: enhancement, Advanced, SSOC S4

#470 Add 24 pyqs - IT Sem 1,2,3 Velammal College of Engineering and Technology
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/1st Sem/CY3151-Engineering-Chemistry-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/1st Sem/CY3151-Engineering-Chemistry-Jan-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/1st Sem/GE3151-Problem-Solving-and-Python-Programming-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/1st Sem/GE3151-Problem-Solving-and-Python-Programming-Jan-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/1st Sem/GE3152-Heritage-of-Tamils-Apr-May-2023-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/1st Sem/GE3152-Heritage-of-Tamils-Nov-Dec-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/1st Sem/HS3151-Professional-English-I-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/1st Sem/HS3151-Professional-English-I-Jan-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/1st Sem/MA3151-Martics-and-Calculus-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/1st Sem/MA3151-Matrices-and-Calculus-Jan-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/1st Sem/PH3151-Engineering-Physics-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/1st Sem/PH3151-Engineering-Physics-Jan-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/2nd Sem/BE3251-Basic-Electrical-and-Electronics-Engineering-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/2nd Sem/CS3251-Programming-in-C-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/2nd Sem/GE3251-Engineering-Graphics-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/2nd Sem/GE3252-Tamils-and-Technology-Apr-May-2023-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/2nd Sem/HS3251-Professional-English-II-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/2nd Sem/MA3251-Statistics-and-Numerical-Methods-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/2nd Sem/PH3256-Physics-for-Information-Science-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/3rd Sem/CD3291-Data-Structures-and-Algorithms-Nov-Dec-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/3rd Sem/CS3351-Digital-Principles-and-Computer-Organization-Nov-Dec-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/3rd Sem/CS3352-Foundations-of-Data-Science-Nov-Dec-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/3rd Sem/CS3391-Object-Oriented-Programming-Nov-Dec-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/IT (INFORMATION TECHNOLOGY)/3rd Sem/MA3354-Discrete-Mathematics-Nov-Dec-2022-Question-Paper-Download.pdf
Labels: enhancement, Advanced, SSOC S4

#472 Update the file structure
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-applied-mathematics-2010.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-applied-mathematics-2011.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-basic-environmental-engineering-and-elementary-biology-2011.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-basic-environmental-engineering-and-elementary-biology-2012.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-chemical-and-engineering-thermodynamics-2012.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-chemical-engineering-and-thermodynamics-2011.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-chemical-thermodynamics-and-kinetics-2009.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-chemistry-2-2011.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-chemistry-2-2012.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-earth-science-and-ceramic-raw-materials-2011.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-earth-sciences-and-ceramic-raw-materials-2012.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-geology-2009.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-geology-2010.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-geology-2011.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-introduction-to-ceramics-2009.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-introduction-to-ceramics-2010.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-introduction-to-ceramics-2011.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-solid-state-physics-and-chemistry-2009.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-unit-operation-1-2009.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-unit-operation-1-2011.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-unit-operation-1-2012.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-unit-operation-1-s3-2011.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-values-and-ethics-in-profession-2011.pdf
  MAKAUT/3rd Sem/CT/btech-ct-3-sem-values-and-ethics-in-profession-2012.pdf
Labels: enhancement, Advanced, SSOC S4

#473 Add 24 pyqs - EEE Sem 1,2,3 Velammal College of Engineering and Technology
  Velammal College of Engineering and Technology/EEE/1st Sem/CY3151-Engineering-Chemistry-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/1st Sem/CY3151-Engineering-Chemistry-Jan-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/1st Sem/GE3151-Problem-Solving-and-Python-Programming-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/1st Sem/GE3151-Problem-Solving-and-Python-Programming-Jan-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/1st Sem/GE3152-Heritage-of-Tamils-Nov-Dec-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/1st Sem/HS3151-Professional-English-I-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/1st Sem/HS3151-Professional-English-I-Jan-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/1st Sem/MA3151-Martics-and-Calculus-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/1st Sem/MA3151-Matrices-and-Calculus-Jan-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/1st Sem/PH3151-Engineering-Physics-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/1st Sem/PH3151-Engineering-Physics-Jan-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/2nd Sem/BE3255-Basic-Civil-and-Mechanical-Engineering-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/2nd Sem/BE3255-Basic-Civil-and-Mechanical-Engineering-Nov-Dec-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/2nd Sem/EE3251-Electric-Circuit-Analysis-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/2nd Sem/EE3251-Electric-Circuit-Analysis-Nov-Dec-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/2nd Sem/GE3251-Engineering-Graphics-Apr-May-2022-Question-Paper-1-Download.pdf
  Velammal College of Engineering and Technology/EEE/2nd Sem/GE3251-Engineering-Graphics-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/2nd Sem/GE3252-Tamils-and-Technology-Apr-May-2023-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/2nd Sem/GE3252-Tamils-and-Technology-Nov-Dec-2023-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/2nd Sem/HS3251-Professional-English-II-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/2nd Sem/HS3251-Professional-English-II-Nov-Dec-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/2nd Sem/MA3251-Statistics-and-Numerical-Methods-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/2nd Sem/MA3251-Statistics-and-Numerical-Methods-Nov-Dec-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/2nd Sem/PH3202-Physics-for-Electrical-Engineering-Apr-May-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/2nd Sem/PH3202-Physics-for-Electrical-Engineering-Nov-Dec-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/3rd Sem/CS3353-C-Programming-and-Data-Structures-Nov-Dec-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/3rd Sem/EC3301-Electron-Devices-and-Circuits-Nov-Dec-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/3rd Sem/EE3301-Electromagnetic-Fields-Nov-Dec-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/3rd Sem/EE3302-Digital-Logic-Circuits-Nov-Dec-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/3rd Sem/EE3303-Electrical-Machines-I-Nov-Dec-2022-Question-Paper-Download.pdf
  Velammal College of Engineering and Technology/EEE/3rd Sem/MA3303-Probability-and-Complex-Functions-Nov-Dec-2022-Question-Paper-Download.pdf
Labels: enhancement, Advanced, SSOC S4

#476 Added 24 PYQs for EE branch 3rd & 4th Sem of HITK
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/3rd Sem/Analog & Digital Electronics (ELE2102)/ELEC 2102- 3rd Sem 2020.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/3rd Sem/Analog & Digital Electronics (ELE2102)/ELEC 2102- 3rd Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/3rd Sem/Analog & Digital Electronics (ELE2102)/ELEC 2102- 3rd Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/3rd Sem/Analog & Digital Electronics (ELE2102)/ELEC 2102- 3rd Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/3rd Sem/Circuit Theory (ELE2101)/ELEC 2101- 3rd Sem 2020.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/3rd Sem/Circuit Theory (ELE2101)/ELEC 2101- 3rd Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/3rd Sem/Circuit Theory (ELE2101)/ELEC 2101- 3rd Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/3rd Sem/Circuit Theory (ELE2101)/ELEC 2101- 3rd Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/3rd Sem/Electrical & Electronic Measurements (ELE2103)/ELEC 2103- 3rd Sem 2020.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/3rd Sem/Electrical & Electronic Measurements (ELE2103)/ELEC 2103- 3rd Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/3rd Sem/Electrical & Electronic Measurements (ELE2103)/ELEC 2103- 3rd Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/3rd Sem/Electrical & Electronic Measurements (ELE2103)/ELEC 2103- 3rd Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/4th Sem/Basic Thermal Power Engineering (ELEC2203)/ELEC 2203- 4th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/4th Sem/Basic Thermal Power Engineering (ELEC2203)/ELEC 2203- 4th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/4th Sem/Basic Thermal Power Engineering (ELEC2203)/ELEC 2203- 4th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/4th Sem/Basic Thermal Power Engineering (ELEC2203)/ELEC 2203- 4th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/4th Sem/Electrical Machines- I (ELE2201)/ELEC 2201- 4th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/4th Sem/Electrical Machines- I (ELE2201)/ELEC 2201- 4th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/4th Sem/Electrical Machines- I (ELE2201)/ELEC 2201- 4th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/4th Sem/Electrical Machines- I (ELE2201)/ELEC 2201- 4th Sem(Backlog) 2021.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/4th Sem/Field Theory (ELEC2204)/ELEC 2204- 4th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/4th Sem/Field Theory (ELEC2204)/ELEC 2204- 4th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/4th Sem/Field Theory (ELEC2204)/ELEC 2204- 4th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/4th Sem/Field Theory (ELEC2204)/ELEC 2204- 4th Sem 2024.pdf
Labels: enhancement, Advanced, SSOC S4

#480 Added PYQs for Core IT Subjects – VIT Bhopal University (IT) [#477]
  VIT Bhopal University/09.Information Technology (IT)/Cloud Computing(SWE4002)/Cloud Computing(dec 2020)(SWE4002).pdf
  VIT Bhopal University/09.Information Technology (IT)/Cloud Computing(SWE4002)/README.md
  VIT Bhopal University/09.Information Technology (IT)/Cyber Security(CSE4003 )/Cyber Security(CSE4003 ) (2).pdf
  VIT Bhopal University/09.Information Technology (IT)/Cyber Security(CSE4003 )/Cyber Security(CSE4003 ) (3).pdf
  VIT Bhopal University/09.Information Technology (IT)/Cyber Security(CSE4003 )/Cyber Security(CSE4003 ).pdf
  VIT Bhopal University/09.Information Technology (IT)/Cyber Security(CSE4003 )/README.md
  VIT Bhopal University/09.Information Technology (IT)/Data Privacy(BCSE318L)/Data Privacy(dec 2020)(BCSE318L) (1).pdf
  VIT Bhopal University/09.Information Technology (IT)/Data Privacy(BCSE318L)/Data Privacy(dec 2020)(BCSE318L).pdf
  VIT Bhopal University/09.Information Technology (IT)/Data Privacy(BCSE318L)/README.md
  VIT Bhopal University/09.Information Technology (IT)/Software Configuration Management(SWE2021)/READM.md
  VIT Bhopal University/09.Information Technology (IT)/Software Configuration Management(SWE2021)/Software Configuration Management(DEC 2020)(SWE2021).pdf
  VIT Bhopal University/09.Information Technology (IT)/Web Mining(CSE3024)/README.md
  VIT Bhopal University/09.Information Technology (IT)/Web Mining(CSE3024)/Web Mining(DEC 2020)(CSE3024) (2).pdf
  VIT Bhopal University/09.Information Technology (IT)/Web Mining(CSE3024)/Web Mining(DEC 2020)(CSE3024).pdf
  VIT Bhopal University/README.md
Labels: enhancement, Intermediate, SSOC S4

#484 [#481] Added README.md for VIT Bhopal University\09. Information Technology (IT)
  VIT Bhopal University/09.Information Technology (IT)/README.md
Labels: enhancement, Advanced, SSOC S4

#486 Added all PYQs of Computer Engineering
  Nagpur_University(Computer_Engineering)/1sem/btech-1-sem-basic-calculus-and-differential-equations-12638-winter-2024.pdf
  Nagpur_University(Computer_Engineering)/1sem/btech-1-sem-communication-skills-12614-winter-2024.pdf
  Nagpur_University(Computer_Engineering)/1sem/btech-1-sem-digital-circuits-and-logic-design-12635-winter-2024.pdf
  Nagpur_University(Computer_Engineering)/1sem/btech-1-sem-engineering-graphics-1-3286-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/1sem/btech-1-sem-essentials-of-chemistry-12630-winter-2024.pdf
  Nagpur_University(Computer_Engineering)/1sem/btech-1-sem-programming-for-problem-solving-12636-winter-2024.pdf
  Nagpur_University(Computer_Engineering)/2sem/btech-2-sem-advanced-electrical-engineering-3291-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/2sem/btech-2-sem-applied-chemistry-2503-winter-2022.pdf
  Nagpur_University(Computer_Engineering)/2sem/btech-2-sem-applied-mathematics-2-3287-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/2sem/btech-2-sem-engineering-mechanics-3290-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/2sem/btech-2-sem-materials-chemistry-3289-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/3sem/btech-comp-eng-3-sem-concepts-in-computer-engineering-3334-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/3sem/btech-comp-eng-3-sem-digital-electronics-3333-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/3sem/btech-comp-eng-3-sem-introduction-to-computer-network-3336-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/3sem/btech-comp-engg-3-sem-digital-circuits-and-fundamentals-of-microprocessor-2536-winter-2022.pdf
  Nagpur_University(Computer_Engineering)/3sem/btech-comp-tech-comp-engg-it-3-sem-mathematics-3-2535-winter-2022.pdf
  Nagpur_University(Computer_Engineering)/3sem/btech-cse-comp-tech-comp-engg-it-3-sem-universal-human-values-2534-winter-2022.pdf
  Nagpur_University(Computer_Engineering)/4sem/btech-comp-eng-4-sem-file-structure-and-data-processing-3389-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/4sem/btech-comp-eng-4-sem-file-structure-and-data-processing-jun-2017.pdf
  Nagpur_University(Computer_Engineering)/4sem/btech-comp-eng-4-sem-microprocessor-jun-2017.pdf
  Nagpur_University(Computer_Engineering)/4sem/btech-comp-eng-4-sem-numerical-computational-techniques-3391-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/4sem/btech-comp-eng-4-sem-object-oriented-methodology-3392-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/4sem/btech-cse-comp-tech-comp-engg-it-4-sem-discrete-mathematics-and-graph-2582-summer-2023.pdf
  Nagpur_University(Computer_Engineering)/5sem/btech-comp-eng-5-sem-computer-architecture-and-organization-3445-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/5sem/btech-comp-eng-5-sem-computer-architecture-and-organization-jun-2017.pdf
  Nagpur_University(Computer_Engineering)/5sem/btech-comp-eng-5-sem-computer-graphics-3447-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/5sem/btech-comp-eng-5-sem-industrial-economics-and-entrepreneurship-development-winter-2016.pdf
  Nagpur_University(Computer_Engineering)/5sem/btech-comp-eng-5-sem-tcp-ip-and-internet-3446-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/5sem/btech-comp-eng-5-sem-theory-of-computation-3444-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/6sem/btech-comp-eng-6-sem-database-management-systems-3502-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/6sem/btech-comp-eng-6-sem-design-and-analysis-of-algorithms-3501-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/6sem/btech-comp-eng-6-sem-functional-english-winter-2018.pdf
  Nagpur_University(Computer_Engineering)/6sem/btech-comp-eng-6-sem-software-engineering-and-project-management-3503-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/6sem/btech-comp-eng-6-sem-system-software-3500-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/7sem/btech-comp-eng-7-sem-compiler-construction-3597-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/7sem/btech-comp-eng-7-sem-data-warehousing-and-mining-3598-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/7sem/btech-comp-eng-7-sem-digital-signal-and-image-processing-3599-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/7sem/btech-comp-eng-7-sem-enterprise-resource-planning-3601-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/7sem/btech-comp-eng-7-sem-information-assurance-and-network-security-3595-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/7sem/btech-comp-eng-7-sem-operating-systems-3593-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/8sem/btech-comp-eng-8-sem-bio-informatics-and-cyber-security-3714-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/8sem/btech-comp-eng-8-sem-distributed-systems-and-grid-computing-3711-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/8sem/btech-comp-eng-8-sem-expert-system-design-3716-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/8sem/btech-comp-eng-8-sem-multimedia-system-3717-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/8sem/btech-comp-eng-8-sem-real-time-systems-3715-summer-2019.pdf
  Nagpur_University(Computer_Engineering)/8sem/btech-comp-eng-8-sem-wireless-communication-and-mobile-computing-3712-summer-2019.pdf
Labels: enhancement, Advanced, SSOC S4

#490 Uploaded 25+ PYQs for Calculus (MAT1011) – #489
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) (10).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) (11).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) (12).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) (13).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) (14).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) (15).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) (16).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) (17).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) (2).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) (3).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) (4).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) (5).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) (6).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) (7).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) (8).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) (9).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) 18.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) 19.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) 20.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) 21.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) 22.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) 23.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) 24.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) 25.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ) 26.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/Calculus (DEC 2019)(MAT1011 ).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Calculus (MAT1011 )/README.md
Labels: enhancement, Advanced, SSOC S4

#494 Uploaded 25+ PYQs for Engineering Chemistry (CHY1701) – #492
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 ) /README.md
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (1).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (10).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (11).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (12).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (13).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (14).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (15).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (16).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (17).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (18).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (19).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (2).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (20).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (21).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (25).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (26).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (3).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (4).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (5).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (6).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (7).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (8).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) (9).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701 ) 24.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701) 22.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Engineering Chemistry(CHY1701 )/Engineering Chemistry(CHY1701) 23.pdf
Labels: enhancement, Advanced, SSOC S4

#502 Uploaded 25 pyq of chemical engineering of 6th semester
  MAKAUT/Chemical Engineering/6th Semester/btech-che-6-sem-advanced-separation-process-2013.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-6-sem-catalysis-and-catalytic-reactor-design-2012.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-6-sem-chemical-engineering-thermodynamics-2013.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-6-sem-chemical-process-technology-2-2012.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-6-sem-chemical-process-technology-2-2013.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-6-sem-chemical-process-technology-2-s3-2013.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-6-sem-environmental-engineering-2013.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-6-sem-industrial-safety-and-hazard-analysis-2013.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-6-sem-instrumentation-and-process-control-2013.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-6-sem-numerical-methods-in-chemical-engineering-2012.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-6-sem-numerical-methods-in-chemical-engineering-2013.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-6-sem-petrochemical-technology-2013.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-6-sem-principles-of-management-2013.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-6-sem-project-engineering-2013.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-6-sem-separation-process-2-2013.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-6-sem-separation-processes-2-2012.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-6-sem-separation-processes-2-2013.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-601-separation-process-2-2013.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-601-separation-processes-2-2011.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-601-separation-processes-2-2012.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-602-chemical-engineering-thermodynamics-2013.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-602-chemical-process-technology-2-2011.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-602-chemical-process-technology-2-2012.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-603-chemical-process-technology-2-2013.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-604a-advanced-separation-process-2013.pdf
  MAKAUT/Chemical Engineering/6th Semester/btech-che-605a-environmental-engineering-2013.pdf
Labels: enhancement, Advanced, SSOC S4

#505 Add the pyq of ceramic technology of 1st semester
  MAKAUT/Cermaic Technology/1st Semester/btech-1-sem-chemistry-1-bs-ch-101-2019.pdf
  MAKAUT/Cermaic Technology/1st Semester/btech-1-sem-mathematics-1-m-101-2017.pdf
  MAKAUT/Cermaic Technology/1st Semester/btech-1-sem-mathematics-1b-bs-m-102-2019.pdf
  MAKAUT/Cermaic Technology/1st Semester/btech-1-sem-mathematics-1b-bs-m-102-2020.pdf
  MAKAUT/Cermaic Technology/1st Semester/btech-1-sem-physics-1-bs-ph-101-2019.pdf
  MAKAUT/Cermaic Technology/1st Semester/btech-1-sem-physics-1-ph-101-2017.pdf
  MAKAUT/Cermaic Technology/1st Semester/btech-1-sem-physics-2-ph-301-2020.pdf
  MAKAUT/Cermaic Technology/1st Semester/btech-es-101-basic-electrical-and-electronic-engineering-1-2019.pdf
  MAKAUT/Cermaic Technology/1st Semester/btech-es-101-basic-electrical-and-electronic-engineering-1-v2-2019.pdf
  MAKAUT/Cermaic Technology/1st Semester/btech-es-101-basic-electrical-and-electronics-engineering-1-2016.pdf
  MAKAUT/Cermaic Technology/1st Semester/btech-es-101-basic-electrical-and-electronics-engineering-1-2017.pdf
  MAKAUT/Cermaic Technology/1st Semester/btech-hu-101-english-language-and-communication-2017.pdf
  MAKAUT/Cermaic Technology/1st Semester/btech-me-1-sem-engineering-mechanics-me-101-2017.pdf
  MAKAUT/Cermaic Technology/1st Semester/btech-me-1-sem-engineering-mechanics-me-101-2018.pdf
Labels: enhancement, Beginner, SSOC S4

#513 Adding Uttrakhand Technical University Master Of Technology in CSE branch PYQ
  UTU MTECH CSE/CSE/SEM 1/AHT 301.pdf
  UTU MTECH CSE/CSE/SEM 1/AHT 302.pdf
  UTU MTECH CSE/CSE/SEM 1/CST 30.pdf
  UTU MTECH CSE/CSE/SEM 1/CST 302.pdf
  UTU MTECH CSE/CSE/SEM 1/CST 303.pdf
  UTU MTECH CSE/CSE/SEM 1/CST 304.pdf
  UTU MTECH CSE/CSE/SEM 1/CST 306.pdf
  UTU MTECH CSE/CSE/SEM 1/CST 307.pdf
  UTU MTECH CSE/CSE/SEM 1/CST 308.pdf
  UTU MTECH CSE/CSE/SEM 1/CST 309.pdf
  UTU MTECH CSE/CSE/SEM 1/CST 310.pdf
  UTU MTECH CSE/CSE/SEM 2/CST 311.pdf
  UTU MTECH CSE/CSE/SEM 2/CST 312.pdf
  UTU MTECH CSE/CSE/SEM 2/CST 313.pdf
  UTU MTECH CSE/CSE/SEM 2/CST 316.pdf
  UTU MTECH CSE/CSE/SEM 2/CST 317.pdf
  UTU MTECH CSE/CSE/SEM 2/CST 319.pdf
  UTU MTECH CSE/CSE/SEM 2/CST 320.pdf
  UTU MTECH CSE/CSE/SEM 2/CST 321.pdf
  UTU MTECH CSE/CSE/SEM 2/CST 322.pdf
  UTU MTECH CSE/CSE/SEM 2/CST 323.pdf
  UTU MTECH CSE/CSE/SEM 2/MCST 201.pdf
  UTU MTECH CSE/CSE/SEM 2/MCST 202.pdf
  UTU MTECH CSE/CSE/SEM 2/MCST 321.pdf
  UTU MTECH CSE/CSE/SEM 2/OET 301.pdf
  UTU MTECH CSE/CSE/SEM 3/CST 325.pdf
  UTU MTECH CSE/CSE/SEM 3/CST 326.pdf
  UTU MTECH CSE/CSE/SEM 3/CST 327.pdf
  UTU MTECH CSE/CSE/SEM 3/CST 328.pdf
  UTU MTECH CSE/CSE/SEM 3/CST 329.pdf
  UTU MTECH CSE/CSE/SEM 3/MCST 329.pdf
Labels: good first issue, Beginner, SSOC S4

#509 Added Syllabus of CE, ME, ECE, IT branches.
  PSIT_Kanpur/02. Information Technology/IT_Syllabus.pdf
  PSIT_Kanpur/03. ECE/ECE_Syllabus.pdf
  PSIT_Kanpur/04. Mechanical Engineering/ME_Syllabus.pdf
  PSIT_Kanpur/05. Civil Engineering/CE_Syllabus.pdf
Labels: good first issue, Intermediate, SSOC S4

#510 Added 30 PYQ's of JNTU College
  JNTU Hyderabad/Sem-I/CSE/Basic Electrical Engineering.pdf
  JNTU Hyderabad/Sem-I/CSE/Chemistry.pdf
  JNTU Hyderabad/Sem-I/CSE/English.pdf.pdf
  JNTU Hyderabad/Sem-I/CSE/Mathematics-I.pdf
  JNTU Hyderabad/Sem-I/ECE/Applied Physics.pdf
  JNTU Hyderabad/Sem-I/ECE/Engineering Graphics.pdf
  JNTU Hyderabad/Sem-I/ECE/Mathematics-I.pdf
  JNTU Hyderabad/Sem-I/ECE/Programming For Problem Solving.pdf
  JNTU Hyderabad/Sem-I/ME/Computer Programming in C.pdf
  JNTU Hyderabad/Sem-I/ME/Engineering Graphics.pdf
  JNTU Hyderabad/Sem-I/ME/Engineering Physics.pdf
  JNTU Hyderabad/Sem-I/ME/Mathematics-I.pdf
  JNTU Hyderabad/Sem-I/ME/Programming For Problem Solving.pdf
  JNTU Hyderabad/Sem-II/CSE/Applied Physics-II.pdf
  JNTU Hyderabad/Sem-II/CSE/Basic Electrical Engneerring-II.pdf
  JNTU Hyderabad/Sem-II/CSE/Chemistry-II.pdf
  JNTU Hyderabad/Sem-II/CSE/Engneering Graphics-II.pdf
  JNTU Hyderabad/Sem-II/CSE/Mathematics-II.pdf
  JNTU Hyderabad/Sem-II/CSE/Programming For Problem Solving-II.pdf
  JNTU Hyderabad/Sem-II/ECE/Applied Physics -II.pdf
  JNTU Hyderabad/Sem-II/ECE/Basic Electrical Engineering -II.pdf
  JNTU Hyderabad/Sem-II/ECE/Chemistry - II.pdf
  JNTU Hyderabad/Sem-II/ECE/Engineering Graphics -II.pdf
  JNTU Hyderabad/Sem-II/ECE/English - II.pdf
  JNTU Hyderabad/Sem-II/ECE/Mathematics -II.pdf
  JNTU Hyderabad/Sem-II/ECE/Programming For Problem Solving -II.pdf
  JNTU Hyderabad/Sem-II/ME/Chemistry - II.pdf
  JNTU Hyderabad/Sem-II/ME/Engineering Mechanics-II.pdf
  JNTU Hyderabad/Sem-II/ME/English - II.pdf
  JNTU Hyderabad/Sem-II/ME/Mathematics-II.pdf
Labels: enhancement, Advanced, SSOC S4

#520 Add the pyq of computer science engineering department of 5th semester
  MAKAUT/Computer Science Engineering/5th semester/btech-cse-5-sem-artificial-intelligence-pec-csbs-501-b-2024.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-cse-5-sem-compiler-design-pcc-cs501-2024.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-cse-5-sem-compiler-design-pcc-cs501-2025.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-cse-5-sem-database-management-system-2014.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-cse-5-sem-design-and-analysis-of-algorithms-2017.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-cse-5-sem-discrete-mathematics-2015.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-cse-5-sem-introducon-to-industrial-management-humanities-3-hsmc-501-2024.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-cse-5-sem-introduction-to-industrial-management-humanities-3-hsmc-501-2025.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-cse-5-sem-microprocessor-and-microcontroller-2014.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-cse-5-sem-microprocessor-and-microcontroller-2016.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-cse-5-sem-microprocessor-and-microcontroller-2017.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-cse-5-sem-microprocessor-and-microcontroller-v2-2013.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-cse-5-sem-object-oriented-programming-2017.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-cse-5-sem-object-oriented-programming-pcc-cs503-2024.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-cse-5-sem-object-oriented-programming-pcc-cs503-2025.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-cse-5-sem-operating-systems-pcc-cs502-2024.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-cse-5-sem-operating-systems-pcc-cs502-2025.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-cse-5-sem-software-engineering-esc501-2025.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-ds-cse-it-5-sem-theory-of-computation-pec-ds-501a-2025.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-esc-5-sem-software-engineering-esc501-2023.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-hsmc-5-sem-introduction-to-industrial-management-hsmc-501-2023.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-pcc-cse-5-sem-compiler-design-pcc-cs501-2023.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-pcc-cse-5-sem-object-oriented-programming-pcc-cs503-2023.pdf
  MAKAUT/Computer Science Engineering/5th semester/btech-pcc-cse-5-sem-operating-systems-pcc-cs502-2023.pdf
Labels: enhancement, Advanced, SSOC S4

#519 Uploaded 25+ PYQs for Linear Algebra (MAT3008) – #518
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (10).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (11).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (12).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (13).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (14).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (15).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (16).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (17).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (18).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (19).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (2).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (20).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (21).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (22).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (23).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (24).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (3).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (4).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (5).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (6).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (7).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (8).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ) (9).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/LINEAR ALGEBRA (dec 2020)(MAT3008 ).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/Linear Algebra (MAT3008) - 1.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/Linear Algebra (MAT3008) - 2.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/Linear Algebra (MAT3008) - 3.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/Linear Algebra (MAT3008) - 4.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/LINEAR ALGEBRA (MAT3008 )/README.md
Labels: enhancement, Advanced, SSOC S4

#523 Add the pyq of instrumentation and control engineering of 2nd semester
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-2-sem-basic-electrical-engineering-es-ee101-2024.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-2-sem-chemistry-1-bsch201-2023.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-2-sem-chemistry-1-bsch201-2024.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-2-sem-chemistry-bsch201-2025.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-2-sem-english-hmhu201-2023.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-2-sem-english-hmhu201-2024.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-2-sem-mathematics-2-b-bsm202-2023.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-2-sem-mathematics-2a-bsm201-2023.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-2-sem-mathematics-2a-bsm201-2024.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-2-sem-physics-1-bsph201-2024.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-2-sem-programming-for-problem-solving-escs201-2023.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-cs-201-basic-computation-and-principles-of-computer-programming-2015.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-cs-201-chemistry-1-2017.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-es-201-basic-electrical-and-electronics-engineering-1-2015.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-es-201-part-2-basic-electrical-and-electronic-engineering-2-2017.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-es-201-part-2-basic-electrical-and-electronics-engineering-2-2017.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-es-201t-basic-electrical-and-electronic-engineering-2-2018.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-es-cs-2-sem-programming-for-problem-solving-escs201-2024.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-m-201-mathematics-2-2017.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-m-201-mathematics-2-2018.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-me-201-engineering-thermodynamics-and-fluid-mechanics-2016.pdf
  MAKAUT/Instrumentation and Control Engineering/2nd semester/btech-me-201-engineering-thermodynamics-and-fluid-mechanics-2017.pdf
Labels: enhancement, Advanced, SSOC S4

#524 Uploaded 25+ PYQs for Complex Variables and Linear Algebra (MAT3003) – #522
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003)  20.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) (1).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) (10).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) (11).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) (12).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) (13).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) (14).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) (15).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) (16).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) (2).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) (3).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) (4).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) (5).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) (6).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) (7).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) (8).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) (9).pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) 17.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) 18.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) 19.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) 21.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) 22.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) 23.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) 24.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex Variables and Linear Algebra(MAT3003) 25.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex_Variables_and_Linear_Algebra_1(MAT3003) 26.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/Complex_Variables_and_Linear_Algebra_2(MAT3003) 27.pdf
  VIT Bhopal University/10.Interdisciplinary & Others/Complex Variables and Linear Algebra (MAT3003)/README.md
Labels: enhancement, Advanced, SSOC S4

#527 Add pyq of mechanical engineering department of 2nd semester
  MAKAUT/Mechanical Engineering/2nd semester/btech-2-sem-chemistry-1-bsch201-2023.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-2-sem-english-hmhu201-2023.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-2-sem-mathematics-2-b-bsm202-2023.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-2-sem-mathematics-2-bsm-202-n-2019.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-2-sem-mathematics-2a-bsm201-2023.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-2-sem-mathematics-2a-bsm201-2024.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-2-sem-physics-1-bs-ph-201-n-2019.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-2-sem-physics-1-bsph201-2024.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-2-sem-programming-for-problem-solving-escs201-2023.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-cs-201-basic-computation-and-principles-of-computer-programming-2015.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-cs-201-basic-computation-and-principles-of-computer-programming-2017.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-cs-201-basic-computation-and-principles-of-computer-programming-2018.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-cs-201-basic-computation-and-principles-of-computer-programming-2019.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-cs-201-chemistry-1-2017.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-es-201-basic-electrical-and-electronic-engineering-2-2018.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-es-201-basic-electrical-and-electronics-engineering-1-2015.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-es-201-basic-electrical-and-electronics-engineering-2-2016.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-es-201-part-2-basic-electrical-and-electronic-engineering-2-2017.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-es-201-part-2-basic-electrical-and-electronics-engineering-2-2017.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-es-201t-basic-electrical-and-electronic-engineering-2-2018.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-m-201-mathematics-2-2017.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-m-201-mathematics-2-2018.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-m-201-mathematics-2-2019.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-me-201-engineering-thermodynamics-and-fluid-mechanics-2016.pdf
  MAKAUT/Mechanical Engineering/2nd semester/btech-me-201-engineering-thermodynamics-and-fluid-mechanics-2017.pdf
  MAKAUT/Mechanical Engineering/3rd Semester/X
Labels: enhancement, Intermediate, SSOC S4
