Repository Saumy1905/PYQFort, pull requests merged in 2025-07, with the labels that each got.

#533 Add the pyq of ceramic technology of 4th semester
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-ceramic-raw-materials-2009.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-ceramic-raw-materials-2010.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-ceramic-raw-materials-2011.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-ceramic-raw-materials-2012.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-computer-science-and-operation-research-2009.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-computer-science-and-operation-research-2010.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-computer-science-and-operation-research-2011.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-energy-engineering-and-furnaces-2009.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-energy-engineering-and-furnaces-2010.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-energy-engineering-and-furnaces-2011.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-energy-resource-and-elements-of-furnaces-2012.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-mathematics-3-2012.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-numerical-methods-2012.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-process-calculation-2012.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-process-calculations-2009.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-process-calculations-2010.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-process-calculations-2011.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-process-ceramics-1-2009.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-process-ceramics-1-2010.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-process-ceramics-1-2011.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-process-ceramics-1-2012.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-process-ceramics-2012.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-unit-operation-2-2009.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-unit-operation-2-2010.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-unit-operation-2-2011.pdf
  MAKAUT/Cermaic Technology/4th semester/btech-ct-4-sem-unit-operation-2-2012.pdf
Labels: enhancement, Advanced, SSOC S4

#538 Added README.md for Interdisciplinary & Others (VIT Bhopal)" #536
  VIT Bhopal University/10.Interdisciplinary & Others/README.md
Labels: enhancement, Advanced, SSOC S4

#543 Added PYQs for Cse 1st and 2nd All All
  Silicon_University/1st Sem/1st SEMESTER End TERM/Basic Electronics Engineering-1st sem End term.pdf
  Silicon_University/1st Sem/1st SEMESTER End TERM/Computer Programming-1st sem End term.pdf
  Silicon_University/1st Sem/1st SEMESTER End TERM/Constitution of India-1st sem End term.pdf
  Silicon_University/1st Sem/1st SEMESTER End TERM/Engineering Chemistry-1st sem End term.pdf
  Silicon_University/1st Sem/1st SEMESTER End TERM/Maths-1st sem End term.pdf
  Silicon_University/1st Sem/1st SEMESTER Mid TERM/Basic Electronic Engineering-1st sem Mid term.pdf
  Silicon_University/1st Sem/1st SEMESTER Mid TERM/Computer Programming-1st sem Mid term.pdf
  Silicon_University/1st Sem/1st SEMESTER Mid TERM/Constitution of India-1st sem Mid term.pdf
  Silicon_University/1st Sem/1st SEMESTER Mid TERM/Engineering Chemistry-1st sem Mid term.pdf
  Silicon_University/1st Sem/1st SEMESTER Mid TERM/Maths-1st sem Mid term.pdf
  Silicon_University/2nd Sem/2nd SEMESTER End TERM/Communicative and Technical English-1st sem End term.pdf
  Silicon_University/2nd Sem/2nd SEMESTER Mid TERM/Basic Electrical engineering-2nd sem Mid term.pdf
  Silicon_University/2nd Sem/2nd SEMESTER Mid TERM/Communicative and Technical English-1st sem Mid term.pdf
  Silicon_University/2nd Sem/2nd SEMESTER Mid TERM/Data structure and algorithm-2nd sem Mid term.pdf
  Silicon_University/2nd Sem/2nd SEMESTER Mid TERM/Engineering physics-2nd sem Mid term.pdf
  Silicon_University/2nd Sem/2nd SEMESTER Mid TERM/Environmental science and engineering-2nd sem Mid term.pdf
  Silicon_University/2nd Sem/2nd SEMESTER Mid TERM/Maths-2nd sem Mid term.pdf
Labels: enhancement, Advanced, SSOC S4

#539 Add the pyq of chemical engineering of 2nd semester
  MAKAUT/Chemical Engineering/2nd semester/btech-2-sem-basic-electrical-engineering-es-ee101-2024.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-2-sem-chemistry-1-bsch201-2023.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-2-sem-chemistry-1-bsch201-2024.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-2-sem-english-hmhu201-2023.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-2-sem-english-hmhu201-2024.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-2-sem-mathematics-2-bsm-202-n-2019.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-2-sem-mathematics-2a-bsm201-2023.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-2-sem-mathematics-2a-bsm201-2024.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-2-sem-physics-1-bs-ph-201-n-2019.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-2-sem-physics-1-bsph201-2024.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-2-sem-programming-for-problem-solving-escs201-2023.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-cs-201-basic-computation-and-principles-of-computer-programming-2015.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-cs-201-basic-computation-and-principles-of-computer-programming-2017.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-cs-201-basic-computation-and-principles-of-computer-programming-2018.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-cs-201-basic-computation-and-principles-of-computer-programming-2019.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-cs-201-chemistry-1-2017.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-es-201-basic-electrical-and-electronic-engineering-2-2018.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-es-201-basic-electrical-and-electronics-engineering-2-2016.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-es-201-part-2-basic-electrical-and-electronic-engineering-2-2017.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-es-201-part-2-basic-electrical-and-electronics-engineering-2-2017.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-es-201t-basic-electrical-and-electronic-engineering-2-2018.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-m-201-mathematics-2-2017.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-m-201-mathematics-2-2018.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-m-201-mathematics-2-2019.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-me-201-engineering-thermodynamics-and-fluid-mechanics-2016.pdf
  MAKAUT/Chemical Engineering/2nd semester/btech-me-201-engineering-thermodynamics-and-fluid-mechanics-2017.pdf
Labels: enhancement, Advanced, SSOC S4

#544 Upload 25 pyq of electronic and communication engineering of 4th semester
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ec-4-sem-analog-communication-ec401-2023.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ec-4-sem-analog-electronic-circuits-ec402-2023.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ec-4-sem-analog-electronics-circuits-ec402-2023.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ec-4-sem-microprocessor-and-microcontrollers-ec403-2023.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ec-401-electromagnetic-theory-and-transmission-lines-2013.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ec-401-electromagnetic-theory-and-transmission-lines-2014.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ec-401-electromagnetic-theory-and-transmission-lines-2015.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ec-401-electromagnetic-theory-and-transmission-lines-2016.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ec-401-electromagnetic-theory-and-transmission-lines-2017.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ec-402-digital-electronic-and-integrated-circuits-2014.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ec-402-digital-electronic-circuits-2013.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ec-402-digital-electronics-and-integrated-circuits-2013.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ec-402-digital-electronics-and-integrated-circuits-2014.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ec-402-digital-electronics-and-integrated-circuits-2015.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ec-402-digital-electronics-and-integrated-circuits-2016.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ec-402-digital-electronics-and-integrated-circuits-2017.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ec-411-principle-of-communication-engineering-2013.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ece-4-sem-analog-communication-2013.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ece-4-sem-analog-electronic-circuits-2013.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ece-4-sem-basic-environmental-engineering-and-elementary-biology-2013.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ece-4-sem-digital-electronic-circuits-2013.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ece-4-sem-digital-electronics-and-integrated-circuits-2013.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ece-4-sem-electromagnetic-theory-and-transmission-lines-2013.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ece-4-sem-microelectronics-and-opto-electronic-devices-2013.pdf
  MAKAUT/Electonics and Communication Engineering/4th semester/btech-ece-4-sem-values-and-ethics-in-profession-2013.pdf
Labels: enhancement, Advanced, SSOC S4

#550 Updated Main README.md of VIT Bhopal University – PYQFort Root Directory #547
  VIT Bhopal University/README.md
Labels: enhancement, Intermediate, SSOC S4

#551 Added GGIPU SEM 1 and 2 question paper
  GGIPU SEM 1 & 2/SEM 1/btech-1-sem-applied-chemistry-etch-113-jan-2024.pdf
  GGIPU SEM 1 & 2/SEM 1/btech-1-sem-applied-mathematics-1-bs-111-dec-2024.pdf
  GGIPU SEM 1 & 2/SEM 1/btech-1-sem-applied-mathematics-1-etma-101-jan-2024.pdf
  GGIPU SEM 1 & 2/SEM 1/btech-1-sem-communications-skills-hs-113-jan-2025.pdf
  GGIPU SEM 1 & 2/SEM 1/btech-1-sem-electrical-science-es-107-jan-2025.pdf
  GGIPU SEM 1 & 2/SEM 1/btech-1-sem-environmental-studies-bs-109-jan-2024.pdf
  GGIPU SEM 1 & 2/SEM 1/btech-1-sem-environmental-studies-bs-109-jan-2025.pdf
  GGIPU SEM 1 & 2/SEM 1/btech-1-sem-manufacturing-process-es-119-dec-2024.pdf
  GGIPU SEM 1 & 2/SEM 1/btech-1-sem-manufacturing-processes-etme-105-jan-2024.pdf
  GGIPU SEM 1 & 2/SEM 1/btech-1-sem-programming-in-c-es-101-dec-2024.pdf
  GGIPU SEM 1 & 2/SEM 1/btech-1-sem-programming-in-c-es-101-jan-2024.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-2-sem-applied-chemistry-bs-104-jul-2023.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-2-sem-applied-chemistry-bs-104-jun-2024.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-2-sem-applied-mathematics-2-bs-112-jul-2023.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-2-sem-applied-mathematics-2-bs-112-jun-2024.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-2-sem-applied-mathematics-2-etma-102-jul-2023.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-2-sem-applied-physics-2-bs-106-jul-2023.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-2-sem-applied-physics-2-bs-106-jun-2024.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-2-sem-communication-skills-hs-114-jul-2023.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-2-sem-electrical-science-es-108-jul-2023.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-2-sem-engineering-mechanics-es-114-jul-2023.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-2-sem-engineering-mechanics-es-114-jun-2024.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-2-sem-environmental-studies-bs-110-jul-2023.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-2-sem-environmental-studies-bs-110-jun-2024.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-2-sem-introduction-to-programming-etcs-108-jul-2021.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-2-sem-programming-in-c-es-102-jul-2023.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-2-sem-programming-in-c-es-102-jun-2024.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-cic-3-sem-data-structures-cic-209-dec-2024.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-cic-3-sem-discrete-mathematics-cic-205-dec-2024.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-cic-3-sem-object-oriented-programming-using-cpp-cic-211-jan-2025.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-ecc-3-sem-analog-electronics-1-ecc-211-jan-2025.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-ecc-3-sem-digital-logic-and-computer-design-ecc-207-dec-2024 (1).pdf
  GGIPU SEM 1 & 2/SEM 2/btech-ecc-3-sem-digital-logic-and-computer-design-ecc-207-dec-2024 (2).pdf
  GGIPU SEM 1 & 2/SEM 2/btech-ecc-3-sem-digital-logic-and-computer-design-ecc-207-dec-2024.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-ecc-3-sem-electronagnetic-field-theory-ecc-213-dec-2024.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-ecc-3-sem-electronics-1-ecc-215-dec-2024.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-ecc-3-sem-signals-and-systems-ecc-205-dec-2024.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-eec-3-sem-electrical-machines-1-eec-211-jan-2025.pdf
  GGIPU SEM 1 & 2/SEM 2/btech-eec-3-sem-electrical-materials-eec-209-dec-2024.pdf
Labels: enhancement, Advanced, SSOC S4

#553 Add the pyq of fashion technology of 4th semester
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-bio-chemistry-and-nutrition-2013.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-biochemistry-and-nutrition-2012.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-chemistry-of-food-2013.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-chemistry-of-foods-2012.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-data-structure-algorithms-2010.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-data-structure-and-algorithm-2009.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-data-structure-and-algorithm-2012.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-data-structure-and-algorithms-2011.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-data-structure-and-algorithms-2013.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-food-process-technology-1-2009.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-food-process-technology-1-2010.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-food-process-technology-1-2012.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-food-process-technology-1-2013.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-industrial-stoichiometry-2012.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-industrial-stoichiometry-2013.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-industrial-stoichiometry-v2-2012.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-industrial-stoichiometry-v2-2013.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-numerical-methods-2013.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-principle-of-food-preservation-2012.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-principles-of-food-preservation-2009.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-principles-of-food-preservation-2010.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-principles-of-food-preservation-2011.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-principles-of-food-preservation-2012.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-principles-of-food-preservation-2013.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-principles-of-food-preservation-v2-2013.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-unit-operation-in-chemical-engineering-1-2013.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-unit-operation-of-chemical-engineering-1-2011.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-unit-operation-of-chemical-engineering-1-2012.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-unit-operation-of-chemical-engineering-1-2013.pdf
  MAKAUT/Fashion Technology/Civil Engineering/4th semester/btech-ft-4-sem-unit-operations-of-chemical-engineering-1-2012.pdf
Labels: enhancement, Advanced, SSOC S4

#560 Added 25+ PYQs – Application of Differential and Difference Equation (MAT2002) | VIT Bhopal University #557
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002) .pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002) 12.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002) 14.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002) 18.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002) 20.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002) 22.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002) 23.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002) 24.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002) 25.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002) 26.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002) 8.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002)10.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002)11 .pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002)13 .pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002)15 .pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002)16 .pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002)17 .pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002)19 .pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002)2.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002)21 .pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002)3 .pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002)4 .pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002)5 .pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002)6 .pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002)7 .pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002)8 .pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/ AOD(dec 2019) (MAT2002)9 .pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/AOD(MAT2002)/README.md
Labels: enhancement, Advanced, SSOC S4, Data Structuring

#565 PYQ addition for GGIPU SEM 5 and 6 #556Add files via upload
  GGIPU SEM 5 & 6/SEM 5/btech-5-sem-control-system-etel-307-dec-2019.pdf
  GGIPU SEM 5 & 6/SEM 5/btech-etat-5-sem-heat-transfer-and-ic-engines-etat-305-dec-2019.pdf
  GGIPU SEM 5 & 6/SEM 5/btech-etat-5-sem-metal-cutting-and-tool-design-etat303-dec-2019.pdf
  GGIPU SEM 5 & 6/SEM 5/btech-etce-5-sem-advanced-structural-analysis-etce-303-dec-2018.pdf
  GGIPU SEM 5 & 6/SEM 5/btech-etce-5-sem-design-of-steel-structures-etce-305-dec-2018.pdf
  GGIPU SEM 5 & 6/SEM 5/btech-etce-5-sem-engineering-hydrology-etce-307-dec-2018.pdf
  GGIPU SEM 5 & 6/SEM 5/btech-etce-5-sem-geotechnical-and-fundation-engg-etce-309-dec-2018.pdf
  GGIPU SEM 5 & 6/SEM 5/btech-etcs-5-sem-algorithms-design-and-analysis-etcs301-feb-2023.pdf
  GGIPU SEM 5 & 6/SEM 5/btech-etcs-5-sem-software-engineering-etcs303-feb-2023.pdf
  GGIPU SEM 5 & 6/SEM 5/btech-eths-5-sem-communication-skills-for-professionals-eths-301-dec-2019.pdf
  GGIPU SEM 5 & 6/SEM 5/btech-eths-5-sem-communication-skills-for-professionals-eths301-feb-2023.pdf
  GGIPU SEM 5 & 6/SEM 5/btech-etme-5-sem-management-of-manufacturing-systems-etme-301-dec-2019.pdf
  GGIPU SEM 5 & 6/SEM 6/btech-eee-6-sem-utilization-of-electrical-energy-eee-320t-jun-2025.pdf
  GGIPU SEM 5 & 6/SEM 6/btech-etce-6-sem-open-channel-flow-and-numerical-hydraulics-etce-308-jun-2018.pdf
  GGIPU SEM 5 & 6/SEM 6/btech-etce-6-sem-quantity-surveying-and-cost-estimation-etce-306-jun-2018.pdf
  GGIPU SEM 5 & 6/SEM 6/btech-etcs-6-sem-artificial-intelligence-etcs-310-jul-2023.pdf
  GGIPU SEM 5 & 6/SEM 6/btech-etcs-6-sem-compiler-design-etcs-302-jul-2023.pdf
  GGIPU SEM 5 & 6/SEM 6/btech-etcs-6-sem-operating-systems-etcs-304-jul-2023.pdf
  GGIPU SEM 5 & 6/SEM 6/btech-etcs-6-sem-web-engineering-web-technology-etcs-308-jul-2023.pdf
  GGIPU SEM 5 & 6/SEM 6/btech-etec-it-6-sem-data-communication-and-networks-etec-310-jul-2023.pdf
  GGIPU SEM 5 & 6/SEM 6/btech-etee-6-sem-microprocessors-and-microcontrollers-etee-310-jul-2023.pdf
Labels: enhancement, Advanced, SSOC S4

#563 Added 25 + pyq for STATISTICS(MAT2001) under EEE
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/README.md
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2019)(MAT2001).pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2019)(MAT2001)17.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2019)(MAT2001)2.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2019)(MAT2001)28.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001).pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)10.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)11.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)12.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)13.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)14.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)18.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)19.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)20.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)21.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)23.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)24.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)25.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)26.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)27.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)3.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)4.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)5.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)6.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)7.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)8.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/STATISTIC(MAT2001)/STATISTICS(may 2020)(MAT2001)9.pdf
Labels: enhancement, Advanced, SSOC S4, Data Structuring

#581 PYQ addition on GGIPU 1 and 2 sem of BAAdd files via upload
  GGIPU BA SEM 1 & 2/SEM 1/ba-1-sem-jmc-basic-of-design-and-graphics-ba-105-2019.pdf
  GGIPU BA SEM 1 & 2/SEM 1/ba-1-sem-jmc-communication-concepts-and-processes-ba-101-dec-2019.pdf
  GGIPU BA SEM 1 & 2/SEM 1/ba-1-sem-jmc-contemporary-india-and-overview-ba-103-dec-2019.pdf
  GGIPU BA SEM 1 & 2/SEM 1/ba-1-sem-jmc-personality-development-ba-107-dec-2019.pdf
  GGIPU BA SEM 1 & 2/SEM 1/ba-1-sem-jmc-writing-skills-ba-109-dec-2018.pdf
  GGIPU BA SEM 1 & 2/SEM 2/ba-2-sem-jmc-health-communication-ba-108-jun-2019.pdf
  GGIPU BA SEM 1 & 2/SEM 2/ba-2-sem-jmc-media-laws-and-ethics-ba-104-jun-2019.pdf
  GGIPU BA SEM 1 & 2/SEM 2/ba-2-sem-jmc-print-journalism-ba-102-jun-2019.pdf
  GGIPU BA SEM 1 & 2/SEM 2/ba-2-sem-jmc-still-photography-ba-106-jun-2019.pdf
Labels: enhancement, Beginner, SSOC S4

#602 Upload pyq of automobile engineering
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-applied-thermodynamics-2011.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-applied-thermodynamics-2012.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-basic-environmental-engineering-and-elementary-biology-2011.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-basic-environmental-engineering-and-elementary-biology-2012.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-engineering-materials-2011.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-engineering-materials-2012.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-engineering-thermodynamics-2009.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-engineering-thermodynamics-2011.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-engineering-thermodynamics-2012.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-fluid-mechanics-and-machinery-2010.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-fluid-mechanics-and-machinery-2011.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-fluid-mechanics-and-machinery-2012.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-manufacturing-methods-2009.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-manufacturing-methods-2011.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-manufacturing-methods-2012.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-mathematics-2010.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-mathematics-2011.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-mathematics-2012.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-physics-2-2011.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-physics-2-2012.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-strength-of-material-2012.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-strength-of-materials-2010.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-strength-of-materials-2011.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-strength-of-materials-2012.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-values-and-ethics-in-profession-2011.pdf
  MAKAUT/Automobile Engineering/3rd Semester/btech-aue-3-sem-values-and-ethics-in-profession-2012.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-cse-ee-eee-7-sem-computer-network-es-cs701-2025.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-ee-3-sem-analog-electronic-circuits-2011.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-ee-3-sem-digital-electronic-circuits-2011.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-ee-3-sem-field-theory-2012.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-ee-3-sem-mathematics-3-2012.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-ee-3-sem-numerical-methods-and-programming-2012.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-ee-301-electric-circuit-theory-2011.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-ee-7-sem-electric-drive-pc-ee-701-2025.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-ee-7-sem-electric-drives-ee-701-2020.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-ee-7-sem-power-generation-economics-pe-ee-701-c-2025.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-ee-7-sem-utilization-of-electric-power-ee-702-2020.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-ee-701-electric-drive-2017.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-ee-702-utilization-of-electric-power-2017.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-ee-703a-power-system-3-2017.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-ee-704d-renewable-and-non-conventional-energy-2017.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-ee-705a-computer-network-2017.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-ee-eee-7-sem-principle-of-management-hm-ee-701-2025.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-hm-ee-7-sem-principle-of-management-hm-ee-701-2023.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-oe-ee-7-sem-computer-network-oe-ee-702-c-2023.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-oe-ee-7-sem-digital-image-processing-oe-ee-702-b-2023.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-oe-ee-7-sem-intemet-of-things-oe-ee-701-b-2023.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-oe-ee-7-sem-internet-of-things-oe-ee-701-b-2023.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-oe-ei-7-sem-telemetry-and-wireless-sensor-network-oe-ei701-2023.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-pc-ee-7-sem-electric-drive-pc-ee-701-2023.pdf
  MAKAUT/Electrical Engineering/7th Semester/btech-pe-ee-7-sem-power-generation-economics-pe-ee-701-c-2023.pdf
Labels: enhancement, Advanced, SSOC S4

#605 Upload 25 pyq of electrical engineering
  MAKAUT/Electrical Engineering/7th Semester/btech-aue-3-sem-manufacturing-methods-2009.pdf
Labels: enhancement, SSOC S4

#610 YMCA CE 2nd sem PYQ added
  J.C. Bose UST, YMCA, Faridabad/03. Computer Engineering/2ndSEM/Mathematics.pdf
  J.C. Bose UST, YMCA, Faridabad/03. Computer Engineering/2ndSEM/PPS.pdf
  J.C. Bose UST, YMCA, Faridabad/03. Computer Engineering/2ndSEM/Physics.pdf
Labels: enhancement, Beginner, SSOC S4

#612 Uploaded 25+ PYQs for CAO(CSE2001) Under Computer science and engineering #611
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2019)(CSE2001)7.pdf
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001).pdf
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)10.pdf
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)11.jpg
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)12.jpg
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)13.jpg
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)14.jpg
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)15.jpg
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)16.jpg
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)17.jpg
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)18.jpg
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)19.jpg
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)2.pdf
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)20.jpg
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)21.jpg
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)22.jpg
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)24.pdf
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)26.pdf
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)3.pdf
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)4.pdf
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)5.pdf
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)6.pdf
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)8.pdf
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2020)(CSE2001)9.pdf
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2024)(CSE2001)23.jpg
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/CAO(May 2024)(CSE2001)25.jpg
  VIT Bhopal University/01. Computer Engineering/CAO(CSE2001)/README.md
Labels: enhancement, Advanced, SSOC S4

#616 Uploaded 25+ PYQs for Circuit Theory(ECE2001) and Electromagnetic Field Theory(ECE1003) #613
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Circuit Theory(ECE2001)/Circuit Theory(May 2024)(ECE2001).pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Circuit Theory(ECE2001)/Circuit Theory(May 2024)(ECE2001)10.jpg
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Circuit Theory(ECE2001)/Circuit Theory(May 2024)(ECE2001)11.jpg
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Circuit Theory(ECE2001)/Circuit Theory(May 2024)(ECE2001)2.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Circuit Theory(ECE2001)/Circuit Theory(May 2024)(ECE2001)3.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Circuit Theory(ECE2001)/Circuit Theory(May 2024)(ECE2001)4.jpg
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Circuit Theory(ECE2001)/Circuit Theory(May 2024)(ECE2001)5.jpg
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Circuit Theory(ECE2001)/Circuit Theory(May 2024)(ECE2001)6.jpg
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Circuit Theory(ECE2001)/Circuit Theory(May 2024)(ECE2001)7.jpg
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Circuit Theory(ECE2001)/Circuit Theory(May 2024)(ECE2001)8.jpg
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Circuit Theory(ECE2001)/Circuit Theory(May 2024)(ECE2001)9.jpg
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Circuit Theory(ECE2001)/README.md
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Electromagnetic Field Theory(ECE1003)/EMFT(May 2019)(ECE1003).pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Electromagnetic Field Theory(ECE1003)/EMFT(May 2019)(ECE1003)10.jpg
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Electromagnetic Field Theory(ECE1003)/EMFT(May 2019)(ECE1003)11.jpg
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Electromagnetic Field Theory(ECE1003)/EMFT(May 2019)(ECE1003)12.jpg
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Electromagnetic Field Theory(ECE1003)/EMFT(May 2019)(ECE1003)13.jpg
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Electromagnetic Field Theory(ECE1003)/EMFT(May 2019)(ECE1003)14.jpg
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Electromagnetic Field Theory(ECE1003)/EMFT(May 2019)(ECE1003)2.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Electromagnetic Field Theory(ECE1003)/EMFT(May 2019)(ECE1003)3.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Electromagnetic Field Theory(ECE1003)/EMFT(May 2019)(ECE1003)4.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Electromagnetic Field Theory(ECE1003)/EMFT(May 2019)(ECE1003)5.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Electromagnetic Field Theory(ECE1003)/EMFT(May 2019)(ECE1003)6.pdf
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Electromagnetic Field Theory(ECE1003)/EMFT(May 2019)(ECE1003)7.JPG
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Electromagnetic Field Theory(ECE1003)/EMFT(May 2019)(ECE1003)8.jpg
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Electromagnetic Field Theory(ECE1003)/EMFT(May 2019)(ECE1003)9.jpg
  VIT Bhopal University/04. Electrical & Electronics Engineering (EEE)/Electromagnetic Field Theory(ECE1003)/README.md
Labels: enhancement, Advanced, SSOC S4

#617 Upload 24 pyq of ceramic technology of 5th semester
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-cement-and-concrete-2009.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-cement-and-concrete-2010.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-cement-and-concrete-2011.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-ceramic-coating-2009.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-ceramic-coating-2010.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-ceramic-coating-2011.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-database-management-system-2012.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-economics-for-engineers-2012.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-glass-1-2009.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-glass-1-2010.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-glass-1-2011.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-glass-science-and-technology-2012.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-metallurgy-2009.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-metallurgy-2010.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-metallurgy-2011.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-object-oriented-programming-2012.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-refractories-1-2009.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-refractories-1-2010.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-refractories-1-2011.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-refractories-technology-2012.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-white-wares-technology-2012.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-whitewares-1-2009.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-whitewares-1-2010.pdf
  MAKAUT/Cermaic Technology/5th semester/btech-ct-5-sem-whitewares-1-2011.pdf
Labels: enhancement, Advanced, SSOC S4

#621 Upload pyq of chemical engineering
  MAKAUT/Chemical Engineering/4th semester/btech-ch-401-basic-environmental-engineering-and-elementary-biology-2012.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-ch-401-basic-environmental-engineering-and-elementary-biology-2013.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-ch-401-basic-environmental-engineering-and-elementary-biology-2014.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-ch-401-basic-environmental-engineering-and-elementary-biology-2015.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-ch-401-basic-environmental-engineering-and-elementary-biology-2017.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-ch-401-basic-environmental-engineering-and-elementary-biology-2019.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-4-sem-chemical-engineering-thermodynamics-2012.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-4-sem-chemical-engineering-thermodynamics-2013.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-4-sem-data-structure-and-database-concept-2012.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-4-sem-data-structure-and-database-concept-2013.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-4-sem-energy-sources-and-their-utilization-2012.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-4-sem-energy-sources-and-their-utilization-2013.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-4-sem-fluid-mechanics-2012.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-4-sem-fluid-mechanics-2013.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-4-sem-material-science-and-technology-2012.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-4-sem-material-science-and-technology-2013.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-4-sem-mathematics-3-2013.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-4-sem-mechanical-operation-2012.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-4-sem-mechanical-operation-2013.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-4-sem-mechanical-operations-2013.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-4-sem-process-heat-transfer-2013.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-401-data-structure-and-database-concept-2012.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-401-data-structure-and-database-concept-2013.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-402-mechanical-operations-2013.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-402-process-heat-transfer-2012.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-402-process-heat-transfer-2013.pdf
  MAKAUT/Chemical Engineering/4th semester/btech-che-403-mechanical-operations-2012.pdf
  MAKAUT/Civil Engineering/5th semester/N
Labels: enhancement, Advanced, SSOC S4

#625 Uploaded 25+ PYQs for German(GER1001) and Japanese(JAP1001) under the Management and Humanities #619
  VIT Bhopal University/11.Management and Humanities/German(GER1001)/German(May 2024)(GER1001)1.pdf
  VIT Bhopal University/11.Management and Humanities/German(GER1001)/German(May 2024)(GER1001)10.jpg
  VIT Bhopal University/11.Management and Humanities/German(GER1001)/German(May 2024)(GER1001)11.pdf
  VIT Bhopal University/11.Management and Humanities/German(GER1001)/German(May 2024)(GER1001)12.pdf
  VIT Bhopal University/11.Management and Humanities/German(GER1001)/German(May 2024)(GER1001)13.pdf
  VIT Bhopal University/11.Management and Humanities/German(GER1001)/German(May 2024)(GER1001)2.pdf
  VIT Bhopal University/11.Management and Humanities/German(GER1001)/German(May 2024)(GER1001)3.pdf
  VIT Bhopal University/11.Management and Humanities/German(GER1001)/German(May 2024)(GER1001)4.pdf
  VIT Bhopal University/11.Management and Humanities/German(GER1001)/German(May 2024)(GER1001)5.pdf
  VIT Bhopal University/11.Management and Humanities/German(GER1001)/German(May 2024)(GER1001)6.pdf
  VIT Bhopal University/11.Management and Humanities/German(GER1001)/German(May 2024)(GER1001)7.jpg
  VIT Bhopal University/11.Management and Humanities/German(GER1001)/German(May 2024)(GER1001)8.jpg
  VIT Bhopal University/11.Management and Humanities/German(GER1001)/German(May 2024)(GER1001)9.jpg
  VIT Bhopal University/11.Management and Humanities/German(GER1001)/README.md
  VIT Bhopal University/11.Management and Humanities/Japanese(JAP1001)/Japanese(May 2024)(JAP1001)1.pdf
  VIT Bhopal University/11.Management and Humanities/Japanese(JAP1001)/Japanese(May 2024)(JAP1001)10.pdf
  VIT Bhopal University/11.Management and Humanities/Japanese(JAP1001)/Japanese(May 2024)(JAP1001)11.pdf
  VIT Bhopal University/11.Management and Humanities/Japanese(JAP1001)/Japanese(May 2024)(JAP1001)12.pdf
  VIT Bhopal University/11.Management and Humanities/Japanese(JAP1001)/Japanese(May 2024)(JAP1001)13.pdf
  VIT Bhopal University/11.Management and Humanities/Japanese(JAP1001)/Japanese(May 2024)(JAP1001)2.pdf
  VIT Bhopal University/11.Management and Humanities/Japanese(JAP1001)/Japanese(May 2024)(JAP1001)3.pdf
  VIT Bhopal University/11.Management and Humanities/Japanese(JAP1001)/Japanese(May 2024)(JAP1001)4.pdf
  VIT Bhopal University/11.Management and Humanities/Japanese(JAP1001)/Japanese(May 2024)(JAP1001)5.jpg
  VIT Bhopal University/11.Management and Humanities/Japanese(JAP1001)/Japanese(May 2024)(JAP1001)6.jpg
  VIT Bhopal University/11.Management and Humanities/Japanese(JAP1001)/Japanese(May 2024)(JAP1001)7.jpg
  VIT Bhopal University/11.Management and Humanities/Japanese(JAP1001)/Japanese(May 2024)(JAP1001)8.jpg
  VIT Bhopal University/11.Management and Humanities/Japanese(JAP1001)/Japanese(May 2024)(JAP1001)9.pdf
  VIT Bhopal University/11.Management and Humanities/Japanese(JAP1001)/README.md
Labels: enhancement, Advanced, SSOC S4

#628 Upload 24 pyq of civil engineering department
  MAKAUT/Biotechnology and leather/1st semester/C
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-construction-engineering-and-management-ce-pc-601-2023.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-construction-engineering-and-management-ce-pc-601-2024.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-construction-engineering-and-management-ce-pc-601-2025.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-construction-planning-and-management-2013.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-construction-planning-and-management-2015.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-design-of-steel-structure-2015.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-design-of-steel-structures-ce-pc-604-2023.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-design-of-steel-structures-ce-pc-604-2024.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-engineering-economics-estimation-and-costing-ce-pc-602-2023.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-engineering-economics-estimation-and-costing-ce-pc-602-2024.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-engineering-economics-estimation-and-costing-ce-pc-602-2025.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-environmental-engineering-2-2013.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-foundation-engineering-ce-pe-6018-2023.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-foundation-engineering-ce-pe-601b-2024.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-highway-and-transportation-engineering-2015.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-human-resource-management-2013.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-operation-research-2015.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-principles-of-management-2013.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-soft-skills-and-interpersonal-communication-1-ce-oe-601a-2024.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-structural-dynamics-and-earthquake-engineering-2015.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-water-resources-engineering-ce-pc-603-2023.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-water-resources-engineering-ce-pc-603-2024.pdf
  MAKAUT/Civil Engineering/6th semester/btech-ce-6-sem-water-resources-engineering-ce-pc-603-2025.pdf
  MAKAUT/Civil Engineering/6th semester/btech-hm-hu-6-sem-operations-research-hm-hu601-2023.pdf
Labels: enhancement, Advanced, SSOC S4

#634 Upload pyq of biotechnology and leather in 1st semester
  MAKAUT/Biotechnology and leather/1st semester/C
  MAKAUT/Biotechnology and leather/1st semester/btech-1-sem-basic-electrical-and-electronic-engineering-1-es-101-part-2-2018.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-1-sem-basic-electrical-engineering-es-ee-101-2020.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-1-sem-chemistry-1-bs-ch-101-2019.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-1-sem-chemistry-1-bs-ch-101-2020.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-1-sem-mathematics-1-m-101-2017.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-1-sem-mathematics-1b-bs-m-102-2019.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-1-sem-mathematics-1b-bs-m-102-2020.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-1-sem-physics-1-bs-ph-101-2019.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-1-sem-physics-1-ph-101-2017.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-1-sem-physics-2-ph-301-2020.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-es-101-basic-electrical-and-electronic-engineering-1-2019.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-es-101-basic-electrical-and-electronic-engineering-1-v2-2019.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-es-101-basic-electrical-and-electronics-engineering-1-2015.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-es-101-basic-electrical-and-electronics-engineering-1-2016.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-es-101-basic-electrical-and-electronics-engineering-1-2017.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-hu-101-english-language-and-communication-2015.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-hu-101-english-language-and-communication-2016.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-hu-101-english-language-and-communication-2017.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-m-101-mathematics-2015.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-m-101-mathematics-2016.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-me-1-sem-engineering-mechanics-me-101-2017.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-me-1-sem-engineering-mechanics-me-101-2018.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-me-101-mechanical-sciences-2016.pdf
  MAKAUT/Biotechnology and leather/1st semester/btech-ph-101-engineering-physics-2016.pdf
Labels: enhancement, Advanced, SSOC S4

#645 Uploaded 25+ PYQs for Network and communications(CSE1004) ,Accounting and Financial Management(MGT1028),Alternative Fuels(MEE1012) and Android Programming(SWE2008) #640
  VIT Bhopal University/01. Computer Engineering/Android Programming(SWE2008)/Android Programming(SWE2008)1.jpg
  VIT Bhopal University/01. Computer Engineering/Android Programming(SWE2008)/Android Programming(SWE2008)2.jpg
  VIT Bhopal University/01. Computer Engineering/Android Programming(SWE2008)/Android Programming(SWE2008)3.jpg
  VIT Bhopal University/01. Computer Engineering/Android Programming(SWE2008)/README.md
  VIT Bhopal University/01. Computer Engineering/Network and communications(CSE1004)/Network and Communications(May 2020)(CSE1004).pdf
  VIT Bhopal University/01. Computer Engineering/Network and communications(CSE1004)/Network and Communications(May 2020)(CSE1004)10.pdf
  VIT Bhopal University/01. Computer Engineering/Network and communications(CSE1004)/Network and Communications(May 2020)(CSE1004)12.pdf
  VIT Bhopal University/01. Computer Engineering/Network and communications(CSE1004)/Network and Communications(May 2020)(CSE1004)13.pdf
  VIT Bhopal University/01. Computer Engineering/Network and communications(CSE1004)/Network and Communications(May 2020)(CSE1004)14.pdf
  VIT Bhopal University/01. Computer Engineering/Network and communications(CSE1004)/Network and Communications(May 2020)(CSE1004)15.pdf
  VIT Bhopal University/01. Computer Engineering/Network and communications(CSE1004)/Network and Communications(May 2020)(CSE1004)2.pdf
  VIT Bhopal University/01. Computer Engineering/Network and communications(CSE1004)/Network and Communications(May 2020)(CSE1004)3.pdf
  VIT Bhopal University/01. Computer Engineering/Network and communications(CSE1004)/Network and Communications(May 2020)(CSE1004)4.pdf
  VIT Bhopal University/01. Computer Engineering/Network and communications(CSE1004)/Network and Communications(May 2020)(CSE1004)5.pdf
  VIT Bhopal University/01. Computer Engineering/Network and communications(CSE1004)/Network and Communications(May 2020)(CSE1004)6.pdf
  VIT Bhopal University/01. Computer Engineering/Network and communications(CSE1004)/Network and Communications(May 2020)(CSE1004)7.pdf
  VIT Bhopal University/01. Computer Engineering/Network and communications(CSE1004)/Network and Communications(May 2020)(CSE1004)8.pdf
  VIT Bhopal University/01. Computer Engineering/Network and communications(CSE1004)/Network and Communications(May 2020)(CSE1004)9.pdf
  VIT Bhopal University/01. Computer Engineering/Network and communications(CSE1004)/README.md
  VIT Bhopal University/03.Mechanical Engineering (ME)/Alternative Fuels(MEE1012)/Alternative Fuels(May 2020)(MEE1012)1.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Alternative Fuels(MEE1012)/Alternative Fuels(May 2020)(MEE1012)2.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Alternative Fuels(MEE1012)/Alternative Fuels(May 2020)(MEE1012)3.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Alternative Fuels(MEE1012)/Alternative Fuels(May 2020)(MEE1012)4.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Alternative Fuels(MEE1012)/Alternative Fuels(May 2020)(MEE1012)5.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Alternative Fuels(MEE1012)/README.md
  VIT Bhopal University/11.Management and Humanities/Accounting and Financial Management(MGT1028)/Accounting and Financial Management(MGT1028)1.pdf
  VIT Bhopal University/11.Management and Humanities/Accounting and Financial Management(MGT1028)/Accounting and Financial Management(MGT1028)2.pdf
  VIT Bhopal University/11.Management and Humanities/Accounting and Financial Management(MGT1028)/Accounting and Financial Management(MGT1028)3.jpg
  VIT Bhopal University/11.Management and Humanities/Accounting and Financial Management(MGT1028)/Accounting and Financial Management(MGT1028)4.jpg
  VIT Bhopal University/11.Management and Humanities/Accounting and Financial Management(MGT1028)/README.md
Labels: enhancement, Advanced, SSOC S4

#647 Upload pyq of mechanical engineering of 6th semester
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-air-conditioning-and-refrigeration-2015.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-air-conditioning-and-refrigeration-2016.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-air-conditioning-and-refrigeration-2017.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-air-conditioning-and-refrigeration-2019.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-design-of-machine-elements-pc-me602-2025.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-finite-element-methods-2016.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-ic-engine-and-gas-turbine-2015.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-ic-engine-and-gas-turbine-2019.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-ic-engines-and-gas-turbines-2015.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-internal-combustion-engines-and-gas-turbines-2016.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-internal-combustion-engines-and-gas-turbines-2017.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-machine-design-2015.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-machine-design-2016.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-machine-design-2017.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-machine-design-2019.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-machining-principles-and-machine-tools-2015.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-machining-principles-and-machine-tools-2016.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-machining-principles-and-machine-tools-2017.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-machining-principles-and-machine-tools-2019.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-material-handling-2016.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-materials-handling-2017.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-turbo-machinery-2016.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-me-6-sem-turbomachinery-2017.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-pc-me-6-sem-design-of-machine-elements-pc-me602-2023.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-pc-me-6-sem-manufacturing-technology-pc-me601-2023.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-pc-me-6-sem-manufacturing-technology-pc-me601-2024.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-pe-me-6-sem-internal-combustion-engines-and-gas-turbines-pe-me601a-2023.pdf
  MAKAUT/Mechanical Engineering/6th semester/btech-pe-me-6-sem-refrigeration-and-air-conditioning-pe-me601b-2023.pdf
Labels: enhancement, Advanced, SSOC S4

#648 Uploaded 25+ PYQs for Foundation of blockchain technology(CSI3013), Industrial Engineering(MEE1014), Microprocessor and Interfacing(CSE2006) #646
  VIT Bhopal University/01. Computer Engineering/Microprocessor and Interfacing (CSE2006)/Microprocessor and Interfacing(May 2020)(CSE2006)27.pdf
  VIT Bhopal University/01. Computer Engineering/Microprocessor and Interfacing (CSE2006)/Microprocessor and Interfacing(May 2020)(CSE2006)28.pdf
  VIT Bhopal University/01. Computer Engineering/Microprocessor and Interfacing (CSE2006)/Microprocessor and Interfacing(May 2020)(CSE2006)29.pdf
  VIT Bhopal University/01. Computer Engineering/Microprocessor and Interfacing (CSE2006)/Microprocessor and Interfacing(May 2020)(CSE2006)30.pdf
  VIT Bhopal University/01. Computer Engineering/Microprocessor and Interfacing (CSE2006)/Microprocessor and Interfacing(May 2020)(CSE2006)31.pdf
  VIT Bhopal University/01. Computer Engineering/Microprocessor and Interfacing (CSE2006)/Microprocessor and Interfacing(May 2020)(CSE2006)32.pdf
  VIT Bhopal University/01. Computer Engineering/Microprocessor and Interfacing (CSE2006)/Microprocessor and Interfacing(May 2020)(CSE2006)33.pdf
  VIT Bhopal University/01. Computer Engineering/Microprocessor and Interfacing (CSE2006)/Microprocessor and Interfacing(May 2020)(CSE2006)34.pdf
  VIT Bhopal University/01. Computer Engineering/Microprocessor and Interfacing (CSE2006)/Microprocessor and Interfacing(May 2020)(CSE2006)35.pdf
  VIT Bhopal University/01. Computer Engineering/Microprocessor and Interfacing (CSE2006)/Microprocessor and Interfacing(May 2020)(CSE2006)37.pdf
  VIT Bhopal University/01. Computer Engineering/Microprocessor and Interfacing (CSE2006)/Microprocessor and Interfacing(May 2020)(CSE2006)38.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(MEE1014)1.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(MEE1014)10.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(MEE1014)11.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(MEE1014)12.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(MEE1014)14.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(MEE1014)2.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(MEE1014)3.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(MEE1014)4.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(MEE1014)5.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(MEE1014)6.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(MEE1014)7.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(MEE1014)8.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/README.md
  VIT Bhopal University/09.Information Technology (IT)/Foundation of blockchain technology(CSI3013)/Foundation of blockchain technology(May 2025)(CSI3013)1.jpg
  VIT Bhopal University/09.Information Technology (IT)/Foundation of blockchain technology(CSI3013)/Foundation of blockchain technology(May 2025)(CSI3013)2.jpg
  VIT Bhopal University/09.Information Technology (IT)/Foundation of blockchain technology(CSI3013)/Foundation of blockchain technology(May 2025)(CSI3013)3.jpg
  VIT Bhopal University/09.Information Technology (IT)/Foundation of blockchain technology(CSI3013)/Foundation of blockchain technology(May 2025)(CSI3013)4.jpg
  VIT Bhopal University/09.Information Technology (IT)/Foundation of blockchain technology(CSI3013)/Foundation of blockchain technology(May 2025)(CSI3013)5.jpg
  VIT Bhopal University/09.Information Technology (IT)/Foundation of blockchain technology(CSI3013)/README.md
Labels: enhancement, Advanced, SSOC S4

#653 Uploaded 25 PYQs for Industrial Engineering(MEE1014) and Strength of materials(MEE2002) #650
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(May 2020)(MEE1014)1.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(May 2020)(MEE1014)10.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(May 2020)(MEE1014)11.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(May 2020)(MEE1014)12.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(May 2020)(MEE1014)13.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(May 2020)(MEE1014)2.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(May 2020)(MEE1014)3.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(May 2020)(MEE1014)4.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(May 2020)(MEE1014)5.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(May 2020)(MEE1014)6.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(May 2020)(MEE1014)7.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(May 2020)(MEE1014)8.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Industrial Engineering(MEE1014)/Industrial Engineering(May 2020)(MEE1014)9.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Strength of materials(MEE2002)/README.md
  VIT Bhopal University/03.Mechanical Engineering (ME)/Strength of materials(MEE2002)/Strength of materials(May 2019)(MEE2002)1.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Strength of materials(MEE2002)/Strength of materials(May 2019)(MEE2002)10.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Strength of materials(MEE2002)/Strength of materials(May 2019)(MEE2002)11.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Strength of materials(MEE2002)/Strength of materials(May 2019)(MEE2002)14.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Strength of materials(MEE2002)/Strength of materials(May 2019)(MEE2002)2.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Strength of materials(MEE2002)/Strength of materials(May 2019)(MEE2002)3.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Strength of materials(MEE2002)/Strength of materials(May 2019)(MEE2002)4.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Strength of materials(MEE2002)/Strength of materials(May 2019)(MEE2002)5.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Strength of materials(MEE2002)/Strength of materials(May 2019)(MEE2002)6.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Strength of materials(MEE2002)/Strength of materials(May 2019)(MEE2002)7.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Strength of materials(MEE2002)/Strength of materials(May 2019)(MEE2002)8.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Strength of materials(MEE2002)/Strength of materials(May 2019)(MEE2002)9.pdf
Labels: enhancement, Advanced, SSOC S4

#655 Upload the pyq of chemical engineering
  MAKAUT/Chemical Engineering/5th semester/btech-che-5-sem-chemical-process-technology-1-2010.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-5-sem-chemical-process-technology-1-2011.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-5-sem-chemical-process-technology-1-2012.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-5-sem-chemical-process-technology-1-s3-2012.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-5-sem-chemical-reaction-engineering-2010.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-5-sem-chemical-reaction-engineering-2012.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-5-sem-chemical-reaction-engineering-s3-2012.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-5-sem-economics-for-engineers-2012.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-5-sem-electrical-machines-design-2012.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-5-sem-machine-design-2010.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-5-sem-machine-design-2011.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-5-sem-machine-design-2012.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-5-sem-machine-design-s3-2012.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-5-sem-process-heat-transfer-2010.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-5-sem-process-heat-transfer-2011.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-5-sem-process-heat-transfer-2012.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-5-sem-separation-process-1-2012.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-5-sem-separation-processes-1-2011.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-5-sem-separation-processes-1-2012.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-502-chemical-reaction-engineering-2012.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-503-chemical-process-technology-1-2011.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-503-chemical-process-technology-2012.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-504a-electrical-machines-design-2012.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-505-separation-process-1-2011.pdf
  MAKAUT/Chemical Engineering/5th semester/btech-che-505-separation-process-1-2012.pdf
Labels: enhancement, Advanced, SSOC S4

#657 Uploaded 25 PYQs for Operation Research(MEE1024) and Spanish(ESP1001) #654
  VIT Bhopal University/03.Mechanical Engineering (ME)/Operation Research(MEE1024)/Operation research(May 2020)(MEE1024)1.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Operation Research(MEE1024)/Operation research(May 2020)(MEE1024)2.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Operation Research(MEE1024)/Operation research(May 2020)(MEE1024)3.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Operation Research(MEE1024)/Operation research(May 2020)(MEE1024)4.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Operation Research(MEE1024)/Operation research(May 2020)(MEE1024)5.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Operation Research(MEE1024)/Operation research(May 2020)(MEE1024)6.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Operation Research(MEE1024)/Operation research(May 2020)(MEE1024)7.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Operation Research(MEE1024)/README.md
  VIT Bhopal University/11.Management and Humanities/Spanish(ESP1001)/README.md
  VIT Bhopal University/11.Management and Humanities/Spanish(ESP1001)/Spanish(Dec 2019)(ESP1001)1.pdf
  VIT Bhopal University/11.Management and Humanities/Spanish(ESP1001)/Spanish(Dec 2019)(ESP1001)12.jpg
  VIT Bhopal University/11.Management and Humanities/Spanish(ESP1001)/Spanish(Dec 2019)(ESP1001)13.pdf
  VIT Bhopal University/11.Management and Humanities/Spanish(ESP1001)/Spanish(Dec 2019)(ESP1001)14.jpg
  VIT Bhopal University/11.Management and Humanities/Spanish(ESP1001)/Spanish(Dec 2019)(ESP1001)15.pdf
  VIT Bhopal University/11.Management and Humanities/Spanish(ESP1001)/Spanish(Dec 2019)(ESP1001)16.pdf
  VIT Bhopal University/11.Management and Humanities/Spanish(ESP1001)/Spanish(Dec 2019)(ESP1001)18.jpg
  VIT Bhopal University/11.Management and Humanities/Spanish(ESP1001)/Spanish(Dec 2019)(ESP1001)19.jpg
  VIT Bhopal University/11.Management and Humanities/Spanish(ESP1001)/Spanish(Dec 2019)(ESP1001)2.pdf
  VIT Bhopal University/11.Management and Humanities/Spanish(ESP1001)/Spanish(Dec 2019)(ESP1001)3.pdf
  VIT Bhopal University/11.Management and Humanities/Spanish(ESP1001)/Spanish(Dec 2019)(ESP1001)4.pdf
  VIT Bhopal University/11.Management and Humanities/Spanish(ESP1001)/Spanish(Dec 2019)(ESP1001)5.jpg
  VIT Bhopal University/11.Management and Humanities/Spanish(ESP1001)/Spanish(Dec 2019)(ESP1001)6.jpg
  VIT Bhopal University/11.Management and Humanities/Spanish(ESP1001)/Spanish(Dec 2019)(ESP1001)7.jpg
  VIT Bhopal University/11.Management and Humanities/Spanish(ESP1001)/Spanish(Dec 2024)(ESP1001)11.jpg
  VIT Bhopal University/11.Management and Humanities/Spanish(ESP1001)/Spanish(Dec 2024)(ESP1001)20.jpg
  VIT Bhopal University/11.Management and Humanities/Spanish(ESP1001)/Spanish(Dec 2024)(ESP1001)8.jpg
  VIT Bhopal University/11.Management and Humanities/Spanish(ESP1001)/Spanish(Dec 2024)(ESP1001)9.jpg
Labels: enhancement, Advanced, SSOC S4

#659 Uploaded 25 PYQs for Sensors and Instrumentations(ECE1005),Thermal energy systems(MEE2003),Open source programming(ITE1008) and Virtualization(CSE4011) #658
  VIT Bhopal University/01. Computer Engineering/Open source programming(ITE1008)/Open source programming(Dec 2020)(ITE1008)1.pdf
  VIT Bhopal University/01. Computer Engineering/Open source programming(ITE1008)/Open source programming(Dec 2020)(ITE1008)2.pdf
  VIT Bhopal University/01. Computer Engineering/Open source programming(ITE1008)/Open source programming(Dec 2020)(ITE1008)3.pdf
  VIT Bhopal University/01. Computer Engineering/Open source programming(ITE1008)/Open source programming(Dec 2020)(ITE1008)6.pdf
  VIT Bhopal University/01. Computer Engineering/Open source programming(ITE1008)/README.md
  VIT Bhopal University/01. Computer Engineering/Virtualization(CSE4011)/README md
  VIT Bhopal University/01. Computer Engineering/Virtualization(CSE4011)/Virtualization(Dec 2019)(CSE4011)1.pdf
  VIT Bhopal University/01. Computer Engineering/Virtualization(CSE4011)/Virtualization(Dec 2019)(CSE4011)2.jpg
  VIT Bhopal University/01. Computer Engineering/Virtualization(CSE4011)/Virtualization(Dec 2019)(CSE4011)3.pdf
  VIT Bhopal University/01. Computer Engineering/Virtualization(CSE4011)/Virtualization(Dec 2019)(CSE4011)6.pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/Sensors and Instrumentations(ECE1005)/README.md
  VIT Bhopal University/02. Electronics & Communication Engineering/Sensors and Instrumentations(ECE1005)/Sensors and Instrumentations(Dec 2019)(ECE1005)1.pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/Sensors and Instrumentations(ECE1005)/Sensors and Instrumentations(Dec 2019)(ECE1005)2.pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/Sensors and Instrumentations(ECE1005)/Sensors and Instrumentations(Dec 2019)(ECE1005)3.pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/Sensors and Instrumentations(ECE1005)/Sensors and Instrumentations(Dec 2019)(ECE1005)4.pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/Sensors and Instrumentations(ECE1005)/Sensors and Instrumentations(Dec 2019)(ECE1005)5.pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/Sensors and Instrumentations(ECE1005)/Sensors and Instrumentations(Dec 2019)(ECE1005)7.pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/Sensors and Instrumentations(ECE1005)/Sensors and Instrumentations(Dec 2019)(ECE1005)8.pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/Sensors and Instrumentations(ECE1005)/Sensors and Instrumentations(Dec 2019)(ECE1005)9.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Thermal energy systems(MEE2003)/README.md
  VIT Bhopal University/03.Mechanical Engineering (ME)/Thermal energy systems(MEE2003)/Thermal energy systems(Dec 2019)(MEE2003)1.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Thermal energy systems(MEE2003)/Thermal energy systems(Dec 2019)(MEE2003)2.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Thermal energy systems(MEE2003)/Thermal energy systems(Dec 2019)(MEE2003)3.jpg
  VIT Bhopal University/03.Mechanical Engineering (ME)/Thermal energy systems(MEE2003)/Thermal energy systems(Dec 2019)(MEE2003)4.jpg
  VIT Bhopal University/03.Mechanical Engineering (ME)/Thermal energy systems(MEE2003)/Thermal energy systems(Dec 2019)(MEE2003)5.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Thermal energy systems(MEE2003)/Thermal energy systems(Dec 2019)(MEE2003)6.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Thermal energy systems(MEE2003)/Thermal energy systems(Dec 2019)(MEE2003)7.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Thermal energy systems(MEE2003)/Thermal energy systems(Dec 2019)(MEE2003)8.jpg
  VIT Bhopal University/03.Mechanical Engineering (ME)/Thermal energy systems(MEE2003)/Thermal energy systems(Dec 2019)(MEE2003)9.jpg
Labels: enhancement, Advanced, SSOC S4

#664 Added PYQ for 4th year Anna-University
  Anna University/01. Computer Science Engineering/Computer Networks (CS-3591)/CN (2010) (CS-3591).pdf
  Anna University/01. Computer Science Engineering/Computer Networks (CS-3591)/CN (2011) (CS-3591).pdf
  Anna University/01. Computer Science Engineering/Computer Networks (CS-3591)/CN (2012) (CS-3591).pdf
  Anna University/01. Computer Science Engineering/Computer Networks (CS-3591)/CN (2013) (CS-3591).pdf
  Anna University/01. Computer Science Engineering/Computer Networks (CS-3591)/CN (2015) (CS-3591).pdf
  Anna University/01. Computer Science Engineering/Computer Networks (CS-3591)/CN (2016) (CS-3591).pdf
  Anna University/01. Computer Science Engineering/Computer Networks (CS-3591)/CN (2017) (CS-3591).pdf
  Anna University/01. Computer Science Engineering/Computer Networks (CS-3591)/CN (2018) (CS-3591).pdf
  Anna University/01. Computer Science Engineering/Computer Networks (CS-3591)/CN (2019) (CS-3591).pdf
  Anna University/01. Computer Science Engineering/Computer Networks (CS-3591)/CN (2020) (CS-3591).pdf
  Anna University/01. Computer Science Engineering/Computer Networks (CS-3591)/CN (2021) (CS-3591).pdf
  Anna University/01. Computer Science Engineering/Computer Networks (CS-3591)/CN (2022) (CS-3591).pdf
  Anna University/01. Computer Science Engineering/Computer Networks (CS-3591)/CN (2023) (CS-3591).pdf
  Anna University/01. Computer Science Engineering/Computer Networks (CS-3591)/CN (2024) (CS-3591).pdf
  Anna University/01. Computer Science Engineering/Computer Networks (CS-3591)/CN (2025) (CS-3591).pdf
  Anna University/02. Electrical Engineering/DSP (2010) (EC-3492).pdf
  Anna University/02. Electrical Engineering/DSP (2011) (EC-3492).pdf
  Anna University/02. Electrical Engineering/DSP (2012) (EC-3492).pdf
  Anna University/02. Electrical Engineering/DSP (2013) (EC-3492).pdf
  Anna University/02. Electrical Engineering/DSP (2014) (EC-3492).pdf
  Anna University/02. Electrical Engineering/DSP (2015) (EC-3492).pdf
  Anna University/02. Electrical Engineering/DSP (2016) (EC-3492).pdf
  Anna University/02. Electrical Engineering/DSP (2017) (EC-3492).pdf
  Anna University/02. Electrical Engineering/DSP (2018) (EC-3492).pdf
  Anna University/02. Electrical Engineering/DSP (2019) (EC-3492).pdf
  Anna University/02. Electrical Engineering/DSP (2020) (EC-3492).pdf
  Anna University/02. Electrical Engineering/DSP (2021) (EC-3492).pdf
  Anna University/02. Electrical Engineering/DSP (2022) (EC-3492).pdf
  Anna University/02. Electrical Engineering/DSP (2024) (EC-3492).pdf
  Anna University/02. Electrical Engineering/DSP (2025) (EC-3492).pdf
  Anna University/03. Information Technology/CC (2010) (CS-6708).pdf
  Anna University/03. Information Technology/CC (2011) (CS-6708).pdf
  Anna University/03. Information Technology/CC (2013) (CS-6708).pdf
  Anna University/03. Information Technology/CC (2014) (CS-6708).pdf
  Anna University/03. Information Technology/CC (2015) (CS-6708).pdf
  Anna University/03. Information Technology/CC (2016) (CS-6708).pdf
  Anna University/03. Information Technology/CC (2017) (CS-6708).pdf
  Anna University/03. Information Technology/CC (2018) (CS-6708).pdf
  Anna University/03. Information Technology/CC (2019) (CS-6708).pdf
  Anna University/03. Information Technology/CC (2020) (CS-6708).pdf
  Anna University/03. Information Technology/CC (2021) (CS-6708).pdf
  Anna University/03. Information Technology/CC (2022) (CS-6708).pdf
  Anna University/03. Information Technology/CC (2023) (CS-6708).pdf
  Anna University/03. Information Technology/CC (2024) (CS-6708).pdf
  Anna University/03. Information Technology/CC (2025) (CS-6708).pdf
  Anna-University/R2021/All Branches PYQ/Fourth Year/Semester 1/Computer Integrated Manufacturing [ME3792]/PYQ [ME3792]/Computer Integrated Manufacturing (Dec 2024) [ME3792].pdf
  Anna-University/R2021/All Branches PYQ/Fourth Year/Semester 1/Computer Integrated Manufacturing [ME3792]/PYQ [ME3792]/Computer Integrated Manufacturing (Dec XXXX) [ME3792].pdf
  Anna-University/R2021/All Branches PYQ/Fourth Year/Semester 1/Computer Integrated Manufacturing [ME3792]/[ME3792]/ME3792 Computer Integrated Manufacturing Notes Notes Notes Notes.pdf
  Anna-University/R2021/All Branches PYQ/Fourth Year/Semester 1/Industrial Management [GE3792]/PYQ [GE3792]/Industrial Management (Dec 2024) [GE3792].pdf
  Anna-University/R2021/All Branches PYQ/Fourth Year/Semester 1/Industrial Management [GE3792]/PYQ [GE3792]/Industrial Management (Dec XXXX) [GE3792].pdf
  Anna-University/R2021/All Branches PYQ/Fourth Year/Semester 1/Industrial Management [GE3792]/[GE3792]/Ge3792 Industrial Management Notes Notes Notes Month XXXX Notes Notes Notes.pdf
  Anna-University/R2021/All Branches PYQ/Fourth Year/Semester 1/Mechatronics and IoT [ME3791]/PYQ [ME3791]/Mechatronics and IoT (Dec 2024) [ME3791].pdf
  Anna-University/R2021/All Branches PYQ/Fourth Year/Semester 1/Mechatronics and IoT [ME3791]/PYQ [ME3791]/Mechatronics and IoT (Dec XXXX) [ME3791].pdf
  Anna-University/R2021/All Branches PYQ/Fourth Year/Semester 1/Mechatronics and IoT [ME3791]/[ME3791]/Me3791 Mechatronics And Iot Notes Notes Notes Month XXXX Notes Notes Notes Notes.pdf
Labels: enhancement, Advanced, SSOC S4

#665 Added PYQs for IT for 3rd semester
  Chennai-Institute-of-Technology-Kanchipuram-TN/Information Technology/3rd-Sem/Design and Analysis of Algorithms (IT4302)/DAA 1.pdf
  Chennai-Institute-of-Technology-Kanchipuram-TN/Information Technology/3rd-Sem/Design and Analysis of Algorithms (IT4302)/DAA 2.pdf
  Chennai-Institute-of-Technology-Kanchipuram-TN/Information Technology/3rd-Sem/Design and Analysis of Algorithms (IT4302)/DAA 3.pdf
  Chennai-Institute-of-Technology-Kanchipuram-TN/Information Technology/3rd-Sem/Design and Analysis of Algorithms (IT4302)/DAA Dec2020.pdf
  Chennai-Institute-of-Technology-Kanchipuram-TN/Information Technology/3rd-Sem/Design and Analysis of Algorithms (IT4302)/DAA May2023.pdf
  Chennai-Institute-of-Technology-Kanchipuram-TN/Information Technology/3rd-Sem/Discrete Mathematics (MA4302)/DM 1.pdf
  Chennai-Institute-of-Technology-Kanchipuram-TN/Information Technology/3rd-Sem/Discrete Mathematics (MA4302)/DM 2.pdf
  Chennai-Institute-of-Technology-Kanchipuram-TN/Information Technology/3rd-Sem/Discrete Mathematics (MA4302)/DM 3.pdf
  Chennai-Institute-of-Technology-Kanchipuram-TN/Information Technology/3rd-Sem/Discrete Mathematics (MA4302)/DM 4.pdf
  Chennai-Institute-of-Technology-Kanchipuram-TN/Information Technology/3rd-Sem/Discrete Mathematics (MA4302)/DM 5.pdf
  Chennai-Institute-of-Technology-Kanchipuram-TN/Information Technology/3rd-Sem/Operating Systems (IT4301)/OS 1.pdf
  Chennai-Institute-of-Technology-Kanchipuram-TN/Information Technology/3rd-Sem/Operating Systems (IT4301)/OS 2.pdf
  Chennai-Institute-of-Technology-Kanchipuram-TN/Information Technology/3rd-Sem/Operating Systems (IT4301)/OS 3.pdf
  Chennai-Institute-of-Technology-Kanchipuram-TN/Information Technology/3rd-Sem/Operating Systems (IT4301)/OS 4.pdf
  Chennai-Institute-of-Technology-Kanchipuram-TN/Information Technology/3rd-Sem/Operating Systems (IT4301)/OS 5.pdf
Labels: enhancement, Beginner, SSOC S4

#666 Upload pyq of ceramic technology of 7th semester
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-advanced-ceramics-2-2009.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-advanced-ceramics-2-2010.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-advanced-ceramics-2-2011.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-advanced-ceramics-2-2012.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-bio-ceramics-2009.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-bio-ceramics-2011.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-bio-ceramics-2012.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-bioceramics-2010.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-financial-management-and-accounts-2009.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-financial-management-and-accounts-2010.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-financial-management-and-accounts-2011.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-financial-management-and-accounts-2012.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-instrumentation-and-process-control-2009.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-instrumentation-and-process-control-2010.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-instrumentation-and-process-control-2011.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-instrumentation-and-process-control-2012.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-oxide-ceramics-2010.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-oxide-ceramics-2011.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-oxide-ceramics-2012.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-physical-ceramics-2009.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-physical-ceramics-2010.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-physical-ceramics-2011.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-physical-ceramics-2012.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-physical-ceramics-v2-2010.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-quality-assurance-2009.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-quality-assurance-2011.pdf
  MAKAUT/Cermaic Technology/7th Semester/btech-ct-7-sem-quality-assurance-2012.pdf
Labels: enhancement, Advanced, SSOC S4

#668 [Task 2.3.11] PYQ Addition #78
  MAKAUT_BCA/1/bca-1-sem-digital-electronics-bcac-102-2023.pdf
  MAKAUT_BCA/1/bca-1-sem-programming-for-problem-solving-bcac-101-2023.pdf
  MAKAUT_BCA/1/bca-1-sem-soft-skills-bcca101-2023.pdf
  MAKAUT_BCA/1/bsc-1-sem-e-learning-ge1b-20-2023.pdf
  MAKAUT_BCA/2/bca-2-sem-computer-architecture-bcac202-2023.pdf
  MAKAUT_BCA/2/bca-2-sem-discrete-structures-bcac201-2023.pdf
  MAKAUT_BCA/2/bca-2-sem-environmental-science-bcaa201-2023.pdf
  MAKAUT_BCA/2/bsc-3-sem-the-language-of-graphic-design-basics-and-beyond-ge2b-05-2023.pdf
  MAKAUT_BCA/3/bca-3-sem-data-structure-and-algorithm-bcac303-2023.pdf
  MAKAUT_BCA/3/bca-3-sem-object-oriented-programming-bcac301-2023.pdf
  MAKAUT_BCA/3/bca-3-sem-operating-system-bcac302-2023.pdf
  MAKAUT_BCA/3/bca-3-sem-value-and-ethics-of-profession-bcas301-2023.pdf
  MAKAUT_BCA/3/bsc-3-sem-computer-basics-and-multimedia-software-ge4b-17t-2024.pdf
  MAKAUT_BCA/4/bca-4-sem-database-management-system-bcac401-2024.pdf
  MAKAUT_BCA/4/bca-4-sem-entrepreneurship-bcas401-2024.pdf
  MAKAUT_BCA/4/bca-4-sem-python-programming-bcac403-2024.pdf
  MAKAUT_BCA/4/bca-4-sem-software-engineering-bcac402-2024.pdf
  MAKAUT_BCA/4/bsc-2-sem-mathematics-for-computing-ge3b-04-2024.pdf
  MAKAUT_BCA/5/CN QUESTION PAPER.pdf
  MAKAUT_BCA/5/IS.pdf
  MAKAUT_BCA/5/IT QUESTION PAPER.pdf
  MAKAUT_BCA/6/CY.pdf
  MAKAUT_BCA/6/EC.pdf
  MAKAUT_BCA/6/U1.pdf
Labels: enhancement, Advanced, SSOC S4

#671 Uploaded 25 PYQs for Alternative Fuels(MEE1012),Android Programming(SWE2008),Foundations of data science(MDI3002) and Urban community development(BHUM108L) #660
  VIT Bhopal University/01. Computer Engineering/Android Programming(SWE2008)/Android Programming(feb 2024)(SWE2008).8.jpg
  VIT Bhopal University/01. Computer Engineering/Android Programming(SWE2008)/Android Programming(feb 2024)(SWE2008).jpg
  VIT Bhopal University/01. Computer Engineering/Android Programming(SWE2008)/Android Programming(feb 2024)(SWE2008)2.jpg
  VIT Bhopal University/01. Computer Engineering/Android Programming(SWE2008)/Android Programming(feb 2024)(SWE2008)3.jpg
  VIT Bhopal University/01. Computer Engineering/Foundations of data science(MDI3002)/Foundations of data science(May 2025)(MDI3002).6.jpg
  VIT Bhopal University/01. Computer Engineering/Foundations of data science(MDI3002)/Foundations of data science(May 2025)(MDI3002).7.jpg
  VIT Bhopal University/01. Computer Engineering/Foundations of data science(MDI3002)/Foundations of data science(May 2025)(MDI3002).8.jpg
  VIT Bhopal University/01. Computer Engineering/Foundations of data science(MDI3002)/Foundations of data science(May 2025)(MDI3002).jpg
  VIT Bhopal University/01. Computer Engineering/Foundations of data science(MDI3002)/Foundations of data science(May 2025)(MDI3002)10.jpg
  VIT Bhopal University/01. Computer Engineering/Foundations of data science(MDI3002)/Foundations of data science(May 2025)(MDI3002)2.jpg
  VIT Bhopal University/01. Computer Engineering/Foundations of data science(MDI3002)/Foundations of data science(May 2025)(MDI3002)3.jpg
  VIT Bhopal University/01. Computer Engineering/Foundations of data science(MDI3002)/Foundations of data science(May 2025)(MDI3002)4.jpg
  VIT Bhopal University/01. Computer Engineering/Foundations of data science(MDI3002)/Foundations of data science(May 2025)(MDI3002)9.jpg
  VIT Bhopal University/01. Computer Engineering/Foundations of data science(MDI3002)/README.md
  VIT Bhopal University/03.Mechanical Engineering (ME)/Alternative Fuels(MEE1012)/Alternative Fuels(dec 2020)(MEE1012).6.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Alternative Fuels(MEE1012)/Alternative Fuels(dec 2020)(MEE1012).7.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Alternative Fuels(MEE1012)/Alternative Fuels(dec 2020)(MEE1012).8.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Alternative Fuels(MEE1012)/Alternative Fuels(dec 2020)(MEE1012).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Alternative Fuels(MEE1012)/Alternative Fuels(dec 2020)(MEE1012)10.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Alternative Fuels(MEE1012)/Alternative Fuels(dec 2020)(MEE1012)2.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Alternative Fuels(MEE1012)/Alternative Fuels(dec 2020)(MEE1012)3.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Alternative Fuels(MEE1012)/Alternative Fuels(dec 2020)(MEE1012)4.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Alternative Fuels(MEE1012)/Alternative Fuels(dec 2020)(MEE1012)9.pdf
  VIT Bhopal University/11.Management and Humanities/Urban community development(BHUM108L)/README.md
  VIT Bhopal University/11.Management and Humanities/Urban community development(BHUM108L)/Urban community development(May 2023)(BHUM108L).jpg
  VIT Bhopal University/11.Management and Humanities/Urban community development(BHUM108L)/Urban community development(May 2023)(BHUM108L)3.jpg
  VIT Bhopal University/11.Management and Humanities/Urban community development(BHUM108L)/Urban community development(May 2025)(BHUM108L)2.jpg
Labels: enhancement, Advanced, SSOC S4

#673 PYQ+
  J.C. Bose UST, YMCA, Faridabad/BCA/2nd SEM/CMR.pdf
  J.C. Bose UST, YMCA, Faridabad/BCA/2nd SEM/CN.pdf
  J.C. Bose UST, YMCA, Faridabad/BCA/2nd SEM/DE (ll).pdf
  J.C. Bose UST, YMCA, Faridabad/BCA/2nd SEM/EVS.pdf
  J.C. Bose UST, YMCA, Faridabad/BCA/2nd SEM/Micro Eco.pdf
  J.C. Bose UST, YMCA, Faridabad/BCA/2nd SEM/OS.pdf
Labels: enhancement, Beginner, SSOC S4

#674 Upload pyq of biotechnology and leather technology of 4th semester
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-database-management-system-and-computer-network-2012.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-database-management-system-and-computer-network-2013.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-database-management-system-and-computer-networking-2010.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-database-management-system-and-computer-networking-2011.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-industrial-microbiology-and-enzyme-technology-2010.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-industrial-microbiology-and-enzyme-technology-2011.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-industrial-microbiology-and-enzyme-technology-2012.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-industrial-microbiology-and-enzyme-technology-2013.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-industrial-microbiology-and-enzyme-technology-v2-2012.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-industrial-microbiology-and-enzyme-technology-v2-2013.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-industrial-stoichiometry-2012.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-industrial-stoichiometry-2013.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-industrial-stoichiometry-v2-2012.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-industrial-stoichiometry-v2-2013.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-molecular-biology-2012.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-molecular-biology-2013.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-molecular-biology-and-r-dna-technology-2012.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-molecular-biology-and-rdna-technology-2011.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-molecular-biology-and-rdna-technology-2013.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-numerical-methods-2012.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-numerical-methods-2013.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-thermodynamics-and-kinetics-2012.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-thermodynamics-and-kinetics-2013.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-transfer-operation-1-2012.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-transfer-operation-1-2013.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-transfer-operation-1-s3-2013.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-transfer-operations-1-2011.pdf
  MAKAUT/Biotechnology and leather/4th semester/btech-bt-4-sem-transfer-operations-1-2012.pdf
Labels: enhancement, Advanced, SSOC S4

#685 Added PYQs for Computer Engineering 2nd,3rd and 4th Sems
  NIT_Kurukshetra/Computer Engineering/2nd Sem/Data Structures(ITPC 100)/ITPC12 ES 2018.pdf
  NIT_Kurukshetra/Computer Engineering/2nd Sem/Data Structures(ITPC 100)/ITPC12 ES 2019.pdf
  NIT_Kurukshetra/Computer Engineering/2nd Sem/Data Structures(ITPC 100)/ITPC12 ES 2021.pdf
  NIT_Kurukshetra/Computer Engineering/2nd Sem/Data Structures(ITPC 100)/ITPC12 ES1 2018.pdf
  NIT_Kurukshetra/Computer Engineering/2nd Sem/Data Structures(ITPC 100)/ITPC12 ES1 2019.pdf
  NIT_Kurukshetra/Computer Engineering/2nd Sem/Data Structures(ITPC 100)/ITPC12 ES2 2019.pdf
  NIT_Kurukshetra/Computer Engineering/2nd Sem/Data Structures(ITPC 100)/ITPC12 ES3 2019.pdf
  NIT_Kurukshetra/Computer Engineering/2nd Sem/Data Structures(ITPC 100)/ITPC12 MS 2021.pdf
  NIT_Kurukshetra/Computer Engineering/2nd Sem/Data Structures(ITPC 100)/ITPC12 MS 2022.pdf
  NIT_Kurukshetra/Computer Engineering/2nd Sem/Data Structures(ITPC 100)/ITPC12 MS1 2021.pdf
  NIT_Kurukshetra/Computer Engineering/2nd Sem/Data Structures(ITPC 100)/ITPC12 MS1 2025.pdf
  NIT_Kurukshetra/Computer Engineering/3rd Sem/Computer Organization and Architecture(CSPC 203)/CSPC29 ES 2018.pdf
  NIT_Kurukshetra/Computer Engineering/3rd Sem/Computer Organization and Architecture(CSPC 203)/CSPC29 ES 2019.pdf
  NIT_Kurukshetra/Computer Engineering/3rd Sem/Computer Organization and Architecture(CSPC 203)/CSPC29 ES 2020.pdf
  NIT_Kurukshetra/Computer Engineering/3rd Sem/Computer Organization and Architecture(CSPC 203)/CSPC29 ES 2021.pdf
  NIT_Kurukshetra/Computer Engineering/3rd Sem/Computer Organization and Architecture(CSPC 203)/CSPC29 ES1 2018.pdf
  NIT_Kurukshetra/Computer Engineering/3rd Sem/Computer Organization and Architecture(CSPC 203)/CSPC29 ES1 2019.pdf
  NIT_Kurukshetra/Computer Engineering/3rd Sem/Computer Organization and Architecture(CSPC 203)/CSPC29 ES1 2020.pdf
  NIT_Kurukshetra/Computer Engineering/3rd Sem/Computer Organization and Architecture(CSPC 203)/CSPC29 ES1 2021.pdf
  NIT_Kurukshetra/Computer Engineering/3rd Sem/Computer Organization and Architecture(CSPC 203)/CSPC29 MS 2020.pdf
  NIT_Kurukshetra/Computer Engineering/3rd Sem/Computer Organization and Architecture(CSPC 203)/CSPC29 MS1 2020.pdf
  NIT_Kurukshetra/Computer Engineering/3rd Sem/Computer Organization and Architecture(CSPC 203)/CSPC29 MS1 2021.pdf
  NIT_Kurukshetra/Computer Engineering/3rd Sem/Computer Organization and Architecture(CSPC 203)/CSPC29 MS2 2021.pdf
  NIT_Kurukshetra/Computer Engineering/4th Sem/Computer Networks(CSPC 202)/CSPC26 ES2 2019.pdf
Labels: enhancement, Advanced, SSOC S4

#676 Upload pyq of information technology
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-advance-data-communication-and-coding-2017.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-advanced-data-communication-and-coding-2016.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-cloud-computing-2015.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-cloud-computing-2017.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-control-system-2019.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-data-warehousing-and-data-mining-2015.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-data-warehousing-and-data-mining-2016.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-data-warehousing-and-data-mining-2017.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-distributed-operating-system-2015.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-distributed-operating-system-2016.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-distributed-operating-system-2019.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-e-commerce-2016.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-e-commerce-2017.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-e-commerce-2018.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-e-commerce-2019.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-e-commerce-it-703a-2020.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-internet-technology-2017.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-internet-technology-2018.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-internet-technology-2019.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-internet-technology-it-701-2020.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-micro-electronics-and-vlsi-design-2016.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-microelectronics-and-vlsi-design-2017.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-mobile-computing-it-704e-2020.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-multimedia-2016.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-multimedia-2017.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-multimedia-2018.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-multimedia-2019.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-multimedia-it-702-2020.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-soft-computing-2016.pdf
  MAKAUT/Information Technology/7th Semester/btech-it-7-sem-soft-computing-2017.pdf
Labels: enhancement, Advanced, SSOC S4

#678 Uploaded 25 PYQs for EMD(ECE1002) and Introduction to Bitcoin(BCSE325L) #672
  VIT Bhopal University/01. Computer Engineering/Introduction to Bitcoin(BCSE325L)/Introduction to Bitcoin(May 2025)(BCSE325L).6.jpg
  VIT Bhopal University/01. Computer Engineering/Introduction to Bitcoin(BCSE325L)/Introduction to Bitcoin(May 2025)(BCSE325L).7.jpg
  VIT Bhopal University/01. Computer Engineering/Introduction to Bitcoin(BCSE325L)/Introduction to Bitcoin(May 2025)(BCSE325L).jpg
  VIT Bhopal University/01. Computer Engineering/Introduction to Bitcoin(BCSE325L)/Introduction to Bitcoin(May 2025)(BCSE325L)2.jpg
  VIT Bhopal University/01. Computer Engineering/Introduction to Bitcoin(BCSE325L)/Introduction to Bitcoin(May 2025)(BCSE325L)3.jpg
  VIT Bhopal University/01. Computer Engineering/Introduction to Bitcoin(BCSE325L)/Introduction to Bitcoin(May 2025)(BCSE325L)4.jpg
  VIT Bhopal University/01. Computer Engineering/Introduction to Bitcoin(BCSE325L)/README.md
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/EMD(May 2024)(ECE1002)1.pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/EMD(May 2024)(ECE1002)10.pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/EMD(May 2024)(ECE1002)11.pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/EMD(May 2024)(ECE1002)12.pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/EMD(May 2024)(ECE1002)13.pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/EMD(May 2024)(ECE1002)14.pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/EMD(May 2024)(ECE1002)15.pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/EMD(May 2024)(ECE1002)16.pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/EMD(May 2024)(ECE1002)17.jpg
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/EMD(May 2024)(ECE1002)18.jpg
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/EMD(May 2024)(ECE1002)19.jpg
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/EMD(May 2024)(ECE1002)2.pdf
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/EMD(May 2024)(ECE1002)3.jpg
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/EMD(May 2024)(ECE1002)4.jpg
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/EMD(May 2024)(ECE1002)5.jpg
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/EMD(May 2024)(ECE1002)6.jpg
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/EMD(May 2024)(ECE1002)7.jpg
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/EMD(May 2024)(ECE1002)8.jpg
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/EMD(May 2024)(ECE1002)9.jpg
  VIT Bhopal University/02. Electronics & Communication Engineering/EMD(ECE1002)/README.md
Labels: enhancement, Advanced, SSOC S4

#686 Upload pyq of biotechnology and leather technology of 5th semester
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-bio-informatics-1-2010.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-bioinformatics-1-2009.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-bioinformatics-1-2011.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-bioinformatics-1-2012.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-bioinformatics-2012.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-bioreactor-design-and-analysis-2009.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-bioreactor-design-and-analysis-2010.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-bioreactor-design-and-analysis-2011.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-bioreactor-design-and-analysis-2012.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-data-structure-and-algorithm-java-and-cpp-2012.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-genetics-2012.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-genetics-and-biostatistics-2009.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-genetics-and-biostatistics-2011.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-immunology-2009.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-immunology-2010.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-immunology-2011.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-immunology-2012.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-principles-and-practices-of-management-2012.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-transfer-operation-2-2009.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-transfer-operation-2-2010.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-transfer-operation-2-2012.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-transfer-operations-2-2011.pdf
  MAKAUT/Biotechnology and leather/5th semester/btech-bt-5-sem-transfer-operations-2-2012.pdf
Labels: enhancement, Advanced, SSOC S4

#692 Upload pyq of electronic and communication engineering of 8th semester
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ec-801c-satellite-communication-and-remote-sensing-2014.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ec-801c-satellite-communication-and-remote-sensing-2015.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ec-801c-satellite-communication-and-remote-sensing-2016.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ec-802c-renewable-energy-2014.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ec-802c-renewable-energy-2015.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ec-802c-renewable-energy-2016.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ec-802c-renewable-energy-2018.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ec-802f-communication-engineering-2012.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ec-802f-communication-engineering-2013.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ec-803b-embedded-system-2012.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ec-803e-modern-control-system-2012.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ec-804d-remote-sensing-2012.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ece-8-sem-advance-communication-system-2013.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ece-8-sem-digital-image-processing-2013.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ece-8-sem-embedded-system-2013.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ece-8-sem-internet-technology-2013.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ece-8-sem-medical-electronics-2013.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ece-8-sem-microwave-circuits-and-systems-2013.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ece-8-sem-mobile-computing-2013.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ece-8-sem-modern-control-system-2013.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ece-8-sem-remote-sensing-2013.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ece-8-sem-software-engineering-2013.pdf
  MAKAUT/Electonics and Communication Engineering/8th semester/btech-ece-8-sem-values-and-ethics-in-profession-2013.pdf
Labels: enhancement, Advanced, SSOC S4

#694 Uploaded 25 PYQs for Knowledge engineering(SWE2032),Foundations of data science(MDI3002),Iot(CSE3009) and Robotics(MEE1030) #689
  VIT Bhopal University/01. Computer Engineering/Foundations of data science(MDI3002)/Foundations of data science(May 2025)(MDI3002)1.jpg
  VIT Bhopal University/01. Computer Engineering/Foundations of data science(MDI3002)/Foundations of data science(May 2025)(MDI3002)6.jpg
  VIT Bhopal University/01. Computer Engineering/Foundations of data science(MDI3002)/Foundations of data science(May 2025)(MDI3002)7.jpg
  VIT Bhopal University/01. Computer Engineering/Iot(CSE3009)/Iot(May 2020)(CSE3009).pdf
  VIT Bhopal University/01. Computer Engineering/Iot(CSE3009)/Iot(May 2020)(CSE3009)10.pdf
  VIT Bhopal University/01. Computer Engineering/Iot(CSE3009)/Iot(May 2020)(CSE3009)11.pdf
  VIT Bhopal University/01. Computer Engineering/Iot(CSE3009)/Iot(May 2020)(CSE3009)12.jpg
  VIT Bhopal University/01. Computer Engineering/Iot(CSE3009)/Iot(May 2020)(CSE3009)2.pdf
  VIT Bhopal University/01. Computer Engineering/Iot(CSE3009)/Iot(May 2020)(CSE3009)6.pdf
  VIT Bhopal University/01. Computer Engineering/Iot(CSE3009)/README.md
  VIT Bhopal University/01. Computer Engineering/Knowledge engineering(SWE2032)/Knowledge engineering(May 2024)(SWE2032).jpg
  VIT Bhopal University/01. Computer Engineering/Knowledge engineering(SWE2032)/Knowledge engineering(May 2024)(SWE2032)2.jpg
  VIT Bhopal University/01. Computer Engineering/Knowledge engineering(SWE2032)/Knowledge engineering(May 2024)(SWE2032)3.jpg
  VIT Bhopal University/01. Computer Engineering/Knowledge engineering(SWE2032)/Knowledge engineering(May 2024)(SWE2032)4.jpg
  VIT Bhopal University/01. Computer Engineering/Knowledge engineering(SWE2032)/Knowledge engineering(May 2024)(SWE2032)5.jpg
  VIT Bhopal University/01. Computer Engineering/Knowledge engineering(SWE2032)/Knowledge engineering(May 2024)(SWE2032)6.jpg
  VIT Bhopal University/01. Computer Engineering/Knowledge engineering(SWE2032)/Knowledge engineering(May 2024)(SWE2032)8.jpg
  VIT Bhopal University/01. Computer Engineering/Knowledge engineering(SWE2032)/README.md
  VIT Bhopal University/03.Mechanical Engineering (ME)/Robotics(MEE1030)/README.md
  VIT Bhopal University/03.Mechanical Engineering (ME)/Robotics(MEE1030)/Robotics(May 2020)(MEE1030).pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Robotics(MEE1030)/Robotics(May 2020)(MEE1030)2.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Robotics(MEE1030)/Robotics(May 2020)(MEE1030)3.jpg
  VIT Bhopal University/03.Mechanical Engineering (ME)/Robotics(MEE1030)/Robotics(May 2020)(MEE1030)4.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Robotics(MEE1030)/Robotics(May 2020)(MEE1030)6.pdf
  VIT Bhopal University/03.Mechanical Engineering (ME)/Robotics(MEE1030)/Robotics(May 2020)(MEE1030)7.pdf
Labels: enhancement, Advanced, SSOC S4

#696 Upload pyq of chemical engineering of 8th semester
  MAKAUT/Chemical Engineering/7th Semester/A
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-biotechnology-and-bio-medical-engineering-2011.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-biotechnology-and-bio-medical-engineering-v2-2011.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-biotechnology-and-biochemical-engineering-2010.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-biotechnology-and-biochemical-engineering-2013.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-biotechnology-and-biomedical-engineering-2012.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-environmental-engineering-2010.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-environmental-engineering-2011.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-environmental-engineering-2012.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-environmental-engineering-2013.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-environmental-engineering-v2-2010.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-nanotechnology-2013.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-operations-research-2010.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-operations-research-2011.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-operations-research-2012.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-operations-research-2013.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-operations-research-v2-2011.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-operations-research-v2-2012.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-safety-in-chemical-process-industries-2011.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-safety-in-chemical-process-industries-2012.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-safety-in-chemical-process-industries-2013.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-total-quality-management-2011.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-total-quality-management-2012.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-total-quality-management-2013.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-transport-phenomena-2011.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-transport-phenomena-2012.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-8-sem-transport-phenomena-2013.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-801-transport-phenomena-2011.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-801-transport-phenomena-2012.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-801-transport-phenomena-2013.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-804a-nanotechnology-2011.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-804a-nanotechnology-2012.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-804a-nanotechnology-2013.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-804b-operations-research-2012.pdf
  MAKAUT/Chemical Engineering/8th semester/btech-che-804b-operations-research-2013.pdf
Labels: enhancement, Advanced, SSOC S4

#712 Upload 25 PYQs for CSE1021 Introduction to Problem Solving #709
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021).jpg
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)10.pdf
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)11.pdf
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)12.docx
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)13.pdf
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)14.pdf
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)15.docx
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)16.pdf
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)17.pdf
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)18.pdf
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)19.pdf
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)2.pdf
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)20.docx
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)21.docx
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)22.docx
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)23.docx
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)24.docx
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)25.pdf
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)3.jpg
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)4.jpg
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)5.pdf
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)6.pdf
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)7.docx
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)8.docx
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/Introduction to Problem Solving(Dec 2023)(CSE1021)9.docx
  VIT Bhopal University/01. Computer Engineering/Introduction to Problem Solving(CSE1021)/README.md
Labels: enhancement, Advanced, SSOC S4

#719 PYQ+
  AKTU/1st Year/BTECH-SEM-1-ENGINEERING-PHYSICS(BAS-101)-2021.pdf
  AKTU/1st Year/BTECH-SEM-1-ENGINEERING-PHYSICS(BAS-101)-2022.pdf
  AKTU/1st Year/BTECH-SEM-1-ENGINEERING-PHYSICS(BAS-101)-2023.pdf
  AKTU/1st Year/BTECH-SEM-1-ENGINEERING-PHYSICS(BAS-101)-2024.pdf
  AKTU/1st Year/BTECH-SEM-1-ENGINNERING MATHEMATICS-1(BAS-103)-2023.pdf
  AKTU/1st Year/BTECH-SEM-1-ENGINNERING MATHEMATICS-1(BAS-103)-2024.pdf
  AKTU/1st Year/BTECH-SEM-1-ENGINNERING MATHEMATICS-2(BAS-203)-2023.pdf
  AKTU/1st Year/BTECH-SEM-1-ENGINNERING MATHEMATICS-2(BAS-203)-2024.pdf
  AKTU/1st Year/BTECH-SEM-1-FUNDAMENTALS OF ELECTRICAL ENGINEERING(BEE-101)-2021.pdf
  AKTU/1st Year/BTECH-SEM-1-FUNDAMENTALS OF ELECTRICAL ENGINEERING(BEE-101)-2022.pdf
  AKTU/1st Year/BTECH-SEM-1-FUNDAMENTALS OF ELECTRICAL ENGINEERING(BEE-101)-2023.pdf
  AKTU/1st Year/BTECH-SEM-1-FUNDAMENTALS OF ELECTRICAL ENGINEERING(BEE-101)-2024.pdf
  AKTU/1st Year/BTECH-SEM-1-PROGRAMMING-FOR-PROBLEM-SOLVING-(BCS-101)-2023.pdf
  AKTU/1st Year/BTECH-SEM-1-PROGRAMMING-FOR-PROBLEM-SOLVING-(BCS-101)-2024.pdf
  AKTU/1st Year/BTECH-SEM-2-ENGINEERING-PHYSICS(BAS-201)-2022.pdf
  AKTU/1st Year/BTECH-SEM-2-ENGINEERING-PHYSICS(BAS-201)-2023.pdf
  AKTU/1st Year/BTECH-SEM-2-ENGINEERING-PHYSICS(BAS-201)-2024.pdf
  AKTU/1st Year/BTECH-SEM-2-ENGINNERING MATHEMATICS-1(kAS-103t)-2022.pdf
  AKTU/1st Year/BTECH-SEM-2-ENGINNERING MATHEMATICS-1(kAS-103t)-2024.pdf
  AKTU/1st Year/BTECH-SEM-2-ENGINNERING MATHEMATICS-2(kAS-203t)-2022.pdf
  AKTU/1st Year/BTECH-SEM-2-FUNDAMENTALS OF ELECTRICAL ENGINEERING(BEE-201)-2022.pdf
  AKTU/1st Year/BTECH-SEM-2-FUNDAMENTALS OF ELECTRICAL ENGINEERING(BEE-201)-2023.pdf
  AKTU/1st Year/BTECH-SEM-2-FUNDAMENTALS OF ELECTRICAL ENGINEERING(BEE-201)-2024.pdf
  AKTU/1st Year/BTECH-SEM-2-PROGRAMMING-FOR-PROBLEM-SOLVING-(BCS-201)-2023.pdf
  AKTU/1st Year/BTECH-SEM-2-PROGRAMMING-FOR-PROBLEM-SOLVING-(BCS-201)-2024.pdf
Labels: enhancement, Advanced, SSOC S4

#715 Upload pyq of the instrumentation and control engineering department
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-analytical-instrumentation-2009.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-analytical-instrumentation-2010.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-analytical-instrumentation-2011.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-analytical-instrumentation-2012.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-analytical-instrumentation-2013.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-analytical-instrumentation-v2-2012.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-industrial-management-2009.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-industrial-management-2010.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-industrial-management-2011.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-industrial-management-2012.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-industrial-management-2013.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-non-conventional-energy-sources-2009.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-non-conventional-energy-sources-2010.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-non-conventional-energy-sources-2011.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-non-conventional-energy-sources-2012.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-non-conventional-energy-sources-2013.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-opto-electronics-and-laser-based-instrumentation-2010.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-power-plant-instrumentation-2010.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-power-plant-instrumentation-2011.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-power-plant-instrumentation-2012.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-power-plant-instrumentation-and-control-2013.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-values-and-ethics-in-profession-2010.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-values-and-ethics-in-profession-2011.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-values-and-ethics-in-profession-2012.pdf
  MAKAUT/Instrumentation and Control Engineering/8th semester/btech-ice-8-sem-values-and-ethics-in-profession-2013.pdf
Labels: enhancement, Advanced, SSOC S4

#728 PYQ+
  AKTU/1st Year/BTECH SEM-1 ENGINEERING CHEMISTRY (BAS-102) 2021.pdf
  AKTU/1st Year/BTECH SEM-1 ENGINEERING CHEMISTRY (BAS-102) 2022.pdf
  AKTU/1st Year/BTECH SEM-1 ENGINEERING CHEMISTRY (BAS-102) 2023.pdf
  AKTU/1st Year/BTECH SEM-1 ENGINEERING CHEMISTRY (BAS-102) 2024.pdf
  AKTU/1st Year/BTECH SEM-2 ENGINEERING CHEMISTRY (BAS-202) 2022.pdf
  AKTU/1st Year/BTECH SEM-2 ENGINEERING CHEMISTRY (BAS-202) 2023.pdf
  AKTU/1st Year/BTECH SEM-2 ENGINEERING CHEMISTRY (BAS-202) 2024.pdf
  AKTU/1st Year/BTECH-SEM-1-FUNDAMENTALS OF ELECTRONICS ENGINEERING(BEC-101)-2021.pdf
  AKTU/1st Year/BTECH-SEM-1-FUNDAMENTALS OF ELECTRONICS ENGINEERING(BEC-101)-2022.pdf
  AKTU/1st Year/BTECH-SEM-1-FUNDAMENTALS OF ELECTRONICS ENGINEERING(BEC-101)-2024.pdf
  AKTU/1st Year/BTECH-SEM-1-FUNDAMENTALS OF MECHANICAL ENGINEERING (BME-101)-2021.pdf
  AKTU/1st Year/BTECH-SEM-1-FUNDAMENTALS OF MECHANICAL ENGINEERING (BME-101)-2022.pdf
  AKTU/1st Year/BTECH-SEM-1-FUNDAMENTALS OF MECHANICAL ENGINEERING (BME-101)-2023.pdf
  AKTU/1st Year/BTECH-SEM-1-FUNDAMENTALS OF MECHANICAL ENGINEERING (BME-101)-2024.pdf
  AKTU/1st Year/BTECH-SEM-1-PROGRAMMING-FOR-PROBLEM-SOLVING-(BCS-101)-2021.pdf
  AKTU/1st Year/BTECH-SEM-1-PROGRAMMING-FOR-PROBLEM-SOLVING-(BCS-101)-2022.pdf
  AKTU/1st Year/BTECH-SEM-1-SOFT SKILLS-BAS-105-2024.pdf
  AKTU/1st Year/BTECH-SEM-2-FUNDAMENTALS OF ELECTRONICS ENGINEERING(BEC-201)-2022.pdf
  AKTU/1st Year/BTECH-SEM-2-FUNDAMENTALS OF ELECTRONICS ENGINEERING(BEC-201)-2023.pdf
  AKTU/1st Year/BTECH-SEM-2-FUNDAMENTALS OF ELECTRONICS ENGINEERING(BEC-201)-2024.pdf
  AKTU/1st Year/BTECH-SEM-2-FUNDAMENTALS OF MECHANICAL ENGINEERING (BME-201)-2022.pdf
  AKTU/1st Year/BTECH-SEM-2-FUNDAMENTALS OF MECHANICAL ENGINEERING (BME-201)-2023.pdf
  AKTU/1st Year/BTECH-SEM-2-FUNDAMENTALS OF MECHANICAL ENGINEERING (BME-201)-2024.pdf
  AKTU/1st Year/BTECH-SEM-2-PROGRAMMING-FOR-PROBLEM-SOLVING-(BCS-201)-2022.pdf
  AKTU/1st Year/BTECH-SEM-2-SOFT SKILLS-BAS-205-2023.pdf
  AKTU/1st Year/BTECH-SEM-2-SOFT SKILLS-BAS-205-2024.pdf
Labels: enhancement, Advanced, SSOC S4

#740 PYQ+
  AKTU/1st Year/BAS204-ENVIRONMENT-AND-ECOLOGY_watermark.pdf
  AKTU/1st Year/BTECH-SEM-1-SOFT SKILLS-BAS-105-2022.pdf
  AKTU/1st Year/BTECH-SEM-2-SOFT SKILLS-BAS-205-2022.pdf
  AKTU/1st Year/ENVIRONMENT-AND-ECOLOGY-BAS-104_watermark.pdf
  AKTU/1st Year/ENVIRONMENT-AND-ECOLOGY-BAS204_watermark.pdf
  AKTU/2nd Year/BTECH-SEM-3-Digital Electronics ( KOE049 )-2022.pdf
  AKTU/2nd Year/BTECH-SEM-3-Digital Electronics ( KOE049 )-2023.pdf
  AKTU/2nd Year/BTECH-SEM-3-Digital Electronics ( KOE049 )-2024.pdf
  AKTU/2nd Year/BTECH-SEM-3-Mathematics IV (KAS302H)-2022.pdf
  AKTU/2nd Year/BTECH-SEM-3-Mathematics IV (KAS302H)-2023.pdf
  AKTU/2nd Year/BTECH-SEM-3-Mathematics IV (KAS302H)-2024.pdf
  AKTU/2nd Year/BTECH-SEM-3-Technical Communication (KAS301)-2022.pdf
  AKTU/2nd Year/BTECH-SEM-3-Technical Communication (KAS301)-2023.pdf
  AKTU/2nd Year/BTECH-SEM-3-Technical Communication (KAS301)-2024.pdf
  AKTU/2nd Year/BTECH-SEM-3-Universal Human values (KVE 301H)-2022.pdf
  AKTU/2nd Year/BTECH-SEM-3-Universal Human values (KVE 301H)-2023.pdf
  AKTU/2nd Year/BTECH-SEM-3-Universal Human values (KVE 301H)-2024.pdf
  AKTU/2nd Year/BTECH-SEM-4-Digital Electronics ( KOE049 )-2022.pdf
  AKTU/2nd Year/BTECH-SEM-4-Digital Electronics ( KOE049 )-2023.pdf
  AKTU/2nd Year/BTECH-SEM-4-Digital Electronics ( KOE049 )-2024.pdf
  AKTU/2nd Year/BTECH-SEM-4-Mathematics IV (KAS402H)-2022.pdf
  AKTU/2nd Year/BTECH-SEM-4-Mathematics IV (KAS402H)-2023.pdf
  AKTU/2nd Year/BTECH-SEM-4-Mathematics IV (KAS402H)-2024.pdf
  AKTU/2nd Year/BTECH-SEM-4-Technical Communication (KAS401)-2022.pdf
  AKTU/2nd Year/BTECH-SEM-4-Technical Communication (KAS401)-2023.pdf
  AKTU/2nd Year/BTECH-SEM-4-Technical Communication (KAS401)-2024.pdf
  AKTU/2nd Year/BTECH-SEM-4-Universal Human values (KVE 401H)-2022.pdf
  AKTU/2nd Year/BTECH-SEM-4-Universal Human values (KVE 401H)-2023.pdf
  AKTU/2nd Year/BTECH-SEM-4-Universal Human values (KVE 401H)-2024.pdf
  AKTU/3rd Year/5th_sem_pyq/ASC
  AKTU/3rd Year/5th_sem_pyq/CD
  AKTU/3rd Year/5th_sem_pyq/COI
  AKTU/3rd Year/5th_sem_pyq/Computer_Graphics
  AKTU/3rd Year/5th_sem_pyq/DAA
  AKTU/3rd Year/5th_sem_pyq/DBMS
  AKTU/4th Year/Coming Soon
Labels: enhancement, Advanced, SSOC S4

#735 Upload pyq of instrumentation and control engineering
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-analytical-instrumentation-2009.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-analytical-instrumentation-2010.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-analytical-instrumentation-2011.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-analytical-instrumentation-2012.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-analytical-instrumentation-2013.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-analytical-instrumentation-v2-2012.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-industrial-management-2009.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-industrial-management-2010.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-industrial-management-2011.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-industrial-management-2012.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-industrial-management-2013.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-non-conventional-energy-sources-2009.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-non-conventional-energy-sources-2010.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-non-conventional-energy-sources-2011.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-non-conventional-energy-sources-2012.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-non-conventional-energy-sources-2013.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-opto-electronics-and-laser-based-instrumentation-2010.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-power-plant-instrumentation-2010.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-power-plant-instrumentation-2011.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-power-plant-instrumentation-2012.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-power-plant-instrumentation-and-control-2013.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-values-and-ethics-in-profession-2010.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-values-and-ethics-in-profession-2011.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-values-and-ethics-in-profession-2012.pdf
  MAKAUT/Instrumentation and Control Engineering/7th Semester/btech-ice-8-sem-values-and-ethics-in-profession-2013.pdf
Labels: enhancement, SSOC S4

#742 Upload pyq of chemical engineering
  MAKAUT/Chemical Engineering/7th Semester/A
  MAKAUT/Chemical Engineering/7th Semester/btech-ch-401-basic-environmental-engineering-and-elementary-biology-2012.pdf
  MAKAUT/Chemical Engineering/7th Semester/btech-ch-401-basic-environmental-engineering-and-elementary-biology-2013.pdf
  MAKAUT/Chemical Engineering/7th Semester/btech-ch-401-basic-environmental-engineering-and-elementary-biology-2014.pdf
  MAKAUT/Chemical Engineering/7th Semester/btech-ch-401-basic-environmental-engineering-and-elementary-biology-2015.pdf
  MAKAUT/Chemical Engineering/7th Semester/btech-ch-401-basic-environmental-engineering-and-elementary-biology-2016.pdf
  MAKAUT/Chemical Engineering/7th Semester/btech-ch-401-basic-environmental-engineering-and-elementary-biology-2017.pdf
  MAKAUT/Chemical Engineering/7th Semester/btech-ch-401-basic-environmental-engineering-and-elementary-biology-2019.pdf
  MAKAUT/Chemical Engineering/7th Semester/btech-ct-5-sem-metallurgy-2009.pdf
  MAKAUT/Chemical Engineering/7th Semester/btech-ct-5-sem-refractories-1-2009.pdf
  MAKAUT/Chemical Engineering/7th Semester/btech-ct-5-sem-whitewares-1-2009.pdf
Labels: enhancement, SSOC S4

#747 PYQ+
  AKTU/2nd Year/(SEM III) THEORY EXAMINATION 2021-22.pdf
  AKTU/2nd Year/BTECH SEM-3 Computer Organization and Architecture(KCS302H ) 2023.pdf
  AKTU/2nd Year/BTECH SEM-3 Computer Organization and Architecture(KCS302H ) 2024.pdf
  AKTU/2nd Year/BTECH-SEM-3-Computer System Security (KNC301H)-2022.pdf
  AKTU/2nd Year/BTECH-SEM-3-Computer System Security (KNC301H)-2023.pdf
  AKTU/2nd Year/BTECH-SEM-3-Computer System Security (KNC301H)-2024.pdf
  AKTU/2nd Year/BTECH-SEM-3-Data Structure (KCS301H)-2022.pdf
  AKTU/2nd Year/BTECH-SEM-3-Data Structure (KCS301H)-2023.pdf
  AKTU/2nd Year/BTECH-SEM-3-Data Structure (KCS301H)-2024.pdf
  AKTU/2nd Year/BTECH-SEM-3-Python Programming (KNC302H)-2022.pdf
  AKTU/2nd Year/BTECH-SEM-3-Python Programming (KNC302H)-2023.pdf
  AKTU/2nd Year/BTECH-SEM-3-Python Programming (KNC302H)-2024.pdf
  AKTU/2nd Year/BTECH-SEM-4-Computer System Security (KNC401H)-2022.pdf
  AKTU/2nd Year/BTECH-SEM-4-Computer System Security (KNC401H)-2023.pdf
  AKTU/2nd Year/BTECH-SEM-4-Computer System Security (KNC401H)-2024.pdf
  AKTU/2nd Year/BTECH-SEM-4-Microprocessor (KCS303H)-2022.pdf
  AKTU/2nd Year/BTECH-SEM-4-Microprocessor (KCS403H)-2023.pdf
  AKTU/2nd Year/BTECH-SEM-4-Python Programming (KNC402H)-2022.pdf
  AKTU/2nd Year/BTECH-SEM-4-Python Programming (KNC402H)-2023.pdf
  AKTU/2nd Year/BTECH-SEM-4-Python Programming (KNC402H)-2024.pdf
  AKTU/3rd Year/BTECH SEM-4 Theory of Automata and Formal Languages (KCS402H) 2022.pdf
  AKTU/3rd Year/BTECH SEM-4 Theory of Automata and Formal Languages (KCS402H) 2023.pdf
  AKTU/3rd Year/BTECH SEM-4 Theory of Automata and Formal Languages (KCS402H) 2024.pdf
  AKTU/3rd Year/BTECH-SEM-3- Discrete Structures & Theory of Logic (KCS303H )-2022.pdf
  AKTU/3rd Year/BTECH-SEM-3- Discrete Structures & Theory of Logic (KCS303H )-2023.pdf
  AKTU/3rd Year/BTECH-SEM-3- Discrete Structures & Theory of Logic (KCS303H )-2024.pdf
  AKTU/3rd Year/BTECH-SEM-4-Operating Systems -(KCS401H)-2022.pdf
  AKTU/3rd Year/BTECH-SEM-4-Operating Systems -(KCS401H)-2023.pdf
  AKTU/3rd Year/BTECH-SEM-4-Operating Systems -(KCS401H)-2024.pdf
  AKTU/3rd Year/BTECH-SEM-5-Constitution of India (BNC501H)-2024.pdf
  AKTU/3rd Year/BTECH-SEM-6-Constitution of India (BNC601H)-2024.pdf
Labels: enhancement, Advanced, SSOC S4

#743 Upload pyq of fashion technology
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-2-sem-basic-electrical-engineering-2013.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-2-sem-basic-electronics-engineering-2013.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-2-sem-engineering-chemistry-2013.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-2-sem-mathematics-2-bsm-202-n-2019.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-2-sem-physics-1-bs-ph-201-n-2019.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-cs-201-basic-computation-and-principles-of-computer-programming-2015.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-cs-201-basic-computation-and-principles-of-computer-programming-2017.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-cs-201-basic-computation-and-principles-of-computer-programming-2018.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-cs-201-basic-computation-and-principles-of-computer-programming-2019.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-cs-201-chemistry-1-2017.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-es-101-basic-electrical-and-electronics-engineering-1-2016.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-es-201-basic-electrical-and-electronic-engineering-2-2018.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-es-201-basic-electrical-and-electronics-engineering-1-2015.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-es-201-basic-electrical-and-electronics-engineering-2-2016.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-es-201-part-2-basic-electrical-and-electronic-engineering-2-2017.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-es-201-part-2-basic-electrical-and-electronics-engineering-2-2017.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-es-201t-basic-electrical-and-electronic-engineering-2-2018.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-hu-201-english-language-and-communication-2014.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-m-201-mathematics-2-2017.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-m-201-mathematics-2-2018.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-m-201-mathematics-2-2019.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-me-201-engineering-thermodynamics-and-fluid-mechanics-2014.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-me-201-engineering-thermodynamics-and-fluid-mechanics-2016.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-me-201-engineering-thermodynamics-and-fluid-mechanics-2017.pdf
  MAKAUT/Fashion Technology/Civil Engineering/2nd semester/btech-ph-201-physics-1-2014.pdf
Labels: enhancement, SSOC S4

#758 Upload pyq of biotechnology and leather technology
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-animal-cell-and-culture-and-molecular-modeling-2012.pdf
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-animal-cell-and-culture-and-molecular-modeling-v2-2012.pdf
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-animal-cell-culture-and-molecular-modelling-2010.pdf
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-animal-cell-culture-and-molecular-modelling-2011.pdf
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-biophysics-of-macromolecules-2010.pdf
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-biophysics-of-macromolecules-2011.pdf
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-biophysics-of-macromolecules-2012.pdf
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-biosensors-and-diagnostics-2012.pdf
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-food-biotechnology-2011.pdf
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-food-biotechnology-2012.pdf
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-industrial-economics-and-management-2011.pdf
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-industrial-economics-and-management-2012.pdf
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-industrial-economics-and-management-v2-2011.pdf
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-modelling-and-simulation-of-bioprocesses-2012.pdf
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-molecular-modelling-and-drug-design-2011.pdf
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-molecular-modelling-and-drug-designing-2012.pdf
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-renewable-energy-technology-2011.pdf
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-renewable-energy-technology-2012.pdf
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-renewable-energy-technology-v2-2011.pdf
  MAKAUT/Biotechnology and leather/7th Semester/btech-bt-7-sem-renewable-energy-technology-v7-2011.pdf
Labels: enhancement, SSOC S4

#769 Completed [Task 3.3.1] [Text file conversion] Create PYQs text files for any of the directed colleges with links given (YMCA, NIT-kurukshetra, IGDTUW, vit-bhopal) #755
  VIT Bhopal University/01. Computer Engineering/Semester 3/Basic Electrical Engineering (EEE1001)/text pdf/Basic Electrical Engineering (Dec 2023) (EEE1001).pdf (10).pdf.txt
  VIT Bhopal University/01. Computer Engineering/Semester 3/Basic Electrical Engineering (EEE1001)/text pdf/Basic Electrical Engineering (Dec 2023) (EEE1001).pdf (2).txt
  VIT Bhopal University/01. Computer Engineering/Semester 3/Basic Electrical Engineering (EEE1001)/text pdf/Basic Electrical Engineering (Dec 2023) (EEE1001).pdf (4).txt
  VIT Bhopal University/01. Computer Engineering/Semester 3/Basic Electrical Engineering (EEE1001)/text pdf/Basic Electrical Engineering (Dec 2023) (EEE1001).pdf (6).txt
  VIT Bhopal University/01. Computer Engineering/Semester 3/Basic Electrical Engineering (EEE1001)/text pdf/Basic Electrical Engineering (Dec 2023) (EEE1001).pdf (7).txt
  VIT Bhopal University/01. Computer Engineering/Semester 3/Basic Electrical Engineering (EEE1001)/text pdf/Basic Electrical Engineering (Dec 2023) (EEE1001).pdf (8).txt
Labels: SSOC S4, Data Structuring

#772 Added Anna university - 8 Electives
  Anna-University/R2021/All Branches PYQ/Electives/Electives/CAD_CAM [CME340]/PYQ [CME340]/CAD_CAM (Dec 2023) [CME340].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/CAD_CAM [CME340]/PYQ [CME340]/CAD_CAM (May 2024) [CME340].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/CAD_CAM [CME340]/PYQ [CME340]/CAD_CAM (May XXXX) [CME340].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Cloud Computing [CCS335]/PYQ [CCS335]/Cloud Computing (Dec 2023) [CCS335].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Cloud Computing [CCS335]/PYQ [CCS335]/Cloud Computing (Dec 2024) [CCS335].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Cloud Computing [CCS335]/PYQ [CCS335]/Cloud Computing (May 2024) [CCS335].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Cloud Computing [CCS335]/PYQ [CCS335]/Cloud Computing (May XXXX) [CCS335].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Cloud Computing [CCS335]/PYQ [CCS335]/Old Regulation [CCS335]/CC [CCS335].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Cloud Computing [CCS335]/[CCS335]/Cloud Computing Notes Notes Notes Notes Notes Notes Notes [CCS335].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Cloud Services Management [CCS336]/PYQ [CCS336]/Cloud Services Management (May 2024) [CCS336].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Cloud Services Management [CCS336]/PYQ [CCS336]/Cloud Services Management (May XXXX) [CCS336].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Cloud Services Management [CCS336]/[CCS336]/CCS336 Cloud Services Management Notes Notes Notes Notes Notes Notes Notes.pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Computer Vision [CCS338]/PYQ [CCS338]/Computer Vision (May 2024) [CCS338].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Computer Vision [CCS338]/PYQ [CCS338]/Computer Vision (May XXXX) [CCS338].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Computer Vision [CCS338]/[CCS338]/Computer Vision Notes Notes Notes Notes Notes Notes Notes [CCS338].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Constitution of India [CMG344]/PYQ [CMG344]/Constitution of India (Dec 2023) [CMG344].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Constitution of India [CMG344]/PYQ [CMG344]/Constitution of India (May XXXX) [CMG344].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Data Warehousing [CCS341]/PYQ [CCS341]/Data Warehousing (Dec 2023) [CCS341].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Data Warehousing [CCS341]/PYQ [CCS341]/Data Warehousing (Dec 2024) [CCS341].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Data Warehousing [CCS341]/PYQ [CCS341]/Data Warehousing (May 2024) [CCS341].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Data Warehousing [CCS341]/PYQ [CCS341]/Data Warehousing (May XXXX) [CCS341].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Digital Marketing [CCW332]/PYQ [CCW332]/Digital Marketing (Dec 2023) [CCW332].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Digital Marketing [CCW332]/PYQ [CCW332]/Digital Marketing (Dec 2024) [CCW332].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Digital Marketing [CCW332]/PYQ [CCW332]/Digital Marketing (May 2024) [CCW332].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Digital Marketing [CCW332]/PYQ [CCW332]/Digital Marketing (May XXXX) [CCW332].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Digital Marketing [CCW332]/[CCW332]/Digital Marketing Notes Notes Notes Notes Notes Notes Notes [CCW332].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Dynamics and Earthquake Resistant Structures [CE3006]/PYQ [CE3006]/Apr May 2024 Question Paper (May 2024) [CE3006].pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Dynamics and Earthquake Resistant Structures [CE3006]/PYQ [CE3006]/CE3006 Dynamics and Earthquake Resistant Structures (Dec XXXX).pdf
  Anna-University/R2021/All Branches PYQ/Electives/Electives/Dynamics and Earthquake Resistant Structures [CE3006]/PYQ [CE3006]/Nov Dec 2023 Question Paper (Dec 2023) [CE3006].pdf
Labels: enhancement, SSOC S4

#770 Uploaded PYQs of Operating System(CSE3003), Applied Linear Algebra(MAT3002), Programming in Java(CSE3002) and PYQs of 2025
  VIT Bhopal University Int.MTech AI/PYQs 2023/Mid-Term/README.md
  VIT Bhopal University Int.MTech AI/PYQs 2024/Term-End/Applied Linear Algebra(MAT3002)/Applied Linear Algebra(MAT3002) - Aug 2024 p.g.1.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2024/Term-End/Applied Linear Algebra(MAT3002)/Applied Linear Algebra(MAT3002) - Aug 2024 p.g.2.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2024/Term-End/Applied Linear Algebra(MAT3002)/Applied Linear Algebra(MAT3002) - Aug 2024 p.g.3.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2024/Term-End/Operating System(CSE3003)/Operating System(CSE3003) - Aug 2024 p.g.1.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2024/Term-End/Operating System(CSE3003)/Operating System(CSE3003) - Aug 2024 p.g.2.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2024/Term-End/Programming in Java(CSE3002)/Programming in Java(CSE3002) - Aug 2024 p.g.1.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2024/Term-End/Programming in Java(CSE3002)/Programming in Java(CSE3002) - Aug 2024 p.g.2.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Mid-Term/Stochastic Process(MAT3016) - March 2025.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Stochastic Process(MAT3016)/Stochastic Process(MAT3016) - June 2025 p.g.1.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Stochastic Process(MAT3016)/Stochastic Process(MAT3016) - June 2025 p.g.2.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Stochastic Process(MAT3016)/Stochastic Process(MAT3016) - June 2025 p.g.3.jpg
Labels: enhancement, SSOC S4

#774 PYQ+
  AKTU/1st Year/Syllabus_BTech_First_Yr_Common_other_than_AG_&_BT_effective_from_2022_23_R.pdf
  AKTU/2nd Year/B.Tech_2nd_Yr_CSE_Hindi_v3.pdf
  AKTU/3rd Year/B.Tech. CS_Hindi Syllabus  3rd Year.pdf
  AKTU/3rd Year/BTECH SEM-6 Data Compression (BCS-064H) 2022.pdf
  AKTU/3rd Year/BTECH SEM-6 Data Compression (BCS-064H) 2023.pdf
  AKTU/3rd Year/BTECH SEM-6 Data Compression (BCS-064H) 2024.pdf
  AKTU/3rd Year/BTECH SEM-6 Machine Learning Techniques (BCS-055H) 2022.pdf
  AKTU/3rd Year/BTECH SEM-6 Machine Learning Techniques (BCS-055H) 2023.pdf
  AKTU/3rd Year/BTECH-SEM-5-Data Analytics (BCS-052H)-2022.pdf
  AKTU/3rd Year/BTECH-SEM-5-Data Analytics (BCS-052H)-2023.pdf
  AKTU/3rd Year/BTECH-SEM-6-Big Data-(BCS-061H)-2022.pdf
  AKTU/3rd Year/BTECH-SEM-6-Big Data-(BCS-061H)-2023.pdf
  AKTU/3rd Year/BTECH-SEM-6-Big Data-(BCS-061H)-2024.pdf
  AKTU/4th Year/BTECH-SEM-7-CLOUD COMPUTING-(KOE081)-2022-23.pdf
  AKTU/4th Year/BTECH-SEM-7-CLOUD COMPUTING-(KOE081)-2023-24.pdf
  AKTU/4th Year/BTECH-SEM-7-Natural Language Processing (KCS072)-2022-23.pdf
  AKTU/4th Year/BTECH-SEM-7-Natural Language Processing (KCS072)-2023-24.pdf
  AKTU/4th Year/BTECH-SEM-7-PROJECT MANAGEMENT & ENTREPRENEURSHIP-2022-23.pdf
  AKTU/4th Year/BTECH-SEM-7-PROJECT MANAGEMENT & ENTREPRENEURSHIP-2023-24.pdf
  AKTU/4th Year/BTECH-SEM-7-RURAL DEVELOPMENT ADMINISTRATION & PLANNING-2022-23.pdf
  AKTU/4th Year/BTECH-SEM-7-RURAL DEVELOPMENT ADMINISTRATION & PLANNING-2023-24.pdf
  AKTU/4th Year/BTECH-SEM-8-CLOUD COMPUTING-(KOE081)-2022-23.pdf
  AKTU/4th Year/BTECH-SEM-8-CLOUD COMPUTING-(KOE081)-2023-24.pdf
  AKTU/4th Year/BTECH-SEM-8-DATA-WAREHOUSING-AND-DATA-MINING-(KAI075)-2023-24.pdf
  AKTU/4th Year/BTECH-SEM-8-Natural Language Processing (KCS072)-2022-23.pdf
  AKTU/4th Year/BTECH-SEM-8-Natural Language Processing (KCS072)-2023-24.pdf
  AKTU/4th Year/BTECH-SEM-8-PROJECT MANAGEMENT & ENTREPRENEURSHIP-2022-23.pdf
  AKTU/4th Year/BTECH-SEM-8-PROJECT MANAGEMENT & ENTREPRENEURSHIP-2023-24.pdf
  AKTU/4th Year/BTECH-SEM-8-RURAL DEVELOPMENT ADMINISTRATION & PLANNING-2021-22.pdf
  AKTU/4th Year/BTECH-SEM-8-RURAL DEVELOPMENT ADMINISTRATION & PLANNING-2022-23.pdf
  AKTU/4th Year/BTECH-SEM-8-RURAL DEVELOPMENT ADMINISTRATION & PLANNING-2023-24.pdf
  AKTU/4th Year/BTech. 4th Year_Computer Science and Engineering- Hindi_2024-25_v2.pdf
  AKTU/4th Year/DATA-WAREHOUSING-DATA-MINING-KOE-093_watermark.pdf
  AKTU/4th Year/KAI075-DATA-WAREHOUSING-AND-DATA-MINING_watermark.pdf
Labels: enhancement, Advanced, SSOC S4

#775 Uploaded text context of 6 pyqs of Engineering Physics (PHY1001) #773
  VIT Bhopal University/01. Computer Engineering/Semester 3/Engineering Physics (PHY1001)/text pdf/Engineering Physics (Dec 2021) (PHY1001).pdf (2).txt
  VIT Bhopal University/01. Computer Engineering/Semester 3/Engineering Physics (PHY1001)/text pdf/Engineering Physics (Dec 2021) (PHY1001).pdf (3).txt
  VIT Bhopal University/01. Computer Engineering/Semester 3/Engineering Physics (PHY1001)/text pdf/Engineering Physics (Dec 2021) (PHY1001).pdf (4).txt
  VIT Bhopal University/01. Computer Engineering/Semester 3/Engineering Physics (PHY1001)/text pdf/Engineering Physics (Dec 2021) (PHY1001).pdf (5).txt
  VIT Bhopal University/01. Computer Engineering/Semester 3/Engineering Physics (PHY1001)/text pdf/Engineering Physics (Dec 2021) (PHY1001).pdf (6).txt
  VIT Bhopal University/01. Computer Engineering/Semester 3/Engineering Physics (PHY1001)/text pdf/Engineering Physics (Dec 2021) (PHY1001).pdf.txt
Labels: SSOC S4, Data Structuring

#778 Added 24 PYQs for EE Branch of HITK
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/5th Sem/Control System (ELEC3103)/ELEC 3103 5th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/5th Sem/Control System (ELEC3103)/ELEC 3103 5th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/5th Sem/Control System (ELEC3103)/ELEC 3103 5th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/5th Sem/Control System (ELEC3103)/ELEC 3203 6th Sem  (Backlog) 2021.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/5th Sem/Indian Constitution and Civil Society (INC3016)/INCO 3016 5th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/5th Sem/Indian Constitution and Civil Society (INC3016)/INCO 3016 5th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/5th Sem/Indian Constitution and Civil Society (INC3016)/INCO 3016 5th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/5th Sem/Power Electronics (ELEC3104)/ELEC 3104 5th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/5th Sem/Power Electronics (ELEC3104)/ELEC 3104 5th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/5th Sem/Power Electronics (ELEC3104)/ELEC 3104 5th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/5th Sem/Power Electronics (ELEC3104)/ELEC 3202 6th Sem (Backlog) 2021.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/6th Sem/Economics for Engineers (HUM3201)/HMTS 3201- 6th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/6th Sem/Economics for Engineers (HUM3201)/HMTS 3201- 6th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/6th Sem/Economics for Engineers (HUM3201)/HMTS 3201- 6th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/6th Sem/Economics for Engineers (HUM3201)/HMTS 3201- 6th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/6th Sem/Illumination Engineering (ELEC3241)/ELEC 3241- 6th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/6th Sem/Illumination Engineering (ELEC3241)/ELEC 3241- 6th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/6th Sem/Illumination Engineering (ELEC3241)/ELEC 3241- 6th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/6th Sem/Illumination Engineering (ELEC3241)/ELEC 3241- 6th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/6th Sem/Microprocessor & Microcontroller (ELE3201)/ELEC 3202- 6th Sem 2021.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/6th Sem/Microprocessor & Microcontroller (ELE3201)/ELEC 3202- 6th Sem 2022.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/6th Sem/Microprocessor & Microcontroller (ELE3201)/ELEC 3202- 6th Sem 2023.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/6th Sem/Microprocessor & Microcontroller (ELE3201)/ELEC 3202- 6th Sem 2024.pdf
  Heritage Institute of Technology, Kolkata/04. Electrical Engineering/6th Sem/Microprocessor & Microcontroller (ELE3201)/ELEC 3204- 6th Sem (Backlog) 2021.pdf
Labels: enhancement, Advanced, SSOC S4

#784 Update README.md
  README.md
Labels: enhancement, SSOC S4

#786 Uploaded 10 PYQs of 2025 into VIT Bhopal University Int.MTech AI
  Data_Dump/VIT Bhopal University Int.MTech AI/PYQs 2025/Mid-Term/Agent based Intelligent System(CSA3001)( A12+A13) - March 2025.jpg
  Data_Dump/VIT Bhopal University Int.MTech AI/PYQs 2025/Mid-Term/Agent based Intelligent System(CSA3001)(F11+F12) - March 2025.jpg
  Data_Dump/VIT Bhopal University Int.MTech AI/PYQs 2025/Mid-Term/Computer Networks(CSE3006) - March 2025.jpg
  Data_Dump/VIT Bhopal University Int.MTech AI/PYQs 2025/Mid-Term/Ethical Hacking(CSD4002) - March 2025.jpg
  Data_Dump/VIT Bhopal University Int.MTech AI/PYQs 2025/Mid-Term/Reinforcement Learning(CSA3003) - March 2025.jpg
  Data_Dump/VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Agent based Intelligent System(CSA3001)/Agent based Intelligent Systems(CSA3001) - June-July 2025 p.g.1.jpg
  Data_Dump/VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Agent based Intelligent System(CSA3001)/Agent based Intelligent Systems(CSA3001) - June-July 2025 p.g.2.jpg
  Data_Dump/VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Agent based Intelligent System(CSA3001)/Agent based Intelligent Systems(CSA3001) - June-July 2025 p.g.3.jpg
  Data_Dump/VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Computer Networks(CSE3006)/Computer Networks(CSE3006) - June-July 2025 p.g.1.jpg
  Data_Dump/VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Computer Networks(CSE3006)/Computer Networks(CSE3006) - June-July 2025 p.g.2.jpg
  Data_Dump/VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Ethical Hacking(CSD4002)/Ethical Hacking(CSD4002) - June-July 2025 p.g.1.jpg
  Data_Dump/VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Ethical Hacking(CSD4002)/Ethical Hacking(CSD4002) - June-July 2025 p.g.2.jpg
  Data_Dump/VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Reinforcement Learning(CSA3003)/Reinforcement Learning(CSA3003) - June-July 2025 p.g.1.jpg
  Data_Dump/VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Reinforcement Learning(CSA3003)/Reinforcement Learning(CSA3003) - June-July 2025 p.g.2.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Mid-Term/Agent based Intelligent System(CSA3001)( A12+A13) - March 2025.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Mid-Term/Agent based Intelligent System(CSA3001)(F11+F12) - March 2025.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Mid-Term/Computer Networks(CSE3006) - March 2025.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Mid-Term/Ethical Hacking(CSD4002) - March 2025.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Mid-Term/Reinforcement Learning(CSA3003) - March 2025.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Agent based Intelligent Systems(CSA3001)/Agent based Intelligent Systems(CSA3001) - June-July 2025 p.g.1.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Agent based Intelligent Systems(CSA3001)/Agent based Intelligent Systems(CSA3001) - June-July 2025 p.g.2.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Agent based Intelligent Systems(CSA3001)/Agent based Intelligent Systems(CSA3001) - June-July 2025 p.g.3.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Computer Networks(CSE3006)/Computer Networks(CSE3006) - June-July 2025 p.g.1.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Computer Networks(CSE3006)/Computer Networks(CSE3006) - June-July 2025 p.g.2.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Ethical Hacking(CSD4002)/Ethical Hacking(CSD4002) - June-July 2025 p.g.1.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Ethical Hacking(CSD4002)/Ethical Hacking(CSD4002) - June-July 2025 p.g.2.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Ethical Hacking(CSD4002)/r
  VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Reinforcement Learning(CSA3003)/Reinforcement Learning(CSA3003) - June-July 2025 p.g.1.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Reinforcement Learning(CSA3003)/Reinforcement Learning(CSA3003) - June-July 2025 p.g.2.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Stochastic Process(MAT3016)/Stochastic Process(MAT3016) - June-July 2025 p.g.1.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Stochastic Process(MAT3016)/Stochastic Process(MAT3016) - June-July 2025 p.g.2.jpg
  VIT Bhopal University Int.MTech AI/PYQs 2025/Term-End/Stochastic Process(MAT3016)/Stochastic Process(MAT3016) - June-July 2025 p.g.3.jpg
Labels: enhancement, Intermediate, SSOC S4

#788 Added 8 subjects of electives - Anna University
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Electrical Drives [EE3012]/PYQ [EE3012]/Electrical Drives (Dec 2023) [EE3012].pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Electrical Drives [EE3012]/PYQ [EE3012]/Electrical Drives (Dec 2024) [EE3012].pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Electrical Drives [EE3012]/PYQ [EE3012]/Electrical Drives (May 2024) [EE3012].pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Electrical Drives [EE3012]/PYQ [EE3012]/Electrical Drives (May XXXX) [EE3012].pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Electrical Drives [EE3012]/[EE3012]/Electrical Drives Notes Notes Notes Notes Notes Notes Notes [EE3012].pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Energy Management and Auditing [EE3005]/PYQ [EE3005]/Energy Management and Auditing (Dec 2023) [EE3005].pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Energy Management and Auditing [EE3005]/PYQ [EE3005]/Energy Management and Auditing (May XXXX) [EE3005].pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Energy Management and Auditing [EE3005]/[EE3005]/EE3005 Energy Management and Auditing Notes Notes Notes Notes Notes Notes.pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Energy Storage Devices [CME364]/PYQ [CME364]/Energy Storage Devices (Dec 2024) [CME364].pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Energy Storage Devices [CME364]/PYQ [CME364]/Energy Storage Devices (May XXXX) [CME364].pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Equipment for Pollution Control [CME366]/PYQ [CME366]/Equipment for Pollution Control (May 2024) [CME366].pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Equipment for Pollution Control [CME366]/PYQ [CME366]/Equipment for Pollution Control (May XXXX) [CME366].pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Ethical Hacking [CCS344]/PYQ [CCS344]/Ethical Hacking (Dec 2023) [CCS344].pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Ethical Hacking [CCS344]/PYQ [CCS344]/Ethical Hacking (May XXXX) [CCS344].pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Ethics and AI [CCS345]/PYQ [CCS345]/Ethics and AI (Dec 2024) [CCS345].pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Ethics and AI [CCS345]/PYQ [CCS345]/Ethics and AI (May 2024) [CCS345].pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Ethics and AI [CCS345]/PYQ [CCS345]/Ethics and AI (May XXXX) [CCS345].pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Ethics and AI [CCS345]/[CCS345]/Ethics and AI Notes Notes Notes Notes Notes Notes Notes [CCS345].pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Ground Improvement Techniques [CE3016]/PYQ [CE3016]/Ground Improvement Techniques (Dec 2023) [CE3016].pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Ground Improvement Techniques [CE3016]/PYQ [CE3016]/Ground Improvement Techniques (May 2024) [CE3016].pdf
  Data_Dump/Anna-University/R2021/All Branches PYQ/Electives/Electives/Ground Improvement Techniques [CE3016]/PYQ [CE3016]/Ground Improvement Techniques (May XXXX) [CE3016].pdf
Labels: enhancement, SSOC S4

#799 PYQ+
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/AST-01 STATISTICAL TECHNIQUES.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BBYCT-131 BIODIVERSITY (MICROBES, ALGAE,.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BBYCT-133  PLANT ECOLOGY AND TAXONOMY.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BBYCT-135 PLANT ANATOMY AND.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BBYCT-137 Plant Physiology and Metabolism.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BCHCT-131 ATOMIC STRUCTURE, BONDING.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BCHCT-133 CHEMICAL ENERGETICS.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BCHCT-135  SOLUTIONS, PHASE EQUILIBRIUM,.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BGGCT-131 PHYSICAL GEOGRAPHY.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BGGCT-132 HUMAN GEOGRAPHY.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BGGCT-133 GENERAL CARTOGRAPHY.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BGGCT-135  ENVIRONMENTAL GEOGRAPHY.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BPHCT-131 MECHANICS.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BPHCT-133 ELECTRICITY AND MAGNETISM.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BPHCT-135 THERMAL PHYSICS AND.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BPHCT-137 WAVES AND OPTICS.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BPHE-104-PHE-04 MATHEMATICAL METHODS.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BZYCT-131 ANIMAL DIVERSITY.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BZYCT-133 COMPARATIVE ANATOMY AND.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BZYCT-135  PHYSIOLOGY AND BIOCHEMISTRY.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/BZYCT–137 GENETICS AND EVOLUTIONARY.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MTE-07  DIFFERENTIAL EQUATIONS.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MTE-08  DIFFERENTIAL EQUATIONS.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MTE-09 REAL ANALYSIS.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MTE-10 NUMERICAL ANALYSIS.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MTE-11 PROBABILITY AND STATISTICS.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MTE-12 LINEAR PROGRAMMING.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MTE-13 DISCRETE MATHEMATICS.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MTE-14 MATHEMATICAL MODELLING.pdf
Labels: Advanced, SSoC25
