Repository Saumy1905/PYQFort, pull requests merged in 2025-08, with the labels that each got.

#807 Added PYQs for AIML & CST SEMESTER 1
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Applied Chemistry/MAIT-Applied Chemistry-2017.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Applied Chemistry/MAIT-Applied Chemistry-2018.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Applied Chemistry/MAIT-Applied Chemistry-2019.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Applied Chemistry/MAIT-Applied Chemistry-Jan2024.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Applied Chemistry/MAIT-Applied Chemistry-MidTem2017.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Applied Chemistry/MAIT-Applied Chemistry-MidTerm2021.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Applied Chemistry/MAIT-Applied Chemistry-Nov 2023.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Applied Mathematics-I/MAIT-Applied Mathematics-I Dec2024.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Applied Mathematics-I/MAIT-Applied Mathematics-I Mar2023.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Applied Mathematics-I/MAIT-Applied Mathematics-I-2017 .pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Applied Mathematics-I/MAIT-Applied Mathematics-I-MidTerm2017.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Applied Physics-I/MAIT-Applied Physics-I Jan2024.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Applied Physics-I/MAIT-Applied Physics-I Nov2023.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Applied Physics-I/MAIT-Applied Physics-I-2017.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Applied Physics-I/MAIT-Applied Physics-I-MidTerm2017.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Communication Skills/MAIT-Communication Skills-Dec2024.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Communication Skills/MAIT-Communication Skills-Jan2024.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Communication Skills/MAIT-Communication Skills-Midsem2023.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Electrical Science/MAIT-Electrical Science-Dec2024.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Electrical Science/MAIT-Electrical Science-Mar2023.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Electrical Science/MAIT-Electrical Science-Midsem2023.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Manufacturing Process/MAIT-Manufacturing Process-Dec2024.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Manufacturing Process/MAIT-Manufacturing Process-MidTerm2019.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Manufacturing Process/MAIT-Manufacturing Process-MidTerm2021.pdf
  Data_Dump/MAIT-GGSIPU/AIML/SEMESTER 1/Manufacturing Process/MAIT-Manufacturing Process-MidTerm2023.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Applied Chemistry/MAIT-Applied Chemistry-2017.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Applied Chemistry/MAIT-Applied Chemistry-2018.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Applied Chemistry/MAIT-Applied Chemistry-2019.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Applied Chemistry/MAIT-Applied Chemistry-Jan2024.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Applied Chemistry/MAIT-Applied Chemistry-MidTem2017.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Applied Chemistry/MAIT-Applied Chemistry-MidTerm2021.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Applied Chemistry/MAIT-Applied Chemistry-Nov 2023.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Applied Mathematics-I/MAIT-Applied Mathematics-I Dec2024.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Applied Mathematics-I/MAIT-Applied Mathematics-I Mar2023.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Applied Mathematics-I/MAIT-Applied Mathematics-I-2017 .pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Applied Mathematics-I/MAIT-Applied Mathematics-I-MidTerm2017.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Applied Physics-I/MAIT-Applied Physics-I Jan2024.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Applied Physics-I/MAIT-Applied Physics-I Nov2023.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Applied Physics-I/MAIT-Applied Physics-I-2017.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Applied Physics-I/MAIT-Applied Physics-I-MidTerm2017.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Communication Skills/MAIT-Communication Skills-Dec2024.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Communication Skills/MAIT-Communication Skills-Jan2024.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Communication Skills/MAIT-Communication Skills-Midsem2023.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Electrical Science/MAIT-Electrical Science-Dec2024.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Electrical Science/MAIT-Electrical Science-Mar2023.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Electrical Science/MAIT-Electrical Science-Midsem2023.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Manufacturing Process/MAIT-Manufacturing Process-Dec2024.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Manufacturing Process/MAIT-Manufacturing Process-MidTerm2019.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Manufacturing Process/MAIT-Manufacturing Process-MidTerm2021.pdf
  Data_Dump/MAIT-GGSIPU/CST/SEMESTER 1/Manufacturing Process/MAIT-Manufacturing Process-MidTerm2023.pdf
Labels: Advanced, SSoC25

#814 Added PYQs for BCA SEM 3
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-basic-of-python-programming-bcat-211-jan-2024.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-basics-of-python-programming-bcat-211-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-computer-architecture-bca-203-dec-2018.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-computer-networks-bca-201-dec-2024.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-computer-networks-bca-201-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-computer-networks-bca-201-jan-2024.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-computer-organization-and-architecture-bca-203-dec-2024.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-computer-organization-and-architecture-bca-203-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-computer-organization-and-architure-bca-203-jan-2024.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-cyber-security-bcat-213-dec-2024.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-human-values-and-ethics-bca-207-dec-2024.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-human-values-and-ethics-bca-207-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-human-values-and-ethics-bca-207-jan-2024.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-object-oriented-programming-using-cpp-bca-209-dec-2013.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-object-oriented-programming-using-cpp-bca-209-dec-2015.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-object-oriented-programming-using-cpp-bca-209-dec-2016.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-object-oriented-programming-using-cpp-bca-209-dec-2017.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-object-oriented-programming-using-cpp-bca-209-dec-2018.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-object-oriented-programming-using-cpp-bca209-dec-2014.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-object-oriented-programming-with-cpp-bca-205-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-object-oriented-programming-with-cpp-bca-205-jan-2024.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-object-oriented-programming-with-cpp-bca-205-jan-2025.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-object-oriented-programming-with-cpp-bca-209-dec-2019.pdf
  Data_Dump/MAIT-GGSIPU/BCA/SEM 3/ggsipu-bca-3-sem-principles-of-accounting-bca207-dec-2012.pdf
Labels: Advanced, SSoC25

#826 Added 24 PYQs in MAIT-GGSIPU
  Data_Dump/MAIT-GGSIPU/BBA/SEM 1/ggsipu-bba-1-sem-business-economics-bba-107-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 1/ggsipu-bba-1-sem-business-economics-bba-107-jan-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 1/ggsipu-bba-1-sem-business-mathematics-bba-103-jan-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 1/ggsipu-bba-1-sem-business-mathematics-bba103-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 1/ggsipu-bba-1-sem-computer-applications-bba-109-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 1/ggsipu-bba-1-sem-financial-accounting-and-analysis-bba-105-dec-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 1/ggsipu-bba-1-sem-financial-accounting-and-analysis-bba-105-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 1/ggsipu-bba-1-sem-it-applications-in-business-bba-109-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 1/ggsipu-bba-1-sem-it-applications-in-business-bba-109-jan-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 1/ggsipu-bba-1-sem-it-applications-in-business-bba-113-dec-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 1/ggsipu-bba-1-sem-management-process-and-organizational-behaviour-bba101-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 1/ggsipu-bba-1-sem-management-process-and-organizational-behaviour-bbacam-101-jan-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 2/ggsipu-bba-2-sem-business-environment-bba-112-nov-2020.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 2/ggsipu-bba-2-sem-business-laws-and-company-laws-bcom-104-jun-2018.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 2/ggsipu-bba-2-sem-cost-accounting-bba-102-jul-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 2/ggsipu-bba-2-sem-cost-accounting-bba-102-jun-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 2/ggsipu-bba-2-sem-cost-accounting-bba-102-may-2019.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 2/ggsipu-bba-2-sem-decision-techniques-for-business-bba-104-jul-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 2/ggsipu-bba-2-sem-decision-techniques-for-business-bba-104-jun-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 2/ggsipu-bba-2-sem-decision-techniques-for-business-bba-104-jun-2025.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 2/ggsipu-bba-2-sem-e-commerce-bba-106-jun-2018.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 2/ggsipu-bba-2-sem-e-commerce-bba-108-jul-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 2/ggsipu-bba-2-sem-e-commerce-bba-108-jun-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 2/ggsipu-bba-2-sem-human-resource-management-bba-106-jun-2025.pdf
Labels: Advanced, SSoC25

#830 added PYQsof s5 and s6 of cse in ktu university in past 3 years
  Data_Dump/ktu/cse/s5/compilerdesign/2021/ktu-compilerdesign-2021.pdf
  Data_Dump/ktu/cse/s5/compilerdesign/2022/ktu-compilerdesign-2022.pdf
  Data_Dump/ktu/cse/s5/compilerdesign/2023/ktu-compilerdesign-2023.pdf
  Data_Dump/ktu/cse/s5/mobilecomputing/2021/ktu-mobilecomputing.2021.pdf
  Data_Dump/ktu/cse/s5/mobilecomputing/2022/ktu-mobilecomputing.2022.pdf
  Data_Dump/ktu/cse/s5/mobilecomputing/2023/ktu-mobilecomputing.2023.pdf
  Data_Dump/ktu/cse/s5/python/2022/ktu-python-2022.pdf
  Data_Dump/ktu/cse/s5/python/2023/ktu-python-2023.pdf
  Data_Dump/ktu/cse/s5/webtechnologies/2021/ktu-webtechnologies-2021.pdf
  Data_Dump/ktu/cse/s5/webtechnologies/2022/ktu-webtechnologies-2022.pdf
  Data_Dump/ktu/cse/s5/webtechnologies/2023/ktu-webtechnologies-2023.pdf
  Data_Dump/ktu/cse/s6/computer_system_architecture/2023/ktu-csarchitectecture-2023.pdf
  Data_Dump/ktu/cse/s6/distributed_computing/2023/ktu-distributedcomputing-2023.pdf
  Data_Dump/ktu/cse/s6/machine_learning/2023/ktu-machine-learning.2023.pdf
Labels: Beginner, SSoC25

#831 Added 24 PYQs in MAIT-GGSIPU
  Data_Dump/MAIT-GGSIPU/BBA/SEM 2/ggsipu-bba-2-sem-business-communication-bba-108-jun-2025.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 2/ggsipu-bba-2-sem-business-communication-bba-110-jul-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 2/ggsipu-bba-2-sem-business-communication-bba-110-jun-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 2/ggsipu-bba-2-sem-business-communication-bba-110-may-2019.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 2/ggsipu-bba-2-sem-business-environment-bba-106-jul-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 2/ggsipu-bba-2-sem-quantitative-techniques-bba-104-nov-2020.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-business-ethics-and-corporate-social-responsibility-bba-205-dec-2018.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-business-ethics-and-corporate-social-responsibility-bba205-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-business-law-bba-201-dec-2018.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-business-laws-bba-201-dec-2019.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-business-laws-bba-201-jan-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-business-laws-bba201-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-business-laws-bba201-v2-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-business-research-methodology-bba-211-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-business-research-methodology-bba-211-jan-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-computer-application-1-bba-207-dec-2019.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-environmental-studies-bba-217-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-environmental-studies-bba-217-jan-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-human-resource-management-bba-205-jan-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-human-resource-management-bba205-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-marketing-management-bba-b-and-1-2023-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-organizational-behaviour-bba-201-dec-2019.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-production-and-operations-management-bba-209-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-production-and-operative-management-bba-209-jan-2024.pdf
Labels: Advanced, SSoC25

#833 Added the Academic Rules for CSJMU Kanpur
  Data_Dump/CSJMU KANPUR/Academic_rules/B.Tech-academic-rules-applicable-from-2020.pdf
  Data_Dump/CSJMU KANPUR/Academic_rules/uiet-csjmu-rules.md
Labels: Intermediate, SSoC25

#834 Added BBA SEM 4 PYQs
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-business-analytics-bba-202-jun-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-business-analytics-bba-202-jun-2025.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-business-law-bba-210-jun-2013.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-business-law-bba-210-jun-2016.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-business-law-bba210-jun-2015.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-business-laws-bba-210-jun-2014.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-busniess-analytics-bba-202-jun-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-corporate-governance-ethics-and-social-responsibility-of-business-bba-206-jun-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-corporate-governance-ethics-and-social-responsibility-of-business-bba-206-jun-2025.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-corporation-governance-ethics-and-social-bba-206-jul-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-financial-management-bba-204-jun-2019.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-financial-management-bba-204-jun-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-financial-management-bba-204-jun-2025.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-financial-markets-and-institutions-bba-216-jun-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-human-resource-management-bba-202-jul-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-human-resource-management-bba-202-may-2019.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-income-tax-law-and-practice-bba-208-jul-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-income-tax-law-and-practice-bba-208-jun-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-income-tax-law-and-practice-bba-208-jun-2025.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-information-systems-management-bba-210-jul-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-information-systems-management-bba210-may-2019.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-research-methodology-bba-206-may-2019.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-research-methodology-bba-206-nov-2020.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 4/ggsipu-bba-4-sem-sales-management-bba-214-jun-2024.pdf
Labels: Advanced, SSoC25

#836 PYQ+
  Data_Dump/IGNOU/School of Computer Information Science (SOCIS)/BCS-011 COMPUTER BASICS AND PC.pdf
  Data_Dump/IGNOU/School of Computer Information Science (SOCIS)/BCS-012 BASIC MATHEMATICS.pdf
  Data_Dump/IGNOU/School of Computer Information Science (SOCIS)/CIT-002 Introduction to Information Technology.pdf
  Data_Dump/IGNOU/School of Computer Information Science (SOCIS)/CIT-003 Web Based technology and Multimedia applications.pdf
  Data_Dump/IGNOU/School of Computer Information Science (SOCIS)/ECO-01 BUSINESS ORGANISATION.pdf
  Data_Dump/IGNOU/School of Computer Information Science (SOCIS)/ECO-02  ACCOUNTANCY-I.pdf
  Data_Dump/IGNOU/School of Computer Information Science (SOCIS)/FEG-1-BEGF-101  FOUNDATION COURSE IN.pdf
  Data_Dump/IGNOU/School of Computer Information Science (SOCIS)/FEG-2 FOUNDATION COURSE IN ENGLISH-2.pdf
  Data_Dump/IGNOU/School of Computer Information Science (SOCIS)/Fundamentals of Computer System.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MGY-001 INTRODUCTION TO G.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MGY-002 REMOTE SENSING.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MGY-003  GLOBAL NAVIGATION.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MGY-005 TECHNIUQUES IN REMOTE.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MGY-006 SPATIAL ANALYSIS.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MGY-007 GEOINFORMATICS.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MGY-101 ITG.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MGY-102 REMOTE SENSING.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MGY-103 GLOBAL NAVIGATION.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MPH-001 MATHEMATICAL METHODS.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MPH-002-MPH-003 CLASSICAL MECHANICS—I.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MPH-004 QUANTUM MECHANICS–I.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MPH-005.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MPH-006 CLASSICAL MECHANICS—II.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MPH-007 CLASSICAL ELECTRODYNAMICS.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MPH-008 QUANTUM MECHANICS—II.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MRW 006 BIOENERGY CONVERSION.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MRW-001 ENERGY CONVERSION.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MRW-002 HEAT TRANSFER.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MRW-003 RENEWABLE ENERGY SYSTEM.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MRW-004 ENERGY MANAGEMENT.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MRW-005 SOLAR ENERGY.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MRW-007 ENERGY ECONOMICS.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MRWE-001 NANOTECHNOLOGY.pdf
  Data_Dump/IGNOU/School of Sciences/Bachelor Degree Programme (APPLICATION ORIENTED COURSE)/MRWE-002 ENERGY STORAGE.pdf
Labels: Advanced, SSoC25

#839 Added PYQs for SEM 5
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-business-policy-and-strategy-bba303-dec-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-e-commerce-bba-b-and-1-309-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-entrepreneurship-development-bba307-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-financial-management-bba-309-dec-2018.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-financial-management-bba-309-jan-2016.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-financial-management-bba-ttm309-dec-2010.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-financial-management-bba309-jan-2015.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-goods-and-services-tax-bba301-dec-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-goods-and-services-tax-gst-bba-309-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-income-tax-law-and-practice-bba-301-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-income-tax-law-and-practices-bba-bandj-301-dec-2019.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-information-systems-management-bba305-dec-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-management-information-system-bba-307-dec-2016.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-management-information-system-bba-307-dec-2017.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-management-information-system-bba-307-jan-2015.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-management-information-system-bba-307-jan-2016.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-management-information-system-bba-gen-307-dec-2018.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-management-process-and-organizational-behaviour-bba101-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-marketing-analytics-bba-309-dec-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-production-and-operation-management-bba-305-jan-2015.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-production-and-operations-management-bba-303-dec-2019.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-sales-management-bba-303-dec-2015.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-sales-management-bba-303-dec-2018.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-services-marketing-bba-305-feb-2023.pdf
Labels: Advanced, SSoC25

#842 Added all remaining PYQs for BBA
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-indian-economy-bba-209-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-management-accounting-bba-207-jan-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-management-accounting-bba207-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-management-accounting-bba207-v2-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-marketing-management-bba-203-feb-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 3/ggsipu-bba-3-sem-marketing-management-bba203-jan-2024.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-values-and-ethics-in-business-bba-301-dec-2017.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-values-and-ethics-in-business-bba-301-jan-2015.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-values-and-ethics-in-business-bba-301-jan-2016.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-5-sem-values-and-ethics-of-business-bba-301-dec-2018.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 5/ggsipu-bba-mba-5-sem-marketing-management-bba-102-jun-2025.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 6/ggsipu-bba-6-sem-business-policy-and-strategy-bba-302-jun-2016.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 6/ggsipu-bba-6-sem-business-policy-and-strategy-bba-302-jun-2017.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 6/ggsipu-bba-6-sem-business-policy-and-strategy-bba-302-jun-2018.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 6/ggsipu-bba-6-sem-business-policy-and-strategy-bba-308-jul-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 6/ggsipu-bba-6-sem-business-policy-and-strategy-bba302-jun-2014.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 6/ggsipu-bba-6-sem-business-policy-and-strategy-bba302-jun-2015.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 6/ggsipu-bba-6-sem-digital-marketing-bba-304-jul-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 6/ggsipu-bba-6-sem-entrepreneurship-development-bba-306-jun-2016.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 6/ggsipu-bba-6-sem-entrepreneurship-development-bba-306-jun-2017.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 6/ggsipu-bba-6-sem-entrepreneurship-development-bba-306-jun-2018.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 6/ggsipu-bba-6-sem-entrepreneurship-development-bba-306-may-2019.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 6/ggsipu-bba-6-sem-entrepreneurship-development-bba306-jun-2015.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 6/ggsipu-bba-6-sem-international-business-management-bba-306-jul-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 6/ggsipu-bba-6-sem-international-business-management-bba-308-may-2019.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 6/ggsipu-bba-6-sem-sales-and-distribution-management-bba-310-jul-2023.pdf
  Data_Dump/MAIT-GGSIPU/BBA/SEM 6/ggsipu-bba-6-sem-values-and-ethics-in-business-bba-bandi-310-may-2018.pdf
Labels: Advanced, SSoC25

#847 Add rules
  Data_Dump/RTMNU-Nagpur University (CSE pyq)/academic-rules/Computer Science & Engineering_RTMNU.pdf
  Data_Dump/RTMNU-Nagpur University (CSE pyq)/academic-rules/RTMNU-academic-rules-1.md
Labels: Intermediate, SSoC25

#849 Added 24 PYQs for EE branch of HITK
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/7th Sem/Advanced Power System (ELEC4131)/ELEC 4131 7th Sem 2021.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/7th Sem/Advanced Power System (ELEC4131)/ELEC 4131 7th Sem 2022.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/7th Sem/Advanced Power System (ELEC4131)/ELEC 4131 7th Sem 2023.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/7th Sem/Advanced Power System (ELEC4131)/ELEC 4161 7th Sem 2019.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/7th Sem/Advanced Power System (ELEC4131)/ELEC 4161 7th Sem 2020.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/7th Sem/Instrumentation and Telemetry (AEIE4121)/AEIE 4121 7th Sem 2021.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/7th Sem/Instrumentation and Telemetry (AEIE4121)/AEIE 4121 7th Sem 2022.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/7th Sem/Instrumentation and Telemetry (AEIE4121)/AEIE 4121 7th Sem 2023.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/7th Sem/Instrumentation and Telemetry (AEIE4121)/AEIE 4181 7th Sem 2019.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/7th Sem/Instrumentation and Telemetry (AEIE4121)/AEIE 4181 7th Sem 2020.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/7th Sem/Optical Instrumentation (AEIE4126)/AEIE4126 7th Sem 2021.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/7th Sem/Optical Instrumentation (AEIE4126)/AEIE4126 7th Sem 2022.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/7th Sem/Optical Instrumentation (AEIE4126)/AEIE4126 7th Sem 2023.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/8th Sem/High Voltage Engineering (ELEC4231)/ELEC 4102- 7th Sem 2019.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/8th Sem/High Voltage Engineering (ELEC4231)/ELEC 4231- 8th Sem 2022.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/8th Sem/High Voltage Engineering (ELEC4231)/ELEC 4231- 8th Sem 2023.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/8th Sem/High Voltage Engineering (ELEC4231)/ELEC 4231- 8th Sem 2024.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/8th Sem/Medical Instrumentation (AEIE4222)/AEIE 4222 8th Sem 2022.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/8th Sem/Medical Instrumentation (AEIE4222)/AEIE 4222 8th Sem 2023.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/8th Sem/Medical Instrumentation (AEIE4222)/AEIE 4222 8th Sem 2024.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/8th Sem/Non-Conventional Energy (BIOT4222)/BIOT 4222 8th Sem 2022.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/8th Sem/Non-Conventional Energy (BIOT4222)/BIOT 4222 8th Sem 2023.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/8th Sem/Non-Conventional Energy (BIOT4222)/BIOT 4222 8th Sem 2024.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/04. Electrical Engineering/8th Sem/Non-Conventional Energy (BIOT4222)/BIOT 4282 8th Sem 2021.pdf
Labels: Advanced, SSoC25

#850 PYQ+
  Data_Dump/IGNOU/MCA/MCS-031 DESIGN AND ANALYSIS.pdf
  Data_Dump/IGNOU/MCA/MCS-032 OBJECT ORIENTED ANALYSIS.pdf
  Data_Dump/IGNOU/MCA/MCS-033 ADVANCED DISCRETE.pdf
  Data_Dump/IGNOU/MCA/MCS-034 SOFTWARE ENGINEERING.pdf
  Data_Dump/IGNOU/MCA/MCS-035 ACCOUNTING AND FINANCIAL.pdf
  Data_Dump/IGNOU/MCA/MCS-041 OPERATING SYSTEMS.pdf
  Data_Dump/IGNOU/MCA/MCS-042 DATA COMMUNICATION.pdf
  Data_Dump/IGNOU/MCA/MCS-043 ADVANCED DATABASE.pdf
  Data_Dump/IGNOU/MCA/MCS-051 ADVANCED INTERNET.pdf
  Data_Dump/IGNOU/MCA/MCS-052 PRINCIPLES OF MANAGEMENT.pdf
  Data_Dump/IGNOU/MCA/MCS-053 COMPUTER GRAPHICS.pdf
  Data_Dump/IGNOU/MCA/MCS-201  PROGRAMMING IN C AND PYTHON.pdf
  Data_Dump/IGNOU/MCA/MCS-211  DESIGN AND ANALYSIS.pdf
  Data_Dump/IGNOU/MCA/MCS-212 DISCRETE MATHEMATICS.pdf
  Data_Dump/IGNOU/MCA/MCS-213 SOFTWARE ENGINEERING.pdf
  Data_Dump/IGNOU/MCA/MCS-214 PROFESSIONAL SKILLS AND ETHICS.pdf
  Data_Dump/IGNOU/MCA/MCS-215  SECURITY AND CYBER LAWS.pdf
  Data_Dump/IGNOU/MCA/MCS-218 DATA COMMUNICATION.pdf
  Data_Dump/IGNOU/MCA/MCS-219 OBJECT ORIENTED.pdf
  Data_Dump/IGNOU/MCA/MCS-220 WEB TECHNOLOGIES.pdf
  Data_Dump/IGNOU/MCA/MCS-221 DATA WAREHOUSING.pdf
  Data_Dump/IGNOU/MCA/MCS-224 ARTIFICIAL INTELLIGENCE.pdf
  Data_Dump/IGNOU/MCA/MCS-225 ACCOUNTANCY.pdf
  Data_Dump/IGNOU/MCA/MCS-226 DATA SCIENCE AND BIG DATA.pdf
  Data_Dump/IGNOU/MCA/MCS-227 CLOUD COMPUTING AND IOT.pdf
  Data_Dump/IGNOU/MCA/MCS-230 DIGITAL IMAGE PROCESSING.pdf
  Data_Dump/IGNOU/MCA/MCS-231  MOBILE COMPUTING.pdf
  Data_Dump/IGNOU/MCA/MCSE-003 AI & KNOWLEDGE MANAGEMENT.pdf
  Data_Dump/IGNOU/MCA/MCSE-004 NUMERICAL.pdf
  Data_Dump/IGNOU/MCA/MCSE-011 PARALLEL COMPUTING.pdf
Labels: Advanced, SSoC25

#852 Added Delhi-University PYQs for CS till 4th Semester
  Data_Dump/delhi-university/computer-science-hons/Sem 2/Object Oriented Programming with C++/Object Oriented programming with C++.pdf
  Data_Dump/delhi-university/computer-science-hons/Sem 2/Probability For Computing/Probability for computing.pdf
  Data_Dump/delhi-university/computer-science-hons/Sem 3/Computer Networks/Computer Networks-2.pdf
  Data_Dump/delhi-university/computer-science-hons/Sem 3/Computer Networks/Computer networks.pdf
  Data_Dump/delhi-university/computer-science-hons/Sem 3/Data Structures/Data Structures.pdf
  Data_Dump/delhi-university/computer-science-hons/Sem 3/Operating Systems/Operating Systems.pdf
  Data_Dump/delhi-university/computer-science-hons/Sem 4/Data Mining-I/Data Mining-I.pdf
  Data_Dump/delhi-university/computer-science-hons/Sem 4/Database Management Systems/Database Management Systems-2.pdf
  Data_Dump/delhi-university/computer-science-hons/Sem 4/Database Management Systems/Database Management Systems.pdf
  Data_Dump/delhi-university/computer-science-hons/Sem 4/Design and Analysis of Algorithms/Design and Analysis of Algorithms-2.pdf
  Data_Dump/delhi-university/computer-science-hons/Sem 4/Design and Analysis of Algorithms/Design and Analysis of Algorithms.pdf
  Data_Dump/delhi-university/computer-science-hons/sem1/Computer System Architechture/Computer System Architechture.pdf
  Data_Dump/delhi-university/computer-science-hons/sem1/Programming Fundamentals with C++/Programming fundamentals using C++.pdf
Labels: SSoC25

#854 PYQ+
  Data_Dump/IGNOU/Bachelor of Computer Applications/BCS-011 COMPUTER BASICS.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/BCS-012 BASIC MATHEMATICS.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/BCS-031 C++.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/BCS-040 STATISTICAL TECHNIQUES.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/BCS-041 COMPUTER NETWORKS.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/BCS-042 ALGORITHM Design.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/BCS-051 INTRODUCTION TO SOFTWARE.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/BCS-052 NETWORK PROGRAMMING.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/BCS-053 WEB.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/BCS-054 COMPUTER ORIENTED.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/BCS-055 BUSINESS COMMUNICATION.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/BCS-062 E-COMMERCE.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/CIT-001 FUNDAMENTALS OF COMPUTER.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/CIT-002 IT.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/CIT-003 MULTIMEDIA APPLICATIONS.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/ECO-01 BUSINESS ORGANISATION.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/ECO-02 ACCOUNTANCY-I.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/FEG-1-BEGF-101 FOUNDATION COURSE Eng.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/FEG-2 ENGLISH-2.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/MCS-011 PROBLEM SOLVING AND.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/MCS-012 COMPUTER ORGANISATION.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/MCS-013 DISCRETE MATHEMATICS.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/MCS-014 SYSTEMS ANALYSIS AND DESIGN.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/MCS-015 COMMUNICATION SKILLS.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/MCS-021 DATE AND FILE STRUCTURE.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/MCS-022 NETWORKING MANAGEMENT.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/MCS-023 DBMS.pdf
  Data_Dump/IGNOU/Bachelor of Computer Applications/MCS-024 JAVA PROGRAMMING.pdf
Labels: Advanced, SSoC25

#859 #796 PYQ addition of NSUT
  Data_Dump/NSUT Main Campus/pyqs/CG endsem.jpeg
  Data_Dump/NSUT Main Campus/pyqs/ITIM endsem.jpeg
  Data_Dump/NSUT Main Campus/pyqs/MID SEM EXAM.jpeg
  Data_Dump/NSUT Main Campus/pyqs/MidSem paper.jpeg
  Data_Dump/NSUT Main Campus/pyqs/QUE BANK.docx.pdf
  Data_Dump/NSUT Main Campus/pyqs/Tutorial 1.pdf
  Data_Dump/NSUT Main Campus/pyqs/end sem 2.jpeg
  Data_Dump/NSUT Main Campus/pyqs/end sem.jpeg
  Data_Dump/NSUT Main Campus/pyqs/endsem paper.jpeg
  Data_Dump/NSUT Main Campus/pyqs/endsem slides.txt
  Data_Dump/NSUT Main Campus/pyqs/mid sem ctsd.jpeg
  Data_Dump/NSUT Main Campus/pyqs/mid sem paper.jpeg
  Data_Dump/NSUT Main Campus/pyqs/midsem ctsd.jpeg
  Data_Dump/NSUT Main Campus/pyqs/paper mid sem.jpeg
  Data_Dump/NSUT Main Campus/pyqs/sample question.pdf
Labels: Beginner, SSoC25

#864 added academic-rules for du
  Data_Dump/delhi-university/computer-science-hons/Academic-rules/Syllabus/Sem 1/Computer System Architechture/Syllabus-Computer_System_Architecture.pdf
  Data_Dump/delhi-university/computer-science-hons/Academic-rules/Syllabus/Sem 1/Programming using Python/Syllabus-Programming Using Python.pdf
  Data_Dump/delhi-university/computer-science-hons/Academic-rules/Syllabus/Sem 1/mathematics for Computing/Syllabus-Mathematics for Computing.pdf
  Data_Dump/delhi-university/computer-science-hons/Academic-rules/Syllabus/Sem 2/Discrete Mathematics/Syllabus-Discrete_Mathematical_Structures.pdf
  Data_Dump/delhi-university/computer-science-hons/Academic-rules/Syllabus/Sem 2/Object Oriented Programming with C++/Syllabus-Object Oriented Programming with C++.pdf
  Data_Dump/delhi-university/computer-science-hons/Academic-rules/Syllabus/Sem 2/Probability For Computing/Syllabus-Probability_for_Computing.pdf
  Data_Dump/delhi-university/computer-science-hons/Academic-rules/Syllabus/Sem 3/Computer Graphics/Syllabus-Computer_Graphics.pdf
  Data_Dump/delhi-university/computer-science-hons/Academic-rules/Syllabus/Sem 3/Data Structures/Syllabus-Data_Structures.pdf
  Data_Dump/delhi-university/computer-science-hons/Academic-rules/Syllabus/Sem 3/Operating Systems/Syllabus-Operating_Systems.pdf
  Data_Dump/delhi-university/computer-science-hons/Academic-rules/Syllabus/Sem 4/Computer Networks/Syllabus-Computer_Networks.pdf
  Data_Dump/delhi-university/computer-science-hons/Academic-rules/Syllabus/Sem 4/Database Management Systems/Syllabus-Database_Management_Systems.pdf
  Data_Dump/delhi-university/computer-science-hons/Academic-rules/Syllabus/Sem 4/Design and Analysis of Algorithms/Syllabus-Design_and_Analysis_of_Algorithms.pdf
  Data_Dump/delhi-university/computer-science-hons/Academic-rules/Syllabus/Sem 5/Algorithms and Advanced Data Structures/Syllabus-Algorithms_and_Advanced_Data_Structures.pdf
  Data_Dump/delhi-university/computer-science-hons/Academic-rules/Syllabus/Sem 5/Software Engineering/Syllabus-Software_Engineering.pdf
  Data_Dump/delhi-university/computer-science-hons/Academic-rules/Syllabus/Sem 5/Theory of Computation/Syllabus-Theory_of_Computation.pdf
  Data_Dump/delhi-university/computer-science-hons/Academic-rules/Syllabus/Sem 6/Artificial Intelligence/Syllabus-Artificial_Intelligence.pdf
  Data_Dump/delhi-university/computer-science-hons/Academic-rules/Syllabus/Sem 6/Cloud Computing/Syllabus-Cloud_Computing.pdf
  Data_Dump/delhi-university/computer-science-hons/Academic-rules/Syllabus/Sem 6/Machine Learning/Syllabus-Machine_Learning.pdf
  Data_Dump/delhi-university/computer-science-hons/Academic-rules/academic-rules.md
Labels: Intermediate, SSoC25

#865 PYQ+
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BHM-101 CERTIFICATE IN HEALTH CARE WASTE.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BHM-102 WASTE MANAGEMENT (CHCWM).pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BHME-101  INTERRELATIONSHIP BETWEEN ENVIRONMENT AND HEALTH.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BHME-102 WORKER SAFETY AND PATIENT.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BHME-103 Current status of health care waste management and legislation.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BHME-104 Managerial and systems approach.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BHME-105 Special considerations of waste management.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BHME-106 Administrative and legal aspects of waste management.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BHT-001 Foundation Of General Duty Assistance.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BHT-002 Basic Needs Of Patient Care.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BHT-006 Foundation Of Geriatric Care Assistance.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BHT-007 Special Needs Of Geriatric Patients.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BHT-011 Basic Phlebotomy Assistance.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BHT-012 Handling Of Blood Samples.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BHT-016 Basic Home Health Assistance.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BHT-017 Applied Home Health Assistance.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BNS-011 Principles And Practices Of Nursing Administration.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BNS-012 Management of Educational Institutes, Hospitals and Community.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BNS-013 Group Dynamics.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BNS-014 Resource Management.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BNS-031 Concepts And Principles In Critical Care Nursing.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BNS-032 Nursing Management In Critical Care Conditions.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BNS-040 CERTIFICATE IN FIRST AID.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BNS-041 CERTIFICATE IN COMMUNITY.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BNS-042 COMMUNITY Health(CCH).pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BYG-001 Introduction To Yoga And Yogic Texts.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/BYG-002 Certificate Programme In Yoga.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/CNS-AH-001 FUNDAMENTALS OF ADOLESCENCE.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/CNS-HC-001 CERTIFICATE IN HOME BASED HEALTH.pdf
  Data_Dump/IGNOU/SCHOOL OF HEALTH SCIENCE (SOHS)/CNSAH-002  ISSUES AND CHALLENGES DURING ADOLESCENCE.pdf
Labels: Advanced, SSoC25

#871 Added 24 PYQs of IMT Branch Sem 3 ABV-IIITM Gwalior
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Computer Organisation and Architecture (IT202)/Computer Organisation and Architecture (IT202) (2023) major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Computer Organisation and Architecture (IT202)/Computer Organisation and Architecture (IT202) (2023) minor.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Computer Organisation and Architecture (IT202)/Computer Organisation and Architecture (IT202) (2024) (major).pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Computer Organisation and Architecture (IT202)/Computer Organisation and Architecture (IT202) (2024) (minor).pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Database Systems (IT205)/Database Systems (IT205) (2023) major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Database Systems (IT205)/Database Systems (IT205) (2023) minor.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Database Systems (IT205)/Database Systems (IT205) (2024) major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Database Systems (IT205)/Database Systems (IT205) (2024) minor.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Design and Analysis of Algorithms (IT203)/Design and Analysis of Algorithms (IT203) (2023) major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Design and Analysis of Algorithms (IT203)/Design and Analysis of Algorithms (IT203) (2023) minor.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Design and Analysis of Algorithms (IT203)/Design and Analysis of Algorithms (IT203) (2024) major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Design and Analysis of Algorithms (IT203)/Design and Analysis of Algorithms (IT203) (2024) minor.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Discrete Structures (IT201)/Discrete Structures (IT201) (2023) MAJORS.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Discrete Structures (IT201)/Discrete Structures (IT201) (2023) MINORS.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Discrete Structures (IT201)/Discrete Structures (IT201) (2024) MAJORS.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Discrete Structures (IT201)/Discrete Structures (IT201) (2024) MINORS.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Indian Culture, Ethics and Moral Values (HS201)/Indian Culture, Ethics and Moral Values (HS201) (2023) major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Indian Culture, Ethics and Moral Values (HS201)/Indian Culture, Ethics and Moral Values (HS201) (2023) minor.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Indian Culture, Ethics and Moral Values (HS201)/Indian Culture, Ethics and Moral Values (HS201) (2024) major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Indian Culture, Ethics and Moral Values (HS201)/Indian Culture, Ethics and Moral Values (HS201) (2024) minor.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Theory of Computation (IT206)/Theory of Computation (IT206) (2023) major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Theory of Computation (IT206)/Theory of Computation (IT206) (2023) minor.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Theory of Computation (IT206)/Theory of Computation (IT206) (2024) major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/3rd Sem/Theory of Computation (IT206)/Theory of Computation (IT206) (2024) minor.pdf
Labels: Advanced, SSoC25

#873 Added 24 PYQs of IMT Branch Sem 5 ABV-IIITM Gwalior
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Advanced Machine Learning (IT007)/Advanced Machine Learning (IT007) 2023 major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Advanced Machine Learning (IT007)/Advanced Machine Learning (IT007) 2023 minor.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Advanced Machine Learning (IT007)/Advanced Machine Learning (IT007) 2024 major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Advanced Machine Learning (IT007)/Advanced Machine Learning (IT007) 2024 minor.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Business Economics (MS603)/Business Economics (MS603) 2023 major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Business Economics (MS603)/Business Economics (MS603) 2023 minor.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Business Economics (MS603)/Business Economics (MS603) 2024 major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Business Economics (MS603)/Business Economics (MS603) 2024 minor.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Compiler Design (IT302)/Compiler Design (IT302) 2023 major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Compiler Design (IT302)/Compiler Design (IT302) 2023 minor.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Compiler Design (IT302)/Compiler Design (IT302) 2024 major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Compiler Design (IT302)/Compiler Design (IT302) 2024 minor.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Computer Graphics (IT303)/Computer Graphics (IT303) 2023 major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Computer Graphics (IT303)/Computer Graphics (IT303) 2023 minor.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Computer Graphics (IT303)/Computer Graphics (IT303) 2024 major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Computer Graphics (IT303)/Computer Graphics (IT303) 2024 minor.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Microprocessor and Interfacing (EE303)/Microprocessor and Interfacing (EE303) 2023 major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Microprocessor and Interfacing (EE303)/Microprocessor and Interfacing (EE303) 2023 minor.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Microprocessor and Interfacing (EE303)/Microprocessor and Interfacing (EE303) 2024 major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Microprocessor and Interfacing (EE303)/Microprocessor and Interfacing (EE303) 2024 minor.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Trustworthy Artificial Intelligence (IT304)/Trustworthy Artificial Intelligence (IT304) 2023 major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Trustworthy Artificial Intelligence (IT304)/Trustworthy Artificial Intelligence (IT304) 2023 minor.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Trustworthy Artificial Intelligence (IT304)/Trustworthy Artificial Intelligence (IT304) 2024 major.pdf
  Data_Dump/ABV-IIITM Gwalior/Integrated Btech IT + Mtech IT/5th Sem/Trustworthy Artificial Intelligence (IT304)/Trustworthy Artificial Intelligence (IT304) 2024 minor.pdf
Labels: Advanced, SSoC25

#882 Added Delhi University in readme.md
  README.md
Labels: Beginner, SSoC25

#884 Added 24 PYQs of 7th & 8th Sem of ECE branch of HITK
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/6th Sem/Information Theory and Coding (ECE3232)/ECEN 4102- 7th Sem 2020.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/7th Sem/Fundamentals of Operating Systems (CSEN4121)/CSEN 4121- (Backlog) 7th Sem 2021.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/7th Sem/Fundamentals of Operating Systems (CSEN4121)/CSEN 4121- 7th Sem 2021.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/7th Sem/Fundamentals of Operating Systems (CSEN4121)/CSEN 4121- 7th Sem 2022.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/7th Sem/Fundamentals of Operating Systems (CSEN4121)/CSEN 4121- 7th Sem 2023.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/7th Sem/Fundamentals of Operating Systems (CSEN4121)/CSEN 4181- 7th Sem 2020.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/7th Sem/Network Security (ECEN3234)/ECEN 3234- 6th Sem 2021.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/7th Sem/Network Security (ECEN3234)/ECEN 3234- 6th Sem 2022.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/7th Sem/Network Security (ECEN3234)/ECEN 3234- 6th Sem 2023.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/7th Sem/Network Security (ECEN3234)/ECEN 3234- 6th Sem 2024.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/7th Sem/Software Defined Radio (ECEN4121)/ECEN 4121- 7th Sem 2022.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/7th Sem/Software Defined Radio (ECEN4121)/ECEN 4121- 7th Sem 2023.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/8th Sem/Application of Green Energy (ECEN4249)/ECEN 4249- 8th Sem 2023.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/8th Sem/Application of Green Energy (ECEN4249)/ECEN 4249- 8th Sem 2024.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/8th Sem/Fundamentals of Cryptography (INFO4221)/INFO 4221- 8th Sem 2022.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/8th Sem/Fundamentals of Cryptography (INFO4221)/INFO 4221- 8th Sem 2023.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/8th Sem/Fundamentals of Cryptography (INFO4221)/INFO 4221- 8th Sem 2024.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/8th Sem/Fundamentals of Cryptography (INFO4221)/INFO 4281- 8th Sem 2018.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/8th Sem/Fundamentals of Cryptography (INFO4221)/INFO 4281- 8th Sem 2019.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/8th Sem/Fundamentals of Cryptography (INFO4221)/INFO 4281- 8th Sem 2021.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/8th Sem/Fundamentals of Cryptography (INFO4221)/INFO 4281- 8th Sem 2022.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/8th Sem/Nanoelectronics & Nanophotonics (ECEN4244)/ECEN 4244- 8th Sem 2022.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/8th Sem/Nanoelectronics & Nanophotonics (ECEN4244)/ECEN 4244- 8th Sem 2023.pdf
  Data_Dump/Heritage Institute of Technology, Kolkata/05. Electronics and Communication Engineering (ECE)/8th Sem/Nanoelectronics & Nanophotonics (ECEN4244)/ECEN 4244- 8th Sem 2024.pdf
Labels: Advanced, SSoC25
